### ISSUE TITLE
Data and Time zone in website configuration issue

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#1]
I can't change date format.  Also when trying to change time zone they are all the same time -5 is this fixed next update.

**Comment by spirogg** [comment]
have the same issue . hope this will be fixed
example " y-m-d " I want m-d-y or d-m-y or change it to what ever we want in admin section and changes format for all pages - users and forms.. please thanks

**Comment by sakydev** [comment]
Multiple timezones have been added
