### ISSUE TITLE
EMAIL NOTIFICATION FOR FRIEND REQUEST, RECEIVED MESSAGE

### ISSUE THREAD

**Issue by husk04** [arslancb/clipbucket#10]
i get new account email notification, video activated email notification but i donot get new message notification, friend request notification.
Also there should be a icon in homepage when you login that tells you you have notifications, mails,friend requests. having to go to my account to check that is hard work especially when there is no email notification for that

**Comment by spirogg** [comment]
I agree

Spiro

**Comment by sakydev** [comment]
Your recommendations will definitely be considered. Thank you for using ClipBucket

**Comment by sakydev** [comment]
@sikanderzel just took care of that! Have fun with ClipBucket
