### ISSUE TITLE
Related Videos on Watch Video Page cb 2.8.1 rc1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#105]
HI,
in the default template is showing Most recent video as popular in watch video page but its not good i think.. if you display related videos hare it will be very good.. and we can easily decrease the bounce rate in google.

check the screen shot.

![untitled-8](https://cloud.githubusercontent.com/assets/4317570/15383069/6e672c40-1da9-11e6-95e9-c48fef4f76a7.jpg)

**Comment by spirogg** [comment]
Thanks @saqirzzq
