### ISSUE TITLE
groups show when using different lang ie Greek Lang - in MY ACCOUNT - english works normal

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#106]
Hi when I view My Account : and use a different language ie Greek, I have a category and links to Groups. If I use english lang, the category and links is playlist
http://discourse.clipbucket.com/uploads/default/_optimized/1fe/de4/ab10de3702_622x499.JPG
http://discourse.clipbucket.com/uploads/default/_optimized/a53/a47/a3c4837d73_630x500.JPG

in different lang, under Category Video : is Groups. Also when clicking on first link under groups the page becomes blank in center. almost same as 404 error but no error shown 
/manage_groups.php ( BLANK PAGE CENTER )
/create_group ( seems to be ok )
/manage_groups.php?mode=joined ( BLANK PAGE CENTER )

in english lang, Under Category Video : is Playlist
no links to groups
![blank](https://cloud.githubusercontent.com/assets/17736688/15386887/c65cec94-1d6f-11e6-8020-88c2233a056b.JPG)

Spiro

**Comment by spirogg** [comment]
![manage-groups-only-with-different-lang-file-showup](https://cloud.githubusercontent.com/assets/17736688/15386905/ebc5dd4c-1d6f-11e6-8c0c-62b5b0a3d5e6.JPG)
![no-group-here-just-playlist-under-video](https://cloud.githubusercontent.com/assets/17736688/15386906/ebd8b67e-1d6f-11e6-8b05-4873e48eb7ea.JPG)

**Comment by move-IT-online** [comment]
It´s depending of what you have in your used (greek) language file. Try to comment out the lines referencing groups.

**Comment by spirogg** [comment]
I used the new language updater. But I have not rc1 installed. I have svn master installed. And it worked for me. Just this issue. I will check to comment out 

Cause this is a bug for sure. Since English prior to creating anothrr language works fine without having to comment out anything. 

Thanks

**Comment by sikanderzel** [comment]
Issue resolved.
