### ISSUE TITLE
Max video Processes at once cb 2.8.1 rc1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#107]
Max video Processes at once is set to 2 
i have check the server cpu its 99% used then i loged in via ssh and run htop command its look like this.

![untitled-10](https://cloud.githubusercontent.com/assets/4317570/15387083/81186c76-1dc4-11e6-988f-3acef670d3bc.jpg)

**when conversion complete the htop look like this**

![untitled-11](https://cloud.githubusercontent.com/assets/4317570/15387161/f18c6e62-1dc4-11e6-8949-bc4dbebb3b7e.jpg)

**Comment by sakydev** [comment]
Issue resolved now.
