### ISSUE TITLE
critical issue in video manager cb 2.8.1 rc1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#108]
e.g. you have upload 20 videos today and you want to delete one of them. you go under admin area and video manager and click on the drop down menu and hit the delete button.. all mp4 files and thumbs will auto delete that uploaded today .. this happen with me 2 time today..

**don't try on live site to delete video from drop down menu ... that appear with each video on right side in video manager in admin are.**

![untitled-12](https://cloud.githubusercontent.com/assets/4317570/15387423/8ab409d2-1dc6-11e6-9ae6-81ceb25c63eb.jpg)

**Comment by sakydev** [comment]
Its really troublesome to re-create this issue. If you can give some insight on how we can do so, we'll fix this issue for sure. Otherwise I'll have to close this issue.
