### ISSUE TITLE
no reply option in received message

### ISSUE THREAD

**Issue by husk04** [arslancb/clipbucket#11]
PlEASE there should be a reply message option in every received message

**Comment by sakydev** [comment]
Issue is valid. Thank you @husk04  for reporting this. Will be fixed soon.

**Comment by spirogg** [comment]
@fahad-cb @saqirzzq hi guys any word on this one ? would be nice to have it :)  thanks again for all your help in taking care of all the issues and bugs :) you guys rock!!!!!!

**Comment by aliawancb** [comment]
@fahad-cb Since we will have a patch soon so may be,,,

**Comment by Awais-cb** [comment]
Added reply option in received messages!
