### ISSUE TITLE
Most viewed today, pr time span issue with SEO url

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#113]
It displays no video in Most viewed today if seo url are on http://prntscr.com/b6a7ry

**Comment by spirogg** [comment]
videos/all/All/view_all/today/1&timing=time

i upload 3 videos today shows no videos

**Comment by sikanderzel** [comment]
it's working

**Comment by spirogg** [comment]
Did you try all today with seoburl on and off just in case one turns it off and one turns it on. Or something else you fixed fixed this issue. ??

**Comment by sikanderzel** [comment]
resolved..
