### ISSUE TITLE
ClipBucket 2.8.1 RC1 Unable to open Rss

### ISSUE THREAD

**Issue by youtubetomp3converterapi** [arslancb/clipbucket#114]
http://demo.clipbucket.com/rss/recent
http://demo.clipbucket.com/rss/views
http://demo.clipbucket.com/rss/rating
http://demo.clipbucket.com/rss

It is very important for SEO, I'm waiting for it to be addressed ...

**Comment by spirogg** [comment]
me too please fix thanks
