### ISSUE TITLE
/edit_video.php images not showing - see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#116]
hi here are some images not showing. 
![edit-videos-1](https://cloud.githubusercontent.com/assets/17736688/15445502/5548979a-1ec5-11e6-851a-956c193a8f22.JPG)
![edit-videos-2](https://cloud.githubusercontent.com/assets/17736688/15445506/554b73ac-1ec5-11e6-9443-334ee5ac62ec.JPG)
![edit-videos-3](https://cloud.githubusercontent.com/assets/17736688/15445503/5549a7fc-1ec5-11e6-89c8-408a9eb9e995.JPG)
![edit-videos-4](https://cloud.githubusercontent.com/assets/17736688/15445504/554a2650-1ec5-11e6-963e-5af770b9cb6c.JPG)
![edit-videos-5](https://cloud.githubusercontent.com/assets/17736688/15445505/554a8c62-1ec5-11e6-879a-df887999679c.JPG)

**Comment by spirogg** [comment]
![edit-videos-5-without-comments](https://cloud.githubusercontent.com/assets/17736688/15446409/dfaca6cc-1ee5-11e6-8fef-d76df8e43975.JPG)

**Comment by spirogg** [comment]
Anyone else see this issue. ??

**Comment by move-IT-online** [comment]
I have the same issue

**Comment by sikanderzel** [comment]
resolved

**Comment by spirogg** [comment]
Thank you @sikanderzel you are doing awesome and always patching things.. I appreciate your speed and dedication to clipbucket my friend... CC @arslancb @fawazcb 

Great Job

Spiro
