### ISSUE TITLE
edit_video.php comments not able to delete - edit - update not sure what function it has see photo

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#117]
here is the photo, seems like the area where there is suppose to be 3 images has no function to edit the comment field. this has to be a bug

see photo
![edit-videos-comment-section-to-delete-update-not-working](https://cloud.githubusercontent.com/assets/17736688/15445519/a13a8398-1ec5-11e6-9dfb-3886bfc1148a.JPG)

**Comment by sikanderzel** [comment]
Done now admin can delete comments on videos.
