### ISSUE TITLE
when viewing a video and there is no comment - ( the word NONE is under circle user) see pic

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#118]
![the-word-none-is-showing-from-nowhere](https://cloud.githubusercontent.com/assets/17736688/15445603/548d5c9e-1ec7-11e6-909f-d5ef5ae3a454.JPG)
![the-word-none-after-leaving-comment-also](https://cloud.githubusercontent.com/assets/17736688/15445602/548cef2a-1ec7-11e6-9de8-dafb2f8f3172.JPG)
![the-word-none-after-comment-after-refresh-no-more-word](https://cloud.githubusercontent.com/assets/17736688/15445601/548cbc58-1ec7-11e6-8dfc-55c4a30f0300.JPG)

when no comments on videos, the word "none" appears under the users circle - photo
after leaving a comment it still shows until you refresh ??

please fix

**Comment by sakydev** [comment]
On the hunt....
