### ISSUE TITLE
can't remove video from collection even from admin area cb 2.8.1 rc1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#129]
i have add video in my collection by mistake now i want to remove that video from this collection there no option on user end .. but i can't even from that video from admin area.. the option is broken in admin area..

![untitled-3](https://cloud.githubusercontent.com/assets/4317570/15468058/67a0ef18-20fb-11e6-846f-f8349e438b2b.jpg)

**Comment by sikanderzel** [comment]
Resolved
