### ISSUE TITLE
links in top of admin area not working example show

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#13]
hi when in admin panel and selecting any area the top part of link doesn't work

example : (( Stats And Configurations [these links not work all of them] )) > Website Configurations
example : (( Groups [this link not working] )) > Add Group

all links like this not work is this done for reason or a bug
https://mydomain.com/admin_area/reports.php#
https://mydomain.com/admin_area/add_group.php#

thanks
Spirogg

**Comment by sakydev** [comment]
Your ClipBucket installation is probably having some issue with loading jQuery files. Issue is not found in ClipBucket. Kindly check your console for errors.
