### ISSUE TITLE
Button alignment on IE11 (4x3 monitor) CB2.8.1 RC1

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#133]
Hi, 
When using IE11 in **FULL SCREEN ONLY** and a 4x3 monitor, 
there is a problem with the button alignment.
![4x3_button_problem](https://cloud.githubusercontent.com/assets/19185161/15572618/57655bec-234a-11e6-8170-d0380cc24a05.PNG)

**Comment by pcmcis** [comment]
Hi,
I have seen the same problem also in Chrome when a user is using more than 15 (17) characters in his username.

Thanks
pcmcis

**Comment by sakydev** [comment]
Issue has been resolved now.  Keep enjoying ClipBucket
