### ISSUE TITLE
order of 240 360 480 720 is backward in cb player 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#134]
![order-of-240-360-460-720-etc-incorrect-order](https://cloud.githubusercontent.com/assets/17736688/15595942/e2425c68-2388-11e6-9eee-b4b043cade87.JPG)
http://discourse.clipbucket.com/t/order-of-video-conversion-240-360-480-numbers-in-player-are-backwards-see-photo/1903
order of video conversion 240 360 480 numbers in player are backwards see photo

I upload videos and they show 480 then 360 above it.. should be 360 first then 480 above that

**Comment by fahad-cb** [comment]
fixed

**Comment by spirogg** [comment]
@fahad-cb @saqirzzq @sikanderzel 

where is this updated file ? is it the video player, i uploaded all files from github still video is same ?
should this not be lowest number is at bottom (Example: 240) and (1080 would be at the top ) ?
can you please show me to commit - file you fixed ?
