### ISSUE TITLE
logo upload in admin instead of ftp upload please 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#136]
logo upload in admin instead of ftp upload please 

can we have in admin. Upload logo. Instead of FTP logo.png. I want to try several logos to see which one looks best. But is really a pain to FTP and go back n forth to change. Can you please add upload logo in admin instead. I'm sure it really simple to do

PLEASE CLIPBUCKET TEAM. make this feature I'm sure lots of people will agree with me.

Thank you Spiro

**Comment by spirogg** [comment]
I saw a commit on this. Were you able to get  this working. :)

**Comment by sikanderzel** [comment]
it's working now.
