### ISSUE TITLE
Other Users are not able to add Photos to this collection

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#137]
Other Users are not able to add Photos to this collection

http://discourse.clipbucket.com/t/add-to-collection-not-working/1905

users cannot add to collection even though we have added the option to allow other users to add to our collection, the collection of that user does not show as an option

**Comment by sikanderzel** [comment]
resolved

**Comment by move-IT-online** [comment]
sikanderzel can you please explain which file(s) i have to change?
