### ISSUE TITLE
The storage engine for the table doesn't support repair

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#138]
_28rc.cb_collection_contributors] note: The storage engine for the table doesn't support repair
_28rc.cb_video_views] note: The storage engine for the table doesn't support repair

 I am running MariaDB is this the script not compatible ? with database ??
or issue in cb_collection_contributors and cb_video_views ?

i did a repair database cause site all of a sudden became slow.. when selecting users in admin

**Comment by spirogg** [comment]
Ok these too ate using InnoDB vs MyISAM this when trying to repair database give this error, I changed to MyISAM and then ran repair database and both said ok , not sure if this is bug ??

please let me know if these 2 need to stay InnoDB or is it ok that i switched to MyISAM

**Comment by sakydev** [comment]
Just let them stay what they are. If you need to make serious database modifications, consult ClipBucket support first.
