### ISSUE TITLE
smaller photos when uploaded resized to big and look really bad

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#139]
http://discourse.clipbucket.com/t/smaller-photos-uploaded-are-too-big-in-viewer-looks-bad-this-really-needs-attention/1910

How can we adjust or add some kind of setting that photos smaller than W x H will be original size
so they don't look stretched out in viewer and make them look bad in viewer and in Thumbs view ?

and also set that If image is greater than W x H and more then the script can resize image to the specified for viewer to look good..

this really needs Clipbucket Dev's Attention

thanks

Spiro

**Comment by sakydev** [comment]
Fixed.
