### ISSUE TITLE
user my account shows all user videos and action button can we hide this ??

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#14]
why do these videos show up in the first place, if i am a user i only want to see my videos not all videos in this area, can you explain reason for this ??

when i am user and i click >>>> My Account 
## Latest Videos

**Videos Details *\*                   **Option**
video1 user                                Action
video2 user                                Action
video3 admin                              Action
I see all videos
should be only user videos         Action

I know you can not edit / delete videos for another user as a user, but looks weird it should be just the users latest videos not all users latest videos 
or 
Is there a way to make CB script (( hide the action button )) if it is not that users video(s), that would be much better only that users video(s) will have the action button ?? 
Can you make this and incorporate into next release ??

Thanks so much you guys ROCK !!!! so does CB :) :+1: 
Spiro

**Comment by sakydev** [comment]
That section is for keeping user updated with what is going around the site by showing the latest videos. It is not a bug. To see your videos only, kindly browser to "Uploaded Videos" section.

Thank you for using ClipBucket :+1:
