### ISSUE TITLE
orphan photos in admin missing select option see photo

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#140]
http://discourse.clipbucket.com/t/orphan-photo-in-admin-missing-select-option-for-photos-see-pics/1919
![orphan-photos-no-select-option](https://cloud.githubusercontent.com/assets/17736688/15653234/41805020-2651-11e6-8dd6-0adc2e0333a7.JPG)

**Comment by sikanderzel** [comment]
resolved..
