### ISSUE TITLE
initially enabled photos in admin uploaded some photos then disabled photos section in admin see pics

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#141]
initially enabled photos in admin uploaded some photos then disabled photos section in admin,
but still shows (( admin has uploaded a new photo 2 days ago )) on user page ?? /user/admin

is this normal or should it hide that part when disabling photos if we initially had photos enabled in admin ??

![if disable photos after already enabled still shows uploaded photos](https://cloud.githubusercontent.com/assets/17736688/15653459/d2dff826-2652-11e6-92ef-23d1bdab8190.JPG)

Thanks Spiro

**Comment by sikanderzel** [comment]
In future..
