### ISSUE TITLE
When set channels to off should go to sign up page not message 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#145]
When set channels to off should go to sign up page not message  that says click here to signup or login. Cause there is no link to either one of the words. 
Should redirect to signup page. Also this is better when using another language so it doesn't have to translate words. Just redirect to page. 

Maybe all options when turned off should redirect to signup page. ??

**Comment by spirogg** [comment]
![click-here-to-login-or-register](https://cloud.githubusercontent.com/assets/17736688/15850447/93c23ce2-2c5d-11e6-930d-b0a7a55f70a7.JPG)

no links..

**Comment by sakydev** [comment]
Adding links is a better idea than redirecting user. Will be done

**Comment by sakydev** [comment]
Just checked and it seems to work ok. Page is not rendered at all as it should be.
