### ISSUE TITLE
Libfdk_aac when crons on in admin not working if crons off works 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#148]
Libfdk_aac in conversion settings in admin area. when crons  is set to on in admin conversion keeps saying processing. If we set to off conversion processes and completes ??

**Comment by spirogg** [comment]
Maybe in cron files .php  there is encoding issue ? 

or could these changes have caused the issue ??
https://github.com/arslancb/clipbucket/commit/523480cb4b2aa6a4fa5bddbbd4868dba9f7b990c
thanks trying to help - brainstorm to make thsi easier to fix :+1:

**Comment by sakydev** [comment]
That is because you then need to set crons from server side which will verify if those videos are converted or not and update their statuses manually.

**Comment by spirogg** [comment]
Already set. On server sir.

**Comment by spirogg** [comment]
I use the code from CB helper plugin. Still face sake issue. The first one never seems to run. The second and third do run it shows also in CB plugin helper that 1 never runs and 2 and 3 always run. ?

**Comment by spirogg** [comment]
yes setup cron in cpanel

php -q /home/t/public_html/actions/video_convert.php >/dev/null 2>&1
and tried 
/usr/local/bin/php -q /home/t/public_html/actions/video_convert.php >/dev/null 2>&1 
and also tried 
/usr/local/bin/php -q /home/t/public_html/actions/video_convert.php

Last Run : No date provided Array 
the 2 others show they did work in clipbucket helper plugin cron jobs
Command
php -q /home/t/public_html/actions/video_convert.php >/dev/null 2>&1 
Last Run : No date provided Array
php -q /home/t/public_html/actions/verify_converted_videos.php >/dev/null 2>&1 
Last Run : 13 seconds ago
php -q /home/t/public_html/actions/update_cb_stats.php >/dev/null 2>&1 
Last Run : 13 seconds ago

thanks
Spiro

**Comment by spirogg** [comment]
@saqirzzq see last post of my cron

**Comment by spirogg** [comment]
@saqirzzq did you fix this already at the link below ?

https://github.com/arslancb/clipbucket/commit/a5878dabe99d6e2c80ac37646249b6e9d9ea7983

**Comment by sakydev** [comment]
Yes. Use Crons has been fixed. Go enjoy
