### ISSUE TITLE
store guest session not allowing to set when select yes or no

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#149]
store guest session not allowing to set when select yes or no

![store-guest-session-not-allow-to-select](https://cloud.githubusercontent.com/assets/17736688/15905177/8b447ce8-2d79-11e6-9626-eb0838326cb9.JPG)

**Comment by cybernetwebdesign** [comment]
@spirogg Hi spirogg, let them finish RC2, postpone reporting a bug in RC1, then please continue looking for all the bugs in RC2, a minimum of other users already can use RC2, please continue hunting bugs if suda RC2 release.

**Comment by youtubetomp3converterapi** [comment]
@spirogg Hi spirogg, let them finish RC2, postpone reporting a bug in RC1, then please continue looking for all the bugs in RC2, so that other users can already use RC2, please continue hunting bugs if RC2 has been released. Thx

**Comment by spirogg** [comment]
I have updated to the master as of today. So really I am reporting as they fix latest  issues on git hub  :) 
But if you like I will stop :)

**Comment by youtubetomp3converterapi** [comment]
@spirogg It's good, make a list of all the bugs you find, and post all the bugs list here if RC2 has been released, :+1:

**Comment by spirogg** [comment]
this should be an easy one --- any update on this please @saqirzzq @sikanderzel @jamilrehman 

thanks guys

**Comment by sakydev** [comment]
Fixed.
