### ISSUE TITLE
# BUG language needs refresh to set cookies and reaches 100% but have to refresh again to get lang to show ??

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#150]
ok when it say refresh to set cookie, right mouse click and refresh, then select Language and generate.. i just try on new fresh install it did same for greek language i right mouse click and refresh browser then select greek and it start working

after finish its stays blue... @ 100% 

but need to click lang on left menu and and refresh again the page and it will change and show the new lang .. 

this is bug to much work to get lang to work

but work around is above

Spiro

**Comment by spirogg** [comment]
Any idea if this issue was fixed in another bug. ??

**Comment by spirogg** [comment]
I see after uploading Master as of 6-19-2016 i can edit the database by hand and to save i click update and then go back to language - then actions and then select from drop down Recreate Pack and your changes will appear. Just FYI if any needs to edit by hand the language and save it

**Comment by sikanderzel** [comment]
When it reaches 100% after 2-3 minutes page itself got refreshed...
