### ISSUE TITLE
language-text missing see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#152]
![language-missing-some-text](https://cloud.githubusercontent.com/assets/17736688/15957208/2aefb4f8-2eb3-11e6-84c6-97ca8c90fce7.JPG)

![when click on video top menu it shows video top right in english first then dropdown is ingreek_bivteo](https://cloud.githubusercontent.com/assets/17736688/15957227/3e765dc4-2eb3-11e6-8ac8-2356dd94d128.JPG)
![same as videos and photos - now channels same issue](https://cloud.githubusercontent.com/assets/17736688/15957238/57af3d9c-2eb3-11e6-9a5f-93515362a0ef.JPG)

**Comment by spirogg** [comment]
![same as video- it haapens to photos also](https://cloud.githubusercontent.com/assets/17736688/15957245/6f0f0792-2eb3-11e6-8022-d61f88057eaa.JPG)

**Comment by spirogg** [comment]
Just an explanation to one thing in photo. In the drop down when I use Greek language. The video shows in in english for initial word then when click on drop down its in Greek. ??

**Comment by spirogg** [comment]
saqirzzq

**Comment by sakydev** [comment]
I'm working on languages part right now. It will be fixed today
