### ISSUE TITLE
search in search bar for video - in greek language ( other language) doesnt work ?

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#156]
michalis_tzouganakis
![see photo but when change drop down to greek language bivteo doesnt work](https://cloud.githubusercontent.com/assets/17736688/15958152/7b146252-2eb9-11e6-835c-052462cb7c6f.JPG)

when initial drop down search for videos is on english word it works, but when switch drop down to Greek word for videos = Bivteo, search in greek language ( other language) when select that languages drop down for video channel etc.. doesn't work ?
![search in different language - drop down search by greek word video bivteo- search not working](https://cloud.githubusercontent.com/assets/17736688/15958228/d84d546a-2eb9-11e6-849b-b739152e67eb.JPG)

**Comment by move-IT-online** [comment]
I tested your Issue with my freshly installed CB 2.8.1 RC2 version and switched between english and german, but works as expected.

BTW: Searching for more than 1 Word is NOT as expected. When searching for 2 words with blanks between the words that contain in the title of a video that video cannot be found.

**Comment by spirogg** [comment]
Do you see under drop down always in German language. Or is initial drop down video in English ??

**Comment by spirogg** [comment]
Then when you select drop down it is in German ??

**Comment by sakydev** [comment]
Issue has been resolved!
