### ISSUE TITLE
language missing text 2.8.1 rc2 login - register page 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#157]
![language-missing-some-text](https://cloud.githubusercontent.com/assets/17736688/15958321/7ecf0b6c-2eba-11e6-8194-d1a5fb958419.JPG)
![language-missing-some-text](https://cloud.githubusercontent.com/assets/17736688/15958335/995cecba-2eba-11e6-91ca-d3f6d24c1819.JPG)

**Comment by spirogg** [comment]
also main login and signup page ? no language files there at all can you make this ? very important to be able to read the other language to understand how to sign up
![laungage-text-bug](https://cloud.githubusercontent.com/assets/17736688/15958348/ad019f7c-2eba-11e6-8fcd-a5f29578b093.JPG)

**Comment by sakydev** [comment]
Killed!
