### ISSUE TITLE
file extention in photo upload page photo titile and caption RC2

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#158]
file extention in photo upload page photo titile and caption RC2
thumb not generated on upload page .. check the screen shot.

![untitled-2](https://cloud.githubusercontent.com/assets/4317570/15959358/d087f01e-2f13-11e6-8863-5085514e541c.jpg)

**Comment by spirogg** [comment]
I have the same issue.

**Comment by move-IT-online** [comment]
I confirm that. Same Issue here.

**Comment by sakydev** [comment]
I'm onto issue hunt! Will be killed shortly

**Comment by move-IT-online** [comment]
Patch imported and .jpg ending in title and description goes away, but picture preview (thumbnail) still missing

**Comment by sakydev** [comment]
Also update actions / photo_uploader.php and includes/functions_photo.php

That should do it

**Comment by move-IT-online** [comment]
Working! Thank you saqirzzq!
