### ISSUE TITLE
ClipBucket 2.8.1 RC2 - XML attributes are missing. All tag does not have the necessary attributes.

### ISSUE THREAD

**Issue by youtubetomp3converterapi** [arslancb/clipbucket#159]
![2](https://cloud.githubusercontent.com/assets/5706519/15965125/3df77368-2f46-11e6-83d5-fb70aaa90262.png)
![1](https://cloud.githubusercontent.com/assets/5706519/15965127/3e2350a0-2f46-11e6-80e1-450164a70f32.png)

It is very important for SEO, I'm waiting for it to be addressed ...

**Comment by spirogg** [comment]
I agree. Thanks

**Comment by youtubetomp3converterapi** [comment]
@spirogg Thank's ...

**Comment by spirogg** [comment]
i dont think they are going to fix this one... this is a plugin they are selling nija SEO :rotating_light:

**Comment by Awais-cb** [comment]
@spirogg can you please explain which attribute exactly is missing?

**Comment by spirogg** [comment]
@Awais-cb Awais its been so long, i don't remember maybe this has been fixed ?? , if exists after i try i will repost 

thanks
