### ISSUE TITLE
can't upload video in github setup git dev to see changes but cant upload video 3 days ago

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#16]
Hi, 
can't upload video in github SVN, 
I setup git dev to see changes but cant upload videos
I set this up 3 days ago. so not sure if there are new changes that fixed this ? says uploaded and when click submit for edit title description etc says video not found, i have latest cb version working great on my live site but svn not working when try to upload videos

i have latest ffmpeg etc etc

**Comment by sakydev** [comment]
Kindly make sure your files are writable. Moreover, check for errors in console. 

Thank you.

**Comment by spirogg** [comment]
Upload form in dev version is broken and it do not work, Here is error from console for upload form
Error in parsing value for 'vertical-align'. Declaration dropped. upload:659:21
Unknown property 'user-select'. Declaration dropped. upload:1:124

**Comment by sakydev** [comment]
We are still working on Upload page. Will be fixed soon.

**Comment by spirogg** [comment]
Has this been fixed ? I await the new cb with excitement and happiness. :)
