### ISSUE TITLE
Email notifications issue

### ISSUE THREAD

**Issue by sysndevops** [arslancb/clipbucket#160]
User activation emails are not working upon new sign up. I also verified resending the activation email from the admin dashboard. Receiving below error:

```
Mailer Error: You must provide at least one recipient email address.
```

I'm using below settings to configure the email address:

Select Mailer Type php Mail() or SMTP : SMTP
SMTP Host-if using smtp, Set SMTP server port : mail.mydomain.com
SMTP Username-if using smtp, please enter SMTP username : user@mydomain.com
SMTP Password-Enter SMTP password : user email account password

Thunderbird email client connects to the specific user account without any issues and sends email using smtp port 25.

I have attached the error screenshot and I'm using ClipBucket 2.8.1 RC 2 version.
![clipbucket_error](https://cloud.githubusercontent.com/assets/19859151/15968382/51283b68-2f49-11e6-8e9c-749f22d9f513.png)

**Comment by spirogg** [comment]
Confirmed no emails sent for verification or to signup activation. Please fix.

**Comment by spirogg** [comment]
Can you please fix this first ? We need to be able to have new signups via activation email please.

**Comment by spirogg** [comment]
@saqirzzq can you please work on this one :)

**Comment by spirogg** [comment]
all you handsome guys @saqirzzq @fahad-cb @jamilrehman  have photos 
except for >> @sikanderzel  what happened ?? :) 
can you guys please please work on this one to be able to have users activate and get activation email to login please :+1: :100: :)

thank you so much Spiro

**Comment by spirogg** [comment]
@saqirzzq @sikanderzel @fahad-cb @arslancb @jamilrehman any update on getting the activations to work ?

**Comment by spirogg** [comment]
@saqirzzq. Please my brother can you fix this one  or give me solution to allow signups and activation.

**Comment by sikanderzel** [comment]
it's working kindly check demo.

**Comment by sysndevops** [comment]
Thank you

**Comment by sysndevops** [comment]
I just tested using ClipBucket 2.8.1 RC 2 version. Still its not working. Same error exists. The clip bucket official demo url is installed with V-2.8.1 beta edition and it just shows email notification sent successfully. But it does not reach my inbox.
