### ISSUE TITLE
Photo Views 0 in admin area all the time

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#164]
1. there is no count for photo in dropdown menu in admin area Waiting for Approval .
2. Photo Views 0 all the time in admin area.
3. there is no menu link for InActive Photos.

check the screen Shot.
![untitled-1](https://cloud.githubusercontent.com/assets/4317570/16034480/8b1ced20-322b-11e6-93d6-33aff190bd3f.jpg)

**Comment by spirogg** [comment]
confirmed no views show in admin_area, also is photo view per IP address - user  or refreash will count how ma y views in front side not admin
- cause i refresh 10 - 20 times on photo page only show 1 photo view  no matter how many times you view it
