### ISSUE TITLE
collection categories does not show when trying to add a new collection ?

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#165]
Hi not sure, but If i add some categories in ( video category but NONE in photo category ) should these categories show in 
( Collection category ) when trying to add a new collection ?  
or will collection categories only show when adding (photo categories) and then the categories will be there to choose from, so I can add a new collection to that category? 

thanks
Spiro

**Comment by spirogg** [comment]
So far when adding video categories, then trying to create a collection it only has uncategorized. For category. But when I add a category in photos. Now we can create a collection to photo category only. But not video category.

**Comment by sikanderzel** [comment]
There are two types of categories 
1.) collection category.
2.) video category.
that's it . photos itself have no category. each photo is assigned by a collection category...
