### ISSUE TITLE
edit video missing some pics - icons ? and need ajust placement of Broadcast Options lower

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#169]
edit video missing some pics - icons ? and need ajust placement of Broadcast Options lower
see photos
![edit video missing pics](https://cloud.githubusercontent.com/assets/17736688/16038533/fbde560c-31ea-11e6-983a-e4cd572ab26c.JPG)
![edit video missing pics 2](https://cloud.githubusercontent.com/assets/17736688/16038539/01b2ac86-31eb-11e6-997c-e9309c245b55.JPG)
![edit video ajust wording broadxast options](https://cloud.githubusercontent.com/assets/17736688/16038546/06432668-31eb-11e6-80ee-9afa0794596d.JPG)

**Comment by move-IT-online** [comment]
I confirm that, but strangely it´s not on all videos. Maybe it depends how they came into CB (uploaded file/embed code/included by link).
