### ISSUE TITLE
My Account and Manage Videos 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#17]
3 days ago Views : 9
Active Successful Viewed Never <<<<<< (( says - Viewed Never )) but 9 views plus i viewd a few times ?

other example : 

 5 days ago Views : 26
## Featured Active Successful Viewed Never 

ok sorry now shows  
3 days ago Views : 9 <<<<
Active Successful Viewed 5 hours ago  <<<<<
is this delay in cache maybe ? still shows 9 views ?? I just viewed again while writing this and then it showed 5 hours ago but still 9 views total ? 

maybe you can just check to see if counts work well and shows - or is this cbstats that are set by when we have cron set to update ??

_PS - does video have to play completely in order for a count to show ? 1 view  _

thanks for all your help

**Comment by sakydev** [comment]
If you view a video 100 times, it will be counted as 1 view only. Views are counted on per unique user. One view per user. So in order for a video to have 100 views, it must be visited by 100 users

Thank you for taking interest in ClipBucket though :+1:
