### ISSUE TITLE
Remotely linked and embedded Videos not editable

### ISSUE THREAD

**Issue by move-IT-online** [arslancb/clipbucket#170]
With CB 2.8.1 RC2 it´s not more possible to edit the Code of embedded Videos and the URL of external linked Videos (which is nearly the same thing).

Before the Update from 2.8.1 RC1 to 2.8.1 RC2 this was okay.

**Comment by sikanderzel** [comment]
embed code is editable however external link is not. We will fix it..

**Comment by sikanderzel** [comment]
Fixed ..

**Comment by move-IT-online** [comment]
Patch applied but not saving external URL via Admin Panel or via User
editing Video Panel

2016-07-01 14:05 GMT+02:00 sikanderzel notifications@github.com:
