### ISSUE TITLE
user activation - emails.. can you please fix this 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#172]
can we please get a fix for this or even a temp fix for now ... This is for new users to be able to use the login page and get activation emails ? please guys

thanks
Spiro

**Comment by spirogg** [comment]
@saqirzzq any update on this one ??

**Comment by spirogg** [comment]
@saqirzzq Hi can you please work on this one tonight for me  please. It doesn't work for me. ?? I'm help catch bugs if you can do me this one favor. And see this one work so I can get update please. Please. 

Thank you so much in advance. 

Spiro

**Comment by spirogg** [comment]
@saqirzzq @fahad-cb @sikanderzel can you guys please fix this or tell me what i need to do to make this active, when i signup i get no emails for activation ??

**Comment by sikanderzel** [comment]
kindly check http://demo.clipbucket.com/ and try signup, you will get an activation mail.

**Comment by spirogg** [comment]
ok working now !!!!!! thanks thanks thanks :)
