### ISSUE TITLE
wording has _ in it Terms_Of_Service should be Terms Of Service in footer

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#175]
wording has _ in it ( should be: Terms Of Service ) now is Terms_of_service
![terms_0f_service](https://cloud.githubusercontent.com/assets/17736688/16180636/87093a26-3650-11e6-9d5e-e47170db261d.JPG)

**Comment by sakydev** [comment]
Looks you had some issue with updating svn because it seems alright at my end
http://prntscr.com/bimety

**Comment by spirogg** [comment]
not sure why, but I change some wording manually in en language then went to look at home page and saw this ? i am reinstalling fresh from git hub and will post again if same issue on new install - i am going to delete old database create new one and delete everything off server and reinstall script..

**Comment by spirogg** [comment]
when I install from github, i jut do normal install process /cb_install is this correct ? or am i missing a first step ?

**Comment by spirogg** [comment]
![terms_0f_service](https://cloud.githubusercontent.com/assets/17736688/16220053/f7445aa0-374f-11e6-8bcc-bf30db90478b.JPG)
new install from guthub is in the pages menu with terms_of_service
![manage-pages](https://cloud.githubusercontent.com/assets/17736688/16220254/502fc9c8-3751-11e6-9b5c-9cabc6f9ae2d.PNG)
