### ISSUE TITLE
I cannot copy and paste the URL from (Link This Video) when trying to share 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#177]
as of today Master - I cannot copy and paste the (Link This Video) URL.. when trying to share the URL in the watch video page see photo
![link-this-video-cannot-select-to-copy-link](https://cloud.githubusercontent.com/assets/17736688/16180686/8ddfd7cc-3652-11e6-8cb5-e6ab1cc1845c.JPG)

**Comment by sakydev** [comment]
Seems invalid http://prntscr.com/bizfmw

**Comment by spirogg** [comment]
Nope. Same issue with seo URL on. When in Firefox I try to select this it shows me a red little circle with a red line in it so I cannot copy it. ?

**Comment by sakydev** [comment]
That means you cannot edit it. You can still copy it though

**Comment by spirogg** [comment]
I just reinstall CB just now. Created new dB and deleted everything off the domain and reinstalled. ? Same issue. Cannot select the line to copy.

**Comment by spirogg** [comment]
No sir cannot copy

**Comment by spirogg** [comment]
Can we make this like the embed code section. Where you select and link is copied 
![14664927559371557328046](https://cloud.githubusercontent.com/assets/17736688/16220800/bc8635b4-3754-11e6-8fc2-835b520344d6.jpg)

**Comment by move-IT-online** [comment]
I have the same Issue like spirogg: with an updated Installation of CB 2.8.1 RC2 it´s not possible to copy the "Link this Video" Link. When I hoover the Mouse over the Link I get a red Symbol meaning it´s forbidden.

**Comment by spirogg** [comment]
Resolved as of 7-1-2016
