### ISSUE TITLE
 'cache' directory is not writeable for resizing thumbs - Directory not added by script

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#179]
![cache-directory-not-writable-for-resizing-thumbs](https://cloud.githubusercontent.com/assets/17736688/16221468/940dae9c-3758-11e6-8524-14d4b9522c69.PNG)
![cache-directory-not-writable-for-resizing-thumbs-not-created](https://cloud.githubusercontent.com/assets/17736688/16221471/9986ca7a-3758-11e6-9044-95324b6c9722.PNG)

 'cache' directory is not writeable for resizing thumbs
we have to manually add a cache directory to the plugin folder ?
Server Thumb for ClipBucket

Add function in clipbucket to get server thumb :)
Active Author : Mohammad Shoaib | Ver : 2 
after there is no issue...

 but misleading cause it doesn't specify what cache directory
can you just add it or when we activate cache folder it is created ??

**Comment by move-IT-online** [comment]
http://discourse.clipbucket.com/t/errors-found-in-cb-2-8-1-rc2/1995
Errors found in CB 2.8.1 RC2
2. Admin Area - Plugins
- when activating Plugin "Server Thumb for ClipBucket" I get an Error like "Missing Cache Folder". I have to manually create /plugins/cb_server_thumb/cache folder and CHMOD this folder and everything in it to 777 (read/write/execute).

**Comment by spirogg** [comment]
ok after clicking refresh a few times i got cache folder created by script sorry...
![cache-folder](https://cloud.githubusercontent.com/assets/17736688/16222537/3dcb6bc2-375e-11e6-8afa-932dc2002367.PNG)

**Comment by spirogg** [comment]
![cache-folder-inside](https://cloud.githubusercontent.com/assets/17736688/16222629/bce535d2-375e-11e6-91fc-a7ba14d75461.PNG)
i just logged out and then logged back in and seems it created but CHMOD id not 777
