### ISSUE TITLE
 Manage Videos >> Videos Details from drop down has 111 after title ?? see photo

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#180]
hi when i go to Manage videos from dropdown top right (logged in as admin) i get 3 111 at end of title of the videos ??

![manage-videos-from-drop-down-loggin-as-admin](https://cloud.githubusercontent.com/assets/17736688/16221910/ed4fc376-375a-11e6-869b-1f89ad8c1786.PNG)

**Comment by move-IT-online** [comment]
Confirmed! Same Issue here.
Dubious "111" not found in the Source Code.
