### ISSUE TITLE
some pages: video title is missing some ending letters ?? see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#181]
some pages: video title is missing some ending letters ?? see photos for better explanation
![missing-the -number-1-and-missing-sd-in-featured-videos-in-title](https://cloud.githubusercontent.com/assets/17736688/16222239/c2b1a2fe-375c-11e6-93da-44f86c6c51bb.PNG)
![missing-the -number-1-and-missing-sd-in-featured-videos-in-titles](https://cloud.githubusercontent.com/assets/17736688/16222246/c855b344-375c-11e6-93a7-09cd1a751be2.PNG)
![missing-the -number-1-and-missing-sd-in-featured-videos-in-titles-](https://cloud.githubusercontent.com/assets/17736688/16222251/cd503450-375c-11e6-9377-37ed2861e512.PNG)
![missing-the -number-1-and-missing-sd-in-featured-videos-in-titles1](https://cloud.githubusercontent.com/assets/17736688/16222262/d3310dc2-375c-11e6-97ed-161a7bd282a0.PNG)
![missing-the -number-1-and-missing-sd-in-featured-videos-in-titles123](https://cloud.githubusercontent.com/assets/17736688/16222270/dac249f2-375c-11e6-8834-9bbb81772f60.PNG)

**Comment by sakydev** [comment]
That's because title is being truncated there due to less space. It  is done on purpose so design doesn't break. Not an issue. Closing now
