### ISSUE TITLE
@cb please read my comments Mass Upload  -  283141e

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#182]
Mass Upload  - see link in other comment and read comments please. Not too good mass uploader. Missing some valuable things to really operate smoothly. Please read.

**Comment by spirogg** [comment]
https://github.com/arslancb/clipbucket/commit/283141e0cbb0c7757871086da26606f4980dee57
@sikanderzel @saqirzzq 
please follow this link and read my comments

**Comment by sikanderzel** [comment]
Resolved ..
