### ISSUE TITLE
If create new theme logo won't upload to new theme ??

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#184]
Hi what changes need to be made if we use 2 or 3 different themes. Example cb_28 and cb_28red and cb_28dark 

What needs to change to allow upload to each theme depending on what theme is active. ??

**Comment by spirogg** [comment]
<?php
require_once '../includes/admin_config.php';
$userquery->admin_login_check();
$pages->page_redir();
/\* Assigning page and subpage */
if(!defined('MAIN_PAGE')){
define('MAIN_PAGE', 'Stats And Configurations');
}
if(!defined('SUB_PAGE')){
define('SUB_PAGE', 'Update Logo');
}
$source = BASEURL.'/styles/cb_28/theme/images/logo.png';

// Upload and Rename File

if (isset($_POST['submit'])) {
// function used to upload site logo.
upload_logo() ;
}
assign('source',$source);
subtitle("Update Logo");
template_files('upload_logo.html');
display_it();
?>

Is this the code.

**Comment by spirogg** [comment]
Is there a way to do this by making code 
Example. 

$source = BASEURL.'/styles/{theme}/theme/images/logo.png';

**Comment by spirogg** [comment]
Is there a way to code that file so if I create my own theme I don't have to make changes to add a logo to that theme ? The logo would just upload to whatever theme we have added ?? Should be an easier way to do this instead of changing Baseurl  every time.  Please.

**Comment by sakydev** [comment]
Use below code and your logo uploading should work with any theme.

$template_dir = $Cbucket->configs['template_dir'];

$source = BASEURL.'/styles/'.$template_dir.'/theme/images/logo.png';
