### ISSUE TITLE
Remote upload not work?

### ISSUE THREAD

**Issue by zebmak** [arslancb/clipbucket#187]
Hello

I installed new version of clipbucket, but when i upload from youtube then i can't change the categories. the videos uploads on same categori "Uncategorized" i changed categiry but videos upload aumatics to this category "Uncategorized". 

You can go and  try to upload video from youtube.
www.afgtube.ml

username:test
pass:test

**Comment by sakydev** [comment]
Issue has been resolved in latest dev version.
