### ISSUE TITLE
when uploading videos featured shows when it is not even processed yet ? 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#188]
when uploading a video from mass uploader or just uploading a video - before it converts.....
it shows active and featured--- check marked --- but it is not featured..  issue 1

then when i click on drop down to feature the video it says it does, but when I select drop down again it still says 
Make Featured 
instead of 
Make Unfeatured   issue 2

![when uploading a video from mass uploader or just uploading before it converts but it still shows active and featured](https://cloud.githubusercontent.com/assets/17736688/16368140/6471a052-3bf0-11e6-8277-f2b31e3ace8a.PNG)

issue 2 

after making video featured it should say in drop down (Make unfeatured) 

![after making video feature should say in drop down unfeature video](https://cloud.githubusercontent.com/assets/17736688/16368238/8680fe94-3bf1-11e6-9c49-08c25efddca6.PNG)

should say (Make Unfeatured) like this section below
![make unfeatured](https://cloud.githubusercontent.com/assets/17736688/16368218/47e55b94-3bf1-11e6-869b-13728df195f3.PNG)

**Comment by sikanderzel** [comment]
It's working now
