### ISSUE TITLE
admin >> tool box >> Action Log page - then other drop downs do not work not clickable see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#189]
when you click on action-logs-you cannot close or open other drop downs ( see photo where i circled the drop down sections, you cannot select those they are not working, only if you click on another link like (view online users) as an example then they work again .. 

![when you click on action-logs-you cannot close or open other drop downs unless you click on another link like view online users example](https://cloud.githubusercontent.com/assets/17736688/16368332/ef232f5c-3bf2-11e6-8677-489d4dcdcd09.PNG)

**Comment by move-IT-online** [comment]
I have the same effect, but strangely not always.

**Comment by sikanderzel** [comment]
resolved...
