### ISSUE TITLE
toolbox >> reindexer - does not refresh (redirect) when trying to reindex see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#190]
toolbox >> reindixer - does not refresh (redirect) when trying to reindex see photos
![reindex clipbucket doesnt refresh see photo](https://cloud.githubusercontent.com/assets/17736688/16368472/3ec389f2-3bf4-11e6-8053-b32fd0006ac9.PNG)
![toolbox-reindexer-not-refreshing](https://cloud.githubusercontent.com/assets/17736688/16368476/4fbdd5fa-3bf4-11e6-8dfc-6fdeff7cda88.PNG)

**Comment by spirogg** [comment]
Any way to fix the indexer. Refresh. (redirect) does not work. It use to work in version 2.6 not sure after that. It should be easy fix for you @saqirzzq or @sikanderzel 
Can you please have a look at this one. 

Thanks.

**Comment by spirogg** [comment]
@saqirzzb

**Comment by sikanderzel** [comment]
resolved ..
