### ISSUE TITLE
user contact manager > images not aligned needs some rework or css adjustment see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#193]
just updated from github Master a couple hours ago 
also these two links are the same page nothing different about them, seems it should be different ??

Manage Contacts >>>  /manage_contacts.php?mode=manage
Add Contact List  >>>   /manage_contacts.php?mode=new_group
its the same layout as photo below can can you fix that also, add contact list ?? we should be able to add contacts to our list of contacts ?? not following what the difference should be but I am sure you guys know what it is and how to fix it :)

user contact manager > Layout page/ images not aligned needs some rework or css adjustment see photos..

![contacts-manager-needs-some-work-css](https://cloud.githubusercontent.com/assets/17736688/16370192/34d482ac-3c03-11e6-8a62-2f54247dec3a.PNG)

**Comment by spirogg** [comment]
PS the misalign is only when there is a pending friend request. As soon as you accept. It is aligned. Just FYI.

**Comment by sikanderzel** [comment]
Fixed ..
