### ISSUE TITLE
Terms_of_Service word is like this from install from github master today ?? 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#195]
![terms_of_service_wording](https://cloud.githubusercontent.com/assets/17736688/16370629/e699c166-3c06-11e6-8873-f32c62e6fe27.PNG)
Terms_of_Service in footer word is like this from install from github master today ?? 
if you go to manage pages you will see this also ?

**Comment by sikanderzel** [comment]
resolved..
