### ISSUE TITLE
Editor Pick video absent?

### ISSUE THREAD

**Issue by edwios** [arslancb/clipbucket#197]
On the latest V2.8.1 RC2 release, video added to Editor's Pick do not show in /admin_area/plugin.php?folder=editors_pick/admin&file=editor_pick.php
The page looks ok however with no video at all.

DB has records, however:

MariaDB [clipbucketdb]> select \* from cb_editors_picks;
+---------+---------+------+---------------------+
| pick_id | videoid | sort | date_added          |
+---------+---------+------+---------------------+
|       1 |     977 |    1 | 2016-06-28 03:26:29 |
|       2 |     974 |    2 | 2016-06-28 03:26:53 |
|       3 |     970 |    3 | 2016-06-28 03:27:12 |
+---------+---------+------+---------------------+
3 rows in set (0.00 sec)

I have tried to un-install then install the plug-in but it does not solve the problem.

**Comment by spirogg** [comment]
![editor](https://cloud.githubusercontent.com/assets/17736688/16404258/eeec697e-3cc2-11e6-8c06-15a65edc8e61.PNG)
![editor-pick](https://cloud.githubusercontent.com/assets/17736688/16404259/f213aa4a-3cc2-11e6-96a0-2f0252718f74.PNG)
Seems to work, i am using Master from Github with fixes already up to date today. so you can update from Master CB or wait till RC3 or what ever they name the next update. it does work editors pick as shown in photos

**Comment by edwios** [comment]
Interesting, I have cloned the master from git and still, the editor's pick has nothing... I am starting to wonder if I did it right by going into admin-->Video Manager-->Actions then Add to Editor's Pick...

**Comment by edwios** [comment]
Ah! Finally found the reason why. There is this:
... AND ".tbl('video.broadcast')." = 'public' ...
in the editors_picks.php, so, the video has to be PUBLIC in order to appear in the Editor's Picks.

Now, it would be good to forbid the video to become an editor's picks if it is not public, and remove the editor's pick property when the video becomes non-public.

//Ed
