### ISSUE TITLE
Guests should not be able see thumbnails of logged-on only videos

### ISSUE THREAD

**Issue by edwios** [arslancb/clipbucket#198]
If a video is set to watch only by logged on users, Guests or whoever has not logged on should not even see the thumbnails of the video.

Please suggest a way to not read these video from DB.

Also, the UX is not good if these video got clicked on and only result in a Blank page.

Version installed: V2.8.1 RC2

Thank you!

**Comment by spirogg** [comment]
I agree with @edwios needs fix

**Comment by spirogg** [comment]
@sikanderzel 
Also, the UX is not good if these video got clicked on and only result in a Blank page.
can you make this popup as  please signup or Login to view videos.

Thanks @sikanderzel
