### ISSUE TITLE
Please correct can't view videos error   unknown function "get_timeComments"  I can't view videos fresh master github install 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#200]
Syntax error in template "/home/tune/test/player/CB_video_js/cb_video_js.html" on line 13 "{$timecomments = json_encode(get_timeComments($vdata.videoid))}" unknown function "get_timeComments"
On Line Number 13
In file /home/tune/test/includes/smartyv3/sysplugins/smarty_internal_templatecompilerbase.php

**Comment by spirogg** [comment]
@fahad-cb @saqirzzq @sikanderzel

**Comment by sikanderzel** [comment]
resolved
