### ISSUE TITLE
When using mobile to reactive or activate account pop-ups blocking input areas

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#204]
He if I want to reactivate or activate my account. I can't see well enough to do so because there are pop-ups in the way. See photos using mobile phone chrome browser. (Nexus 6p)
![screenshot_20160702-233706](https://cloud.githubusercontent.com/assets/17736688/16543768/6111b18c-40ae-11e6-999e-184a2ee6dec4.png)

**Comment by spirogg** [comment]
This is your site. Clipbucket.com

please hard code the popups next to each button 
1 is activation button 

![activation-hard code next to activate button for better mobile use](https://cloud.githubusercontent.com/assets/17736688/16543978/5c076916-40b8-11e6-87c5-85bcfff32516.PNG)

and the other is the 
request button see photos

![request-activation-code-hard code next to request button for better mobile use](https://cloud.githubusercontent.com/assets/17736688/16543981/69c70b9c-40b8-11e6-96f4-4960afa3b606.PNG)

**Comment by spirogg** [comment]
please do this for better mobile use. so its not a popup in the way when users are using their mobile phones :+1: 

please thanks so much guys

**Comment by spirogg** [comment]
@saqirzzq @sikanderzel @jamilrehman 

any update here ?

**Comment by sakydev** [comment]
We will definitely look into it.

**Comment by sakydev** [comment]
Killed!
