### ISSUE TITLE
Mobile upload photo chrome browser can't see with pop-ups in the way. 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#205]
![screenshot_20160702-235810](https://cloud.githubusercontent.com/assets/17736688/16543839/af7f5514-40b2-11e6-9567-150bb6d08872.png)
![screenshot_20160702-235910](https://cloud.githubusercontent.com/assets/17736688/16543841/e349a62e-40b2-11e6-8442-20e2ec6abf3c.png)

See photos. Self explanatory.

**Comment by spirogg** [comment]
![hard code below for better mobile useability](https://cloud.githubusercontent.com/assets/17736688/16543947/a594041a-40b6-11e6-9cd2-4017bac6a828.PNG)
Same issue when uploading videos - but it's for YouTube videos. Where you cannot add a URL cause the pop-up writing if blocking it. Only way to manage is landscape on my phone but even then it's still blocking. I suggest remove pop-ups or hardcode into those areas. Photo upload and video upload areas. Also on activation area. Hardcode wording. Below the input fields  
ALSO VIDEO HARD CODE BELOW 
![hard code below for better mobile use](https://cloud.githubusercontent.com/assets/17736688/16543951/c437a8a4-40b6-11e6-8de4-7b36139f810e.PNG)

Thanks Spiro.

**Comment by spirogg** [comment]
@saqirzzq @sikanderzel @jamilrehman 

any update here ?

**Comment by sakydev** [comment]
Killed!
