### ISSUE TITLE
when clicking collection and then videos collection - the report is ON instead of OFF for default see photo

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#207]
when clicking on collection and then choosing videos collection - the Report video option is ON instead of OFF for the default.... please change it to OFF as default..
 see photo
![collections selecting videos makes the report on instead of off as default setting](https://cloud.githubusercontent.com/assets/17736688/16552387/573d3946-4186-11e6-9856-6a3cdc8ce54c.PNG)

![collections selecting videos please set this to off as default should look like this now](https://cloud.githubusercontent.com/assets/17736688/16552396/64f88aa4-4186-11e6-9a6f-d42d131819cf.PNG)

**Comment by sikanderzel** [comment]
Resolved..
