### ISSUE TITLE
playlist added from user section, returns this link https://mysite.tld&play_list=13/  not playable

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#208]
playlist added from user section returns this link https://mysite.tld&play_list=13/  not playable

but when create playlist under video player >> add to >> create new playlist the link works correctly
https://mysite.tld/vasilis-karras-gia-des-poia-milaei_v1135&play_list=12 except that the link should have ? instead of & like below or playlist doesn't show up 

https://mysite.tld/vasilis-karras-gia-des-poia-milaei_v1135?play_list=12

can you please fix this from user side and correct the link ? vs &

your site too clipbucket.com demo same thing ? vs & when you click a playlist

my account manage playlist add playlist 
if it is two words not connected (Greek Music) will give bad url - link
 if it is one word (greekmusic) or connected (Greek-Music) it works
unlike view video page where it can be multiple words not connected and will still work

so if a user tries from his or her account to add a playlist with more than one word seperated it will not work.

thanks

spiro

**Comment by spirogg** [comment]
http://demo.clipbucket.com/test-driving-james-bonds-incredible-custom-made-aston_v1107&play_list=10
try this playlist wont show playlist needs ? instead of & 
should be http://demo.clipbucket.com/test-driving-james-bonds-incredible-custom-made-aston_v1107?play_list=10

**Comment by sikanderzel** [comment]
Resolved..
