### ISSUE TITLE
Problem when users create collection. 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#211]
I see that admin need to manually set a users collection preview image.

Perhaps it would be better if the preview image is automatically populated by the most recent image within the collection.

With the current system, admin needs to login daily and manually upload images to be used for preview image. If hundreds of users create new collection, then updating them would take hours.

Any way we can automatically set thumbnails ?

**Comment by sikanderzel** [comment]
Latest image is now being used for the collection preview as far as photo collection is concern..
