### ISSUE TITLE
CB2.8.1 Playlist load more

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#213]
When you click on a playlist that has more than 10 videos, the load more button is not working.

Also, (http://demo.clipbucket.com) you have to click on the first playlist video to open the playlist. Clicking on the **playlist name** just takes you to the first playlist video.

**Comment by spirogg** [comment]
![load-more-not-working](https://cloud.githubusercontent.com/assets/17736688/16829587/f280997c-495e-11e6-8ec2-cc976dc660fb.PNG)

**Comment by pcmcis** [comment]
Hi, spirogg,

By default it shows the first 10 videos. If you have a playlist with more than 10 videos and you hit "load more" to see the rest of them, nothing happens.
