### ISSUE TITLE
Clipbucket install does not work on PHP 7

### ISSUE THREAD

**Issue by xaoseric** [arslancb/clipbucket#219]
The install of clipbucket does not work on php 7, keeps showing a spinning circle. after you press the check database connection button.

**Comment by sakydev** [comment]
Hello there @xaoseric 

Unfortunately, ClipBucket is currently not supported with PHP7. We actively working on making this a better product and making it compatible with PHP7 is definitely in our plans.

Thank you for using ClipBucket. Closing this for now.
