### ISSUE TITLE
user link in user photo not correct

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#22]
hi, when viewing a photo and clicking on the avatar -image that link of the user avatar takes me to mydomain.tld/user not the actual user. but when clicking below avatar on the username it works.

**Comment by spirogg** [comment]
this is gitdev version of clipbucket sorry for double post just maling sure you know what version of CB im reporting unless you know this already :)

**Comment by sakydev** [comment]
Done and committed.
