### ISSUE TITLE
 Please detect and fix this vulnerability asap please. 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#222]
url:http://www.xxx.com/ajax.php
parameter: rating=5&type=user&mode=rating&id=4 OR (8281=8282)
Request method: POST

Please detect and fix this vulnerability as soon as possible. thank! Hard to you!

**Comment by spirogg** [comment]
This was posted here. 
http://discourse.clipbucket.com/t/ajax-php-sql-injection-vulnerabilities-seriously-seriously-serious/2174

**Comment by sakydev** [comment]
It was fixed on urgent basis moments after it was reported.
