### ISSUE TITLE
cb_install SQL scripts contain errors

### ISSUE THREAD

**Issue by mtlynch** [arslancb/clipbucket#223]
There seem to be several simple errors in the SQL install scripts. They should all be very easy to fix:
#### `cb_install/sql/structure.sql`
- [609](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L609): `CREATE TABLE` should be `CREATE TABLE IF NOT EXISTS`
- [1053-1054](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1053-L1054): ``{tbl_prefix}_video`` - extra underscore after `{tbl_prefix}`
- [1107](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1107): This line is formatted incorrectly (`{table_prefix}` appears in the wrong place) and can be deleted because the statement on [1197](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1173) has the same effect
- [1141](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1141): This line is not necessary because the `file_directory` column already appears in the original `CREATE TABLE` statement on [490](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L490-L522)
- [1148](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1148): Line is not necessary because `video_version` column already appears in the original `CREATE TABLE` statement on [898](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L898-L960)
- [1149](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1148): Line is not necessary because `extras` column already appears in the original `CREATE TABLE` statement on [898](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L898-L960)
- [1191](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1191): Line is not necessary because `file_directory` column was added on [1142](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1142) 
- [1201](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1201): Line is not necessary because `parent_id` appears in original `CREATE TABLE` query on [108](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L108-L118)
#### `cb_install/sql/configs.sql`
- [224](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/configs.sql#L224): Fails because the primary key `224` was already used on [158](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/configs.sql#L158)
#### `cb_install/sql/user_levels.sql`
- [83-88](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/user_levels.sql#L83-L88): Fails because these lines already appear in [`structure.sql`:1116-1116](https://github.com/arslancb/clipbucket/blob/f3e4596914d6b02465e0f2b51a7e7f3285710cee/upload/cb_install/sql/structure.sql#L1112-L1116)

**Comment by RealDekkia** [comment]
Just FYI, this Issue has been mentionend in a blog-post: https://mtlynch.io/digitizing-2/#clipbucket-the-open-source-youtube-clone-you-cant-really-install
