### ISSUE TITLE
CB2.8.1 editors picks problem IE11

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#224]
Please see the attached video
This happens only on IE

https://youtu.be/HuE7DB25UBo

**Comment by spirogg** [comment]
I confirm same issue. Just noticed it.

**Comment by spirogg** [comment]
Also windows 10 edge browser.

**Comment by sakydev** [comment]
We are looking into this issue. If confirmed, it will be fixed in next release for sure.
