### ISSUE TITLE
CB2.8.1 Featured Videos, Load More problem

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#228]
Hi,

Load More is working fine if **Index page Featured** in website configuration is set to 2.
Changing to 4 or more, the last time you hit Load More, you get 2 empty spaces.
I have 6 featured videos. 4 are displayed by default. Clicking on Load More I see the rest of my videos.
But the Load More button is still there. So clicking the Load More once more you get the empty spaces.

![load more2](https://cloud.githubusercontent.com/assets/19185161/17434816/52850214-5b15-11e6-8a6a-82eacabdb013.PNG)

![load more1](https://cloud.githubusercontent.com/assets/19185161/17434825/5a3f8a2e-5b15-11e6-9057-2782206774ae.PNG)
then

![load more](https://cloud.githubusercontent.com/assets/19185161/17434829/5d0de05c-5b15-11e6-94c6-93401e5904d7.PNG)

**Comment by sakydev** [comment]
We will definitely look into this issue.
