### ISSUE TITLE
do not delete mass upload function not working

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#229]
server centos 6.8 php 5.4 using php fpm on directadmin server 
have tested with apache only, apache with nginx proxy, nginx only
 build 4770 (and I also pulled from here last night to verify) is deleting items in mass upload no matter what the option is set too.
tested on 2 different dedicated servers over 5 different domains

**Comment by dmaclip** [comment]
just applied new file and still an issue
tested on main site and on test site that was fresh install of files downloaded from here 20 minutes ago

**Comment by sakydev** [comment]
Are you sure you have the latest version? Can you tell me if your changes are saving for "Mass Upload Don't Delete" option?

**Comment by dmaclip** [comment]
yes latest version, downloaded master-zip (notes showed file was fixed) and did fresh install.
no  the changes do NOT save when swapped and click save
