### ISSUE TITLE
CB2.8.1stable, Action Logs always show server IP

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#230]
Admin area --> Tool Box --> Action Logs

After updating from CB2.8.1RC1 to CB2.8.1Stable, IP is always Server IP.
Older entries display the client IP.

**Comment by move-IT-online** [comment]
confirmed

**Comment by sakydev** [comment]
Will be fixed in upcoming versions.

**Comment by MacWarrior** [comment]
get_local_ipv4() function can only works on linux based systems, and I don't get why it gets server internal IP instead of client IP : $_SERVER['REMOTE_ADDR'] must be fine for this case ? if not, why ?
