### ISSUE TITLE
mass upload display issue

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#232]
when clicking mass upload top of video list shows all categories for system even though they have no direct effect on the upload.
this is just small sample but the list can line wrap if there are lot of categories.
![capture](https://cloud.githubusercontent.com/assets/20878066/17490939/59728bfe-5d73-11e6-839b-47e2356403b2.PNG)

**Comment by sakydev** [comment]
Valid issue. Will be fixed.

**Comment by dmaclip** [comment]
thank you sir

**Comment by dmaclip** [comment]
was this corrected? used files from master-zip last night and same issue

**Comment by MacWarrior** [comment]
Hi, some changes has been merged about this page, here's the new presentation :
![screenshot 1](https://cloud.githubusercontent.com/assets/200590/19948399/aefda406-a14c-11e6-9adb-4f00b2d167d3.jpg)

Now, when you check or uncheck a category, it is also checked/unchecked on each video

This may close this issue, right ?

**Comment by sakydev** [comment]
Categories selection works now. Closing this.
