### ISSUE TITLE
Video cannot be added to playlist only if rating is not allowed

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#233]
Do Not Allow Comments
Do Not Allow Comments Voting
No, Do Not Allow Rating on this video
No, People cannot play this video on other websites

**Comment by fahad-cb** [comment]
not a bug

**Comment by fahad-cb** [comment]
@aliawancb  please verify again

**Comment by aliawancb** [comment]
@fahad-cb  try adding this video to a Playlist https://demo.clipbucket.com/test_v2202

**Comment by aliawancb** [comment]
Still Valid

**Comment by Awais-cb** [comment]
Fixed
