### ISSUE TITLE
Max video Processes at once does not work

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#234]
this is getting old, this bug has been around for years.
heres Max video Processes at once set to 1 in admin panel
![capture](https://cloud.githubusercontent.com/assets/20878066/17530860/5e7339da-5e47-11e6-9704-979710899bdf.PNG)
as you can see theres more than 1

**Comment by sakydev** [comment]
Max processes means videos being converted at one time and not the processes running to convert 1 video. ClipBucket generates 5 resolutions for an HD video and those process can be visible.

**Comment by dmaclip** [comment]
will retest again but don't think thats it. even with sd/hd only set (and sd only videos) and 5 videos set to process see 5 processes in past and all 5 showed being converted
will kno wmore later tonight will set a few videos to sd only and see

**Comment by dmaclip** [comment]
ok with max set to 2 and 4 vids queued as sd/hd I now only see 4 ffmpeg processes (2 processes per video) which is a lot different than the past.
prior versions would start every video no matter the setting.
at one point, with sd/hd only (as the all res bug was still in play) 10 sd only vids that would not generate an hd verson (with max process set to one) did all 10 at once.

however is there a way to schedule the ffmpg process for each resolution to reduce loads? for example progressively step up through the resolutions and do one at a time?
its not huge deal for dedicated server users but vps users pretty much need to run a cpulimit script when ffmpeg running just to allow site to work.

perhaps a better description in admin panel would help, instead of max processes label it max number of videos to process and have a note saying each res will generate an ffmpeg process and this is normal and expected.

**Comment by sakydev** [comment]
Thank you @dmaclip for all your effort. I'm glad things worked up fine for you.

As for feature you suggested, we will look into it but can't promise anything due to our hectic schedule. 

As for label, I'd agree with you that it is indeed confusing. Will be changed as soon as possible.

**Comment by sakydev** [comment]
Alright. Quick update. Just changed label. It won't be bothering anyone else now :smile: https://github.com/arslancb/clipbucket/commit/ebf5e1c4d209ee3e16738307b11a05fbe964089b
