### ISSUE TITLE
 ' character in description causes problem in saving the changes.

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#235]
I tried to change the values directly from the database and it worked.
After playing around, I discovered that the problem was the video Description!!
Long story short, the problem is the ' character!! 
If you enter in the description the character ' you will get ',category= 
after hitting update video details.

I also tried that on my live site and it works!

**Comment by sakydev** [comment]
We will definitely look into this issue.

**Comment by dmaclip** [comment]
thanks I presently have to directly edit database to make descriptions work
have not tested extensively but also seems if there is a line break between first line and rest of description it may fail to save too

example:
video name
rest of description

that enter after video name seems to me to cause issues but like I said I need to test that more

**Comment by dmaclip** [comment]
possibly related, when uploading and entering description items if you hit enter to do line break when done the code <br> is displayed. editing it out from admin panel corrects it

**Comment by sakydev** [comment]
Fixed now.

Edit video:
http://prnt.sc/cj122i

Watch video:
http://prnt.sc/cj12a3
