### ISSUE TITLE
When password protect a video and share the link there is no field to type in the password 

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#236]
when I password protect a video and want to share the link, there is no way to type in the password, please take a look at the attachment. I think there need to be a box were the one who receive the link type in the password.
<img width="1280" alt="skarmavbild 2016-08-10 kl 09 58 17" src="https://cloud.githubusercontent.com/assets/15014349/17546654/b1416294-5efc-11e6-9f27-433ede71f189.png">

**Comment by sakydev** [comment]
Issue is valid. Will be fixed in coming versions.
