### ISSUE TITLE
please make this php 5.6 compatible

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#238]
5.4 will be eol soon, 5.5 and 5.6 bring a lot of opcode cache enahncements to the table.

**Comment by dmaclip** [comment]
actually 5.4 IS eol now as of 9-2015.
you cannot keep forcing people to use 5.4

**Comment by sakydev** [comment]
Most of ClipBucket features work with 5.5 and 5.6 and all of new development is being done with compatibility to PHP 5.6. Making PHP 5.6 as officially recommended PHP version will cause thousands of clients to update their PHP versions.

However, we cannot deny the importance of doing so. It will be done as soon as we can.

Thank you for pointing it out

**Comment by dmaclip** [comment]
those thousands probably running an EOL unpatched unsupported php version SPECIFICALLY due to clipbucket I bet and would most likely be happy to update off the unsecure php version.

**Comment by chrisbbreuer** [comment]
I agree, that's something I would love to see soon. Those clients should update their system for sure if they aren't keeping it due to clipbucket. Anyways, I will try to join and start collaborating with you from now on as well!
