### ISSUE TITLE
mass upload function grabs ALL videos not just chosen ones

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#239]
earlier versions did nothing to videos you did not click on and enter catagory/etc
present version will convert all videos in mass upload folder  (also see this report  https://github.com/arslancb/clipbucket/issues/229 ) and uses default category for ones you did not click and enter info for.
so if you have 10 files in mass folder want to work one of them, no matter what all 10 get worked.

**Comment by sakydev** [comment]
Issue is valid. Labeling....

**Comment by MacWarrior** [comment]
Trick to select file to upload : leave title (or description/category/tags) blank for not wanted files.
It will display a warning but will import only fully informed files

**Comment by MacWarrior** [comment]
Hi, a new feature has been added to the mass upload page : 
![screenshot 2](https://cloud.githubusercontent.com/assets/200590/19948521/3eb659ee-a14d-11e6-8cd2-2f69702b6e22.jpg)

Now, there is a checkbox for each file and only checked files will be imported, and you can check the "Select/Deselect" checkbox to check/uncheck all checkboxes

This may close this issue

**Comment by dmaclip** [comment]
seems that should suffice if I get chance will test tomorrow and report my findings

also I suck using github can you provide link where I can get files needed for this?

**Comment by MacWarrior** [comment]
Hi, I've made some mistakes on the current dev version, please check my last pull request to get it correctly work

**Comment by sakydev** [comment]
Issue resolved. Only selected videos are uploaded now.
