### ISSUE TITLE
upgrading from 2.6 to 2.8 error

### ISSUE THREAD

**Issue by Blisk** [arslancb/clipbucket#241]
When I overwrite my 2.6 files with 2.8 files and locate site on web browser I get this error
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 523800 bytes) in /var/www/video/includes/functions_db.php on line 236

**Comment by sakydev** [comment]
It has nothing to do with ClipBucket but has everything to do with your server's RAM. You will need to increase ram size or setup regular cache files cleaning to avoid this.

It is highly recommended to follow instructions on this page http://clipbucket.com/cb-install-requirements/
