### ISSUE TITLE
system creating empty original files directories

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#243]
there is no option that I can find to allow  saving original like older versions but system is still creating the directories
![capture](https://cloud.githubusercontent.com/assets/20878066/18036540/0b0baa22-6d3b-11e6-9239-c469df7671bd.PNG)

**Comment by sakydev** [comment]
Are you using any additional plugins with ClipBucket?

List them down if any (leave out free ones)

**Comment by dmaclip** [comment]
when posted there were no plugins installed.
was test install to verify what I saw against main site.

**Comment by Awais-cb** [comment]
system create those directories according to dates just to track the media files easily.
