### ISSUE TITLE
Disabled submit button

### ISSUE THREAD

**Issue by martinvivek** [arslancb/clipbucket#248]
The Submit button is disabled even though the video uploaded progress is 100 %
If we enabled the Fileinfo.dll in php extension the submit button enables but still we cannot able to upload it.

**Comment by sakydev** [comment]
Kindly provide more details like screenshot, url to website etc.

**Comment by martinvivek** [comment]
I am running in a local network.
Using Windows 2008 Server
Mysql database
Installed All modules. all are working fine except FFMPEG says not detected but running by command line works fine.

Referenced issue 249 is different in that i cannot upload anything in the website, add photos, create users, add collections folder everything shows successfully created but in database nothing is there

**Comment by martinvivek** [comment]
php version tried using 5.3, 5.4, 5.6, 7 Nothing helped

**Comment by sakydev** [comment]
Windows servers are not recommended with ClipBucket because we haven't officially started support for Windows. You are advised to use Linux until we do so. Closing this.

**Comment by goldenkomane** [comment]
I have the same issue, please help
