### ISSUE TITLE
editing admin or user section date of birth problem

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#25]
when Editing > admin
right side under
User Activity
Date of birth   0000-00-00 YYYY-MM-DD  <<<(how to fix this)
Joined - IP     111.111.111.111
Last-Login IP   2016-03-31 16:20:57

**Comment by spirogg** [comment]
this is gitdev version of clipbucket

**Comment by spirogg** [comment]
this is also same error for user in signup form. can we deselct this as part of signup form

**Comment by MacWarrior** [comment]
Hi, a fix has been merged, this issue may be closed 😄
