### ISSUE TITLE
when trying to add comment error

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#26]
Fatal error: Can't use function return value in write context in /home/mysie/gitdev/cache/25a251b2ef449de7325445ce3ae6d7d734197d97.file.comment.html.php on line 87

**Comment by spirogg** [comment]
this is gitdev version of clipbucket

**Comment by sakydev** [comment]
I can comment just fine on photos as well as videos. Kindly be a little more descriptive about where you are encountering this issue. Before retrying, kindly clear your Cache directory.

**Comment by spirogg** [comment]
i did clear cache folder and still getting this error 2 hours ago I update gitdev and get this error with php5.4
Fatal error: Can't use function return value in write context in /home/tunegr/gitdev/cache/25a251b2ef449de7325445ce3ae6d7d734197d97.file.comment.html.php on line 87

i had installed 5.5.3 php no more errors in comments but big POPUP say admin warning, script needs 5.4.x php so i change back and i get this error again ??

**Comment by spirogg** [comment]
what version php we could use 5.4 or can we also use 5.5.3 ? please let us know for latest stable build and also 2,8 git dev svn

**Comment by spirogg** [comment]
i dont know why but this error occur still after update svn 1/2 hour ago
php5.5.3 there were no errors, now back to 5.4.4 and errors ??

**Comment by sakydev** [comment]
Killed by @fahad-cb
