### ISSUE TITLE
Pagination issue when large numbers of pages..

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#263]
in my site there 800+ page when i goto page 5 or 10 then pagination is going to multiple rows.. check bellow screen shot. on small devices like mobile it going to 3~4 lines..

![untitled-5](https://cloud.githubusercontent.com/assets/4317570/19557370/cfe3c074-96de-11e6-987c-a6f4458a58f5.jpg)

**Comment by aliawancb** [comment]
@fahad-cb Kindly look into it.
