### ISSUE TITLE
CB2.8.1 Recent Videos, Load More

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#265]
Hi,

I tried this with the latest Github download.

I have 10 videos uploaded.
Using **Index Page Recent** 3, doesn't list my 10th video.
If **Index Page Recent** is more than 4, the last time your hit the **Load More** button you get empty video windows.
Please have a look at the attached video.
https://youtu.be/70qrzZ611wE

**Comment by aliawancb** [comment]
@fahad-cb Review and label. Load More button doesn't go all the way, disapears after loading some pages.

**Comment by aliawancb** [comment]
Not critical
