### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by mahdaen** [arslancb/clipbucket#270]
When i enable the `Verification` option on user signup, users never get the verification link. I've tried using `SMTP` or `PHPMail()`. Trying to send mass mail success, but when trying to re-send verification email it's fail. The error says `At least one email recipient required.`, but i use email to signup.

**Comment by dmaclip** [comment]
not using sparkpost or mandrill/mailchimp are you?
actually probably any mass mailer would be affected

https://github.com/arslancb/clipbucket/issues/237

**Comment by aliawancb** [comment]
Try setting SMTP properly, http://discourse.clipbucket.com/t/email-configuration-smtp-php-mail/
