### ISSUE TITLE
Remote Upload Grab from YouTube feature issue in Apple Mac with Chrome

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#272]
When I test the 'Remote Upload' feature in Apple Mac Mozilla Firefox, it works as
planned. When I also test the remote upload in PC Chrome it works as expected too.

So the location of this problem is in the Chrome Browser for Apple Mac from
my investigations.

It would be good if this bug could be fixed given 75% of the world uses Chrome, and given most video producers in Australia use Mac.

**Comment by sakydev** [comment]
We tested issue on two different machines and things worked just fine. Closing it.
