### ISSUE TITLE
Video rating is disabled on photo rating ??? 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#28]
when viewing a photo and trying to click on the thumbs up it says >> Video rating is disabled

i don't disabled photo ratings ? or video ratings ?
is this a bug ?

this is gitdev version of clipbucket

**Comment by sakydev** [comment]
Kindly elaborate a little more. Tell me how I can recreate this issue because rating photos seems to be working ok at my end

**Comment by spirogg** [comment]
2 hours ago i update git now no longer issue. what permission should cache folder be 755 and all under >folders 755 files will write 777 or 644 from script if needed or should i change to 664 ?
have issue again you say to clear cache ? is gitingnore  to delete and clear cache or under user commnets delete all files ?

**Comment by spirogg** [comment]
Fatal error: Can't use function return value in write context in /home/tr/gitdev/cache/25a251b2ef449de7325445ce3ae6d7d734197d97.file.comment.html.php on line 87

**Comment by spirogg** [comment]
i clear cache all still same issue

**Comment by sakydev** [comment]
Probably a permissions issue. Keep it 777. It is working. Closing this now.
