### ISSUE TITLE
Add Lang code for

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#282]
View Channel page:

Report : <button id="report-user" class="btn btn-default">Report</button>
since: 
last_Login: (3 hours قبل)

My Account Dashboard:

Action : http://prntscr.com/dacgnz
Watched 
Delete
inactive, processing, Viewed
Featured
Uploaded

Followers/subscriptions page at My account:

Username
views

Manage Photos:
title. view, edit, delete
http://prntscr.com/daczi0

Add collection:

Back to collection button, no-tag text, collection type selector 

Change Avatar:

Choose file, no file chosen (if user has uploaded profile pic)

Videos Page:

All text for categories. and this  for arabic  (http://prntscr.com/dad4h6)

Watch video Page:

Comment box text, add to collection text, no collection found,  added to playlist message text.

View Photo page:

Subscribe button, comments box text,

**Comment by Awais-cb** [comment]
Added
