### ISSUE TITLE
Video title issue when you are uploading multiple files at once in different Categories

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#283]
Video title issue when you are uploading multiple files at once in different Categories

Watch the video for better understanding
http://tune.pk/video/6784775/video-title-issue-when-you-are-uploading-multiple-files-at-once-in-different-categories

**Comment by aliawancb** [comment]
When upload multiple videos in different categories, the videos actually go to one category with default title of uploaded file.

@Arman143 the video didn't explained much and consider choosing better background music, Falak dekhon was really good in other videos.
