### ISSUE TITLE
Photo Extension issue when you uploading multiple photos at once cb 2.8.1 stable.

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#284]
Photo Extension issue when you uploading multiple photos at once cb 2.8.1 stable.

watch the video
http://tune.pk/video/6784781/photo-extention-issue-when-you-uploading-multiple-photos-at-once

**Comment by aliawancb** [comment]
@Arman143  I see the issue during upload but the photos are saved with their original title and without the extension.

**Comment by aliawancb** [comment]
@fahad-cb @Awais-cb Not critical, make a decision depending on your time.
