### ISSUE TITLE
Request: Video Manager Suggestions Under Admin Area

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#286]
check the discourse post: http://discourse.clipbucket.com/t/video-manager-suggestions-under-admin-area/2522

**Comment by sakydev** [comment]
Fixed!

**Comment by Arman143** [comment]
HI,
         i have update these 2 files the category worked fine .. but the video resolution dosn't work on my live site using cb. 2.8.1. i am re-converting video from old 2.6 flv to new MP4 it will help me alot if you fix it on my site... there is 25,000+ video that need re-conversion

check the screenshot.
![untitled-1](https://cloud.githubusercontent.com/assets/4317570/20825392/8ff22ee2-b885-11e6-9455-388a3a7d5b1a.png)
 
i have update  functions_video.php with the following code.

```
function resString($res) {
 $qual = preg_replace("/[^a-zA-Z0-9-,]+/", "", html_entity_decode($res, ENT_QUOTES));
 if (!empty($qual)) {
 return $qual;
 }
 }
```

and also update video_manager.html 

```
<span class="label label-primary">
      {resString($video.video_files)} 
   </span>
  <span>
        Categories: {$video.category|categories:video}
 </span>
```
