### ISSUE TITLE
Image is not showing for youtube videos

### ISSUE THREAD

**Issue by MohammedJaffar** [arslancb/clipbucket#288]
Hi, 
when i use grab video from youtube, thumb image is not created and show only this image view(refer screenshot below).
i have a used embed video plugin for grabbing videos.

![capture](https://cloud.githubusercontent.com/assets/8073735/20786126/2f6c8380-b7ca-11e6-8a6a-00c345977516.JPG)
please help me and Thanks in advance

**Comment by sakydev** [comment]
Make sure your server has latest version of cURL installed and files directory is 777.

**Comment by MohammedJaffar** [comment]
Hi @saqirzzq ,
my server is windows server and also php version is 5.4 . i checked the file directory is 777 mode .
still not showing the image
thanks  in advance

**Comment by sakydev** [comment]
ClipBucket is not fully compatible with Windows Server and we strongly discourage use of that due to numerous complications. You are suggested to start using some Linux distribution for CB to work on its 100% force.

Thank you.
