### ISSUE TITLE
Request: How to get Video file Extension in Video Manager Under Admin Area

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#289]
HI,
i am Re-Converting my FLV Video to Mp4 with new modification that made in github i have 26,000+ FLV videos i start re-converting these videos. but i have missed up lots of video during the re-conversion process now i don't know which videos is flv and i can't watch all the videos coz its 26K videos. i want to add file extension under admin area in video manager.. see the screenshot what i want.

![005fd2628c19491da358ef214116bbfe](https://cloud.githubusercontent.com/assets/4317570/20925391/8fe6641c-bbd8-11e6-8470-515befce679e.png)

i will check all pages and select flv and re-covert it to mp4 it will be very helpful for me.. 
if i delete the original FLVs then there is no option to reconvert that videos

Thanks in advance

**Comment by sakydev** [comment]
That's a good suggestion but one that can cause heavy load on page. To be able to show extension like that, we'll need to fetch all video files for video and then parse to fetch extension. Doing the same process for all videos loaded in videos manager will start taking long time.

However, if you are still interested in this feature, I can guide you on how you can add this to your videos manager but we are not going to put it in ClipBucket as we have to consider users with low spec servers as well.

First update to latest development version of video_manager.html and then paste below code at around line #104

`    {$videoFiles = get_video_files($cbvid->get_video($video.videoid))}
    {foreach $videoFiles as $vfile}
         {$vExtension = getExt($vfile)}
         <span class="label {if $vExtension == 'flv'}label-danger{else}label-success{/if}">Extension : {$vExtension} </span> 
          {break}
    {/foreach}`
