### ISSUE TITLE
Upgraded from 2.6 to 2.8.1 and sitemap still showing FLV file not MP4

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#290]
Upgraded from 2.6 to 2.8.1 and sitemap still show FLV file not MP4
please check the screenshot

![untitled-1](https://cloud.githubusercontent.com/assets/4317570/21041912/f280aba8-be0f-11e6-9715-456a0fab7db5.jpg)

any help.. please to correct that..

**Comment by aliawancb** [comment]
@fahad-cb review and close
