### ISSUE TITLE
Registered User can change there email to any none existing email without confirmation

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#291]
Registered User can change there email to any none existing email without confirmation
check screen shot.

![untitled-2](https://cloud.githubusercontent.com/assets/4317570/21042030/d5cb7938-be10-11e6-958b-2ba663b9fcdf.jpg)

**Comment by aliawancb** [comment]
@fahad-cb  Review and label, its not a critical issue so if its up to you.
