### ISSUE TITLE
Video thumbs problem

### ISSUE THREAD

**Issue by p3rtinax** [arslancb/clipbucket#293]
Dear developers, 
last night ( 12-16-16 ), I installed clipbucket on a test server, but still have the issue " Video thumbs are not being generated. "
in the old topic you said it fixed by farhad abbas, but its not, please guide me to resolve this problem.

I'm going to buy multi-server license but if this issue be there, no chance :(

logs says its generated but folders are empty! 

`Thumbs Generation
-----------------
Starting

Thumbs Files
------------

File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-original-1.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-original-2.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-original-3.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-168x105-1.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-168x105-2.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-168x105-3.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-416x260-1.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-416x260-2.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-416x260-3.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-632x395-1.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-632x395-2.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-632x395-3.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-768x432-1.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-768x432-2.jpg 
File : /var/www/html/upload/files/thumbs/2016/12/17/1481995940fbf13-768x432-3.jpg 
====== End : Thumbs Generation ======= 
`

![image](https://cloud.githubusercontent.com/assets/19358918/21288538/483b1cf4-c49b-11e6-9543-1d7121dd53a1.png)

**Comment by aliawancb** [comment]
@p3rtinax This is a server module related issue, its not a bug in the script, thumbs generation works fine in the latest version.
