### ISSUE TITLE
When trying to edit language file in admin section wont edit after stays the same even when press update ?

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#3]
When trying to edit language file in admin section wont edit after stays the same even when press update ? in 2.6 we could edit grammar and save, why not now ?

thanks

**Comment by fahad-cb** [comment]
Have you tried the latest commited source ? 
This issue has been fixed, not officially resealed though

Regards

**Comment by spirogg** [comment]
ok thanks
