### ISSUE TITLE
URL search is not as it should be

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#30]
if I try to look in ClipBucket the word "test", the URL of the internal search engine is 
http://demo.clipbucket.com//search_result.php?query=test&type=videos&cbsearch=Go1

it's horrible to see

As it should be: http://demo.clipbucket.com/search/?query=test

OR as YouTube

http://demo.clipbucket.com/results?search_query=test1

OR

http://demo.clipbucket.com/search_result?query=test1

**Comment by sakydev** [comment]
Killed!
