### ISSUE TITLE
users not listed under members area

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#303]
create a user from back end/admin panel, user can operate normally, however user does not show under manage members section.
neither does admin actually, nothing shows
this is from new install downloaded from here about 12 hours ago on 1-18-2017

**Comment by dmaclip** [comment]
actually members created from signining up on front end also don't show in admin panel

**Comment by dmaclip** [comment]
upgrading site causes same issue

**Comment by sakydev** [comment]
We are making some drastic changes. Development version will behave in unexpected ways till release.

**Comment by dmaclip** [comment]
then you better make sure zip file downloaded form website isn't same one downloaded from here.
may have been fluke but version I tested I downloaded from main website.

**Comment by sakydev** [comment]
Then you should recheck what you downloaded because I can confirm that link on website's download page is going to latest STABLE release and not development version
