### ISSUE TITLE
Server configuration update while php.ini values are OK

### ISSUE THREAD

**Issue by romjean** [arslancb/clipbucket#31]
Hi,
I've this message into the admin area: "You must update "Server Configurations". Click here for details". The php.ini values were updated to fit the requirements but the message is still there (see attached image)!
Help !
RomJean

![2016-04-14_13-02-16](https://cloud.githubusercontent.com/assets/15798122/14526499/e3296506-0243-11e6-8017-4236ca0c7439.png)

**Comment by sakydev** [comment]
Fixed in latest ClipBucket

**Comment by asif-raza** [comment]
I just installed the ClipBucket 2.8.1 and have the same issue. Can someone tell me the solution please?

**Comment by sakydev** [comment]
Just ignore it if your configs are OK

**Comment by iStudLion** [comment]
Where do I go to update the Server Configuration?
