### ISSUE TITLE
Numeric usernames

### ISSUE THREAD

**Issue by collegemerici** [arslancb/clipbucket#311]
Hello

I need to have several accounts added that have numeric-only usernames (ex. 0192837)

When these users log in to Clipbucket, it returns as User does not exist (user_doesnt_exist lang code)

I believe the problem is that when the username is only numeric, Clipbucket tries to connect the user using the user ID, not the username. For example, if my user 0192837 has user ID 102 in the users database, I get user_doesnt_exist if I log using username 0192837, but I connect successfully if I use 102 as username.

If I change the username from 0192837 to 0192837a, it works since it is not numeric only, so the connection is successful.

I already have V2.8.1 RC2 installed in August 2016.

It seems to be with the Check_User_Exists function in /includes/classes/user.class.php

I disabled the 3 IF lines so it won't check if the numeric username is a user id. My numeric usernames work at login now.

However, I get many « User does not exist » error while using many functions, like changing the avatar, viewing a channel, or deleting an user from the admin panel.

Thank you

    //Check User Exists or Not
    function Check_User_Exists($id,$global=false){
            global $db;

            if($global)
            {
                    if(empty($this->user_exist))
                    {
                            if(is_numeric($id))
                                    $result = $db->count(tbl($this->dbtbl['users']),"userid"," userid='".$id."' ");
                            else
                                    $result = $db->count(tbl($this->dbtbl['users']),"userid"," username='".$id."' ");
                            if($result>0)
                            {
                                    $this->user_exist = 'yes';
                            }else{
                                    $this->user_exist = 'no';
                            }
                    }

                    if($this->user_exist=='yes')
                            return true;
                    else
                            return false;
            }else
            {
                    //if(is_numeric($id))
                            //$result = $db->count(tbl($this->dbtbl['users']),"userid"," userid='".$id."'");
                    //else
                            $result = $db->count(tbl($this->dbtbl['users']),"userid"," username='".$id."'");
                    if($result>0)
                    {
                            return true;
                    }else{
                            return false;
                    }
            }

    }

**Comment by arslancb** [comment]
@collegemerici 
This hack will work but there are many places we use 'get_user()' function which uses the same methodology.

Adding 'OR' in the query can effect Website performance. we will look into this in future.

**Comment by collegemerici** [comment]
Thank you for your support!

**Comment by collegemerici** [comment]
Hello, just installed 2.8.2 and the issue is still there, can you give me an estimate date of fix? thank you!

**Comment by collegemerici** [comment]
Do you intend to fix this issue for 2.8.4?

Thank you!
