### ISSUE TITLE
Not fetching users/channels in Latest Source

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#320]
Not fetching users/channels in Latest Source

http://prntscr.com/e9wbd0
http://prntscr.com/e9wbip

**Comment by dmaclip** [comment]
https://github.com/arslancb/clipbucket/issues/303
listed as invalid yet is same issue as
http://prnt.sc/e9wbd0

**Comment by ASponch** [comment]
Hi Clipbucket team ! 

For information I make a pull request for this issues : https://github.com/arslancb/clipbucket/pull/306

Have a nice day.

**Comment by fahad-cb** [comment]
This is issue has been fixed .. !
Thankyou ! @ASponch  for your contribution as well
