### ISSUE TITLE
Search bar keyword limit exceed and goes out of design

### ISSUE THREAD

**Issue by yousafrasheed** [arslancb/clipbucket#340]
http://prntscr.com/ekzjfj

**Comment by fahad-cb** [comment]
any one who wants to search an "Essay" in CB . can fix this issue by himself

**Comment by yousafrasheed** [comment]
@fahad-cb  shrink the text like youtube ( http://prntscr.com/ekzyy1 )

**Comment by fahad-cb** [comment]
Alright ! @yousafrasheed will be fixed

**Comment by Awais-cb** [comment]
Fixed!
