### ISSUE TITLE
Please check the https://demo.clipbucket.com/ functionality with IE11

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#354]
The following resolved issue appeared again.
https://github.com/arslancb/clipbucket/issues/224

Also when you click on the main page a video thumbnail, the full screen video player is corrupted.
http://prnt.sc/em7e6i

**Comment by aliawancb** [comment]
One cannot keep up with the IE, its too advance for today's web technology...

**Comment by pcmcis** [comment]
Hi,
I understand that you are dropping support on Microsoft browsers.
Please update your supported browser list so it's clear, that some features might not work correctly on IE11 and Edge.
On the other hand, I cannot force anyone to install Chrome or Firefox on his/her machine if they don't want to.
