### ISSUE TITLE
Subscribed User's Videos Page is missing ?

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#356]
HI,
      whats the functionality of Subscribe button. youtube showing recently uploaded video from subscribed users and tube.pk as well.. but i can't find that page in clip bucket 2.8.1 or 2.8.2 ... 

tune.pk
![tunepk](https://cloud.githubusercontent.com/assets/4317570/24397984/4fdab71a-13c1-11e7-9864-2033066473fa.jpg)

YT
![yt](https://cloud.githubusercontent.com/assets/4317570/24397990/55571788-13c1-11e7-8706-813ae00ffbda.jpg)

Regards

**Comment by spirogg** [comment]
I like this idea. Please make it. I know you can do it guys. You are awesome. 😎
