### ISSUE TITLE
 Filtering videos for “viewed” by time period is not working

### ISSUE THREAD

**Issue by adam1000018** [arslancb/clipbucket#357]
For "viewed" only "all time" shows videos from correct period.
Other time periods  for "viewed" are not working.

**Comment by aliawancb** [comment]
The flters work fine in the latest version.

**Comment by adam1000018** [comment]
this problem still remains. now affects all time period too.
As I wrote on clipbucket discourse, after every unique view video disapears from 'viewed'. After non unique view it appears again but it acts like it was added that day (when non unique view was).
