### ISSUE TITLE
Audio problem while playing video

### ISSUE THREAD

**Issue by raiancollyn** [arslancb/clipbucket#360]
Today I tried to send a video file, I had no problems, the problem even came up during the playback of the video, it worked correctly, but the audio had an accelerated effect, and I did not make any changes to the original file.

This is the video on YouTube: https://www.youtube.com/watch?v=r9OWmGwbRG0
This is Video upado and with problems of audio: http://up.dpbr.ml/kontinuum-lost-feat-savoi-jjd-remix-ncs-release_v983

This problem only appears with this file (in mp4 format), I tried to send a file in another format (in avi case) to test, and it worked correctly.

If it has any relevance, I did other tests, the configuration in which it presents this problem is in the "High Configurations With H264" conversion configuration, I also tested in the "H.264, ACC - Youtube like" configuration, however in this file did not present Problems, the quality was not very good.

**Comment by raiancollyn** [comment]
I forgot to quote, here is the URL of the file sent using the setting "H.264, ACC - Youtube like": http://up.dpbr.ml/kontinuum-lost-feat-savoi-jjd-remix-ncs-release_v975

**Comment by aliawancb** [comment]
There could be an issue with encoding of this specific file.

The following error was encountered while trying to retrieve the URL: http://up.dpbr.ml/kontinuum-lost-feat-savoi-jjd-remix-ncs-release_v983

Unable to determine IP address from host name up.dpbr.ml
