### ISSUE TITLE
mass_uploads_php not working with other add-ons

### ISSUE THREAD

**Issue by scarar** [arslancb/clipbucket#362]
Their is a conflict within the Add-ons that causes mass_uploads.php not to convert the videos. Here is a fix for it if you are using the Ultimate version. I sent this file to clipbucket and problem wasn't fix or not discovered. Posting this issue someone will be able to use the code to fix it. I'm unable to do a pull request from here for some reason and unable to post the code. I hope someone is able to help fix this bug and find out why its causing this issue with this add-on. 
[mass_uploader.txt](https://github.com/arslancb/clipbucket/files/916612/mass_uploader.txt)

**Comment by scarar** [comment]
Will this be fixed for the Ultimate version?

**Comment by scarar** [comment]
Have you guys install the Ultimate bundle to see why the mass_upload.php file not working when the addon is installed?

**Comment by scarar** [comment]
Has anyone else having issues with this file?

**Comment by scarar** [comment]
Was the mass_uploader.php been fix to allow mass uploader to work with Ultimate Version?

**Comment by aliawancb** [comment]
Yes, this issue was fixed in last release.
