### ISSUE TITLE
@Awais-cb please look again add-playlist-from-a-video-doesnt-work-link-gives-error-and-more-read-and-see-photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#382]
http://discourse.clipbucket.com:3000/t/add-playlist-from-a-video-doesnt-work-link-gives-error-and-more-read-and-see-photos/2660
![playlist-from-video-page-creates-errors](https://cloud.githubusercontent.com/assets/17736688/26569417/3cbbb068-44d0-11e7-8f10-6d3cdbda948b.PNG)
![user-playlist-playnow-not-working](https://cloud.githubusercontent.com/assets/17736688/26569423/46a13076-44d0-11e7-94b5-14a9474c89ea.PNG)
![seo-off-playlist-link-error](https://cloud.githubusercontent.com/assets/17736688/26569428/50223c76-44d0-11e7-9609-88d0a306c8b4.PNG)
![index-html-playlist-link-error](https://cloud.githubusercontent.com/assets/17736688/26569441/676021c8-44d0-11e7-98ae-6bb20b3e8449.PNG)
![manage-playlist-error](https://cloud.githubusercontent.com/assets/17736688/26569453/791f021c-44d0-11e7-9149-0c71f65d7a0f.PNG)

**Comment by Awais-cb** [comment]
Hi @spirogg to play that playlist you must have any video in your playlist otherwise that button "play now" won't work after adding new playlist you must have to add a video in it then playlist will work fine.

**Comment by spirogg** [comment]
@Awais-cb there is video please look at photo

**Comment by spirogg** [comment]
@Awais-cb can you check again please.. from a video on your demo site add a new playlist and then go to main page and try to click on link not image of video just the link to the playlist.. You have to add a playlist from a video not from /manage_playlists.php?user=admin from any video.. then after you see the playlist link ( name of playlist) if you click on that it will not get you to the playlist page will go back to main site
if i click on the playlist title i get this below

https://mywebsite.com/?play_list=16

if i click on the video image (thumb) it works correctly

https://mywebsite.com/video/1173/nino-%CE%98%CE%B5%CF%8C%CF%82-nino-theos-official-video-clip-hq?play_list=16


THE ISSUE IS PLAYLIST LINK NOT WORKING

**Comment by Awais-cb** [comment]
@spirogg please verify your database if it is as same as ours.

**Comment by spirogg** [comment]
@Awais-cb  how can i do this ? i am using the latest as of today from here github, i uploaded all files today

i had already installed from Github 2-3 weeks ago and uploaded all foders and files except for CB_install and Cache and Files ? should I of uploaded CB_install also, did not want to loose any videos from my site ?

**Comment by spirogg** [comment]
@Awais-cb 

is this code correct ??

```
function view_playlist( $playlist_id ) {

    $playlist_link = BASEURL;

    if ( is_array( $playlist_id ) and isset( $playlist_id[ 'playlist_id' ] ) ) {
        $playlist = $playlist_id;
    } else {
        $playlist = get_playlist( $playlist_id );
    }

    if ( empty( $playlist  ) ) {
        return BASEURL;
    }

    $is_seo = SEO;


    $data = cb_do_action( 'view_playlist_link', array( 'playlist' => $playlist, 'seo_enabled' => $is_seo ) );

    if ( $is_seo ) {
        $playlist_link .= '/list/'.$playlist[ 'playlist_id' ].'/'.SEO( $playlist[ 'playlist_name' ] );
    } else {
        $playlist_link .= '/view_playlist.php?list='.$playlist_id;
    }
```

**Comment by spirogg** [comment]
is this code correct ? or how to fix my databse incase there is error in there ? 

```
`			<!-- playlists -->
			{$playlists = get_playlists(['limit'=>4, 'order'=>'total_items DESC'])}
			{$playlists = activePlaylists($playlists)}
			{if $playlists}
			<div class="clearfix sidebar-playlists">
				<h2 title="Playlists with most videos">{lang code="top_playlists"}</h2>
				{foreach $playlists as $playlist}
				<div class="playlist clearfix"> 
					<a href="{videoLink vdetails=$playlist['first_item']|@json_decode}{if $Cbucket->configs.seo == 'no'}&{else}?{/if}play_list={$playlist.playlist_id}"><h3>{$playlist.playlist_name}</h3></a>
					{$items = get_playlist_items($playlist.playlist_id)}
					<div class="clearfix row">
					{foreach $items as $item}
						{if $item@iteration == 5}
							{break}
						{/if}
						{$videoid = $item.videoid}
						{if $videoid}
							<div class="video col-lg-3 col-md-4 col-sm-6 col-xs-6">
								{$videos = get_videos(['videoid'=>$videoid,'limit'=>'2'])}
								{foreach $videos as $video}
									<a href="{videoLink($video)}{if $Cbucket->configs.seo == 'no'}&{else}?{/if}play_list={$playlist.playlist_id}" class="playlist-video">
										<img src="{getThumb vdetails=$video size=168x105}" class="img-responsive">
										<img src="{$theme}/images/thumb-ratio.png" alt="" class="thumb-ratio">
									</a>
								{/foreach}
							</div>
						{else}
						<div class="clearfix well">no items</div>
						{/if}
					{/foreach}
					</div>
					<span class="videos-count">{$cbvid->action->count_playlist_items($playlist.playlist_id)|number_format}&nbsp;{lang code="videos"}</span>
				</div>
				{/foreach}
			</div>
			{else}
				{if has_access('admin_access')}
					<div class="clearfix well">{lang code="no_playlists"}</div>
				{/if}
			{/if}
		</aside>
	</div>	
</div>`
```

**Comment by Awais-cb** [comment]
Issue is fixed in current version.Try updating the source
