### ISSUE TITLE
ClipBucket: LIke, Dislike and Subscribe button not working.

### ISSUE THREAD

**Issue by Allanbuzzy** [arslancb/clipbucket#384]
So I installed the script on cPanel and the Subscribe, Like and Dislike buttons do not work. If you try to click it the number does not go up or go blue. Is there a fix to this?

**Comment by abaalkh** [comment]
Can you give us the console log on your browser? Maybe there is a 500 error on ajax.php.
Then you'll need to check the error log for PHP and see what it says.
