### ISSUE TITLE
Support for mysqli extension

### ISSUE THREAD

**Issue by hidayat365** [arslancb/clipbucket#385]
We all aware that mysql extension is deprecated and already removed in PHP 7.0. Is there any plan to support mysqli, or probably PDO?

**Comment by abaalkh** [comment]
I agree this is very important.
Even speaking from a security and performance perspective, PDO should be used.

**Comment by MacWarrior** [comment]
Hi, 

Speaking of performance, MySQLi and PDO are almost the same (Both are far far faster than MySQL)

Switching to MySQLi is much more faster than PDO thanks to the major compatibility of the MySQL functions : in most case, you just have to replace "mysql" by "mysqli" and it works (Not the best way, but it works)

In my opinion, the first step is to switch to MySQLi as a minor update and then to PDO as a major update

**Comment by MacWarrior** [comment]
Hi, 

Here are the modifications needed to switch from MySQL to MySQLi : 
https://github.com/MacWarrior/clipbucket/commit/2f6d0325f5af52511a72da58033c0fd1a36dadde
https://github.com/MacWarrior/clipbucket/commit/9c6c99bfe1079ffc8fa78f5f1e9771805c7abbda
https://github.com/MacWarrior/clipbucket/commit/56ec3e50bd8eb670a1fa868c53dc4ae4f3e441d3
