### ISSUE TITLE
Remote Upload - YouTube Grab issue

### ISSUE THREAD

**Issue by tahirafridi** [arslancb/clipbucket#388]
Dear developers,

I'm facing a bit strange issue while grabbing youtube video using remote upload options. From a youtube channel I was trying to grab video and its working fine, but as I enter another youtube url in grabber, it just doing nothing, no error nothing else.

But as I see the console > network... network window i see after clicking on the grab button url fired and it got response and in response i can see youtube data , title, desc, tags, etc. But after clicking the grab button it won't drop down the form for editing purpose, and also the video not found in managers, videos pages etc.

Please have a look into this video screen recorder: https://www.useloom.com/share/520db27d4cf149269567d80a81fa52dc

Note: The video url has no embed restrictions in my country or anything else. If I copy embed code manually and put the code in html code its working fine. So please don't say this that it might be the video owner is restricted the video in your country or he/she might set some special rules, if this is the case then why they don't set the rules for other their videos.

**Comment by move-IT-online** [comment]
I confirm that YouTube Grabbing in ClipBucket is not very reliable, other Software (PHP Melody) make this Job much better.

**Comment by Awais-cb** [comment]
@tahirafridi have you tried updating Clipbucket with the latest source?

**Comment by tahirafridi** [comment]
@Awais-cb I just downloaded the source from your official website. the stable version.
But due to some reasons I can't upload all files, could you please suggest me which files should I upload from github repo to check if the issue resolved or not.

**Comment by Awais-cb** [comment]
grab the file_downloader.php from Clipbucket repository and replace it with old ones! this will probably resolve this problem.
here is the link : https://github.com/arslancb/clipbucket/blob/master/upload/actions/file_downloader.php

**Comment by tahirafridi** [comment]
@Awais-cb I just updated the file actions/file_downloader.php but no luck. Yes I did it before your 2nd comment already. No luck, I see the file is firing after clicking on the grab button. and this file is updated just 3 days before. It might be something else. please check it on your end with this youtube url and figure out the issue thnx.
url: https://www.youtube.com/watch?v=axjigH8di_k

The above same url i just embedded the video manually and its working but with grabber its not working you can demo the embed here eshows dot pk

**Comment by Awais-cb** [comment]
@tahirafridi same source is running on http://demo.clipbucket.com/ 
and youtube grabber is working fine at there
there is no issue with "\n" issue is with vid which is being fetched with the same source on our demo.
i will recommend you to try it by yourself
username: demo
password: demo
on your side vid is null
please consider replacing the code of file_downloader.php again on your server and try grabbing.

**Comment by tahirafridi** [comment]
@Awais-cb please suggest me the process that how to update the files and folder, because i don't want to replace the existing things that is some styling, and my db details thnx.

I just uploaded files via folder by folder, accept the dbconnect.php file. but the error is still there, i didn't updated the admin_area folder

**Comment by tahirafridi** [comment]
@Awais-cb today I just removed the cb whole files from my server and re upload the files from clipbucket github repo. with latest files and folders. But the issue is remain same. Please help me thanks!

**Comment by Awais-cb** [comment]
@tahirafridi we can not assist you unless we look into the issue on your side it is working fine on our demo we would be needing your ftp credentials to assist you on this.

**Comment by tahirafridi** [comment]
@Awais-cb please let me know how to send you my ftp details thanks :) give me your email id or let me know if I can send you msg here in github.

**Comment by Awais-cb** [comment]
you can send your ftp credentials on this email id: awaisfiaz.dev@iu.com.pk

**Comment by tahirafridi** [comment]
@Awais-cb plz check your email, I have sent the ftp details my clpubcket admin area info thnx. waiting for your response

**Comment by Awais-cb** [comment]
We are looking into this @tahirafridi will get back to you soon.

**Comment by tahirafridi** [comment]
@Awais-cb any update regarding the issue? Thanks for your time.

**Comment by tahirafridi** [comment]
@Awais-cb dear I have checked that my current website php version is 5.6+ and when I checked the same thing on php version 5.4 the issue is no more and its resolved. So I think you have to update the code to 5.6+ There is might b some functions which are deprecated in 5.4 Let me ask my hosting provider to change my eshows.pk php version to 5.4 for now.

**Comment by Arman143** [comment]
the issue is php version i have php 5.4 and everything is working fine... running clip bucket 2.8.2
@tahirafridi try to downgrade php version to 5.4 and then try it..
