### ISSUE TITLE
js failled during install on databse tab

### ISSUE THREAD

**Issue by benIT** [arslancb/clipbucket#391]
Hi, 
I encounter a JS error while installing app.
On the "database" tab of the web installer, there this js error.
Error on chromium 57:
```
functions.js:11 Uncaught TypeError: Cannot read property 'err' of null
    at Object.success (functions.js:11)
    at Object.resolveWith (jquery.min.js:16)
    at w (jquery.min.js:16)
    at XMLHttpRequest.c (jquery.min.js:16)
```

Error on firefox 52:
```
TypeError: data is null[Learn More]  functions.js:11:1
	dbconnect/< http://lab.local/clipbucket-4829/upload/cb_install/functions.js:11:1
	d</<._Deferred/f.resolveWith https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js:16:12499
	w https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js:16:66778
	.send/c https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js:16:72471
```

The gif loader appears and the install is locked at this step.

The response of the `ajax.php` request if empty which makes the js processing failed.

**Comment by lg0killer** [comment]
I presume you are using php7?

**Comment by MacWarrior** [comment]
Hi, 

I confirm it may come from PHP7
I've been upgrading clipbucket to PHP7 today and there's at least all mysql to convert to mysqli and some broken switch case to fix to make it run

**Comment by hackertron** [comment]
Hey i am also using php 7 , can you please share your updated copy of clipbucket . i will be able to use it too then . 

Thank you !!

**Comment by lg0killer** [comment]
Use php 6.4 and it should be fine. The issue is with the mysqli and mysql conversions as php7 does not support mysqli any more.

At least that is what worked for me

**Comment by MacWarrior** [comment]
Hi, 
To upgrade to PHP 7.X, here are the modifications needed : 
https://github.com/MacWarrior/clipbucket/commit/2f6d0325f5af52511a72da58033c0fd1a36dadde
https://github.com/MacWarrior/clipbucket/commit/9c6c99bfe1079ffc8fa78f5f1e9771805c7abbda
https://github.com/MacWarrior/clipbucket/commit/734f5190afc647f03e88ad4b8411dbe9bc8e67cd
https://github.com/MacWarrior/clipbucket/commit/5f3f122b582da16f4e302ea8c43ccaa0af90f592
https://github.com/MacWarrior/clipbucket/commit/56ec3e50bd8eb670a1fa868c53dc4ae4f3e441d3
( Switch from MySQL to MySQLi + fix some multiple default in switch case )
