### ISSUE TITLE
Level of Support?

### ISSUE THREAD

**Issue by mwweb** [arslancb/clipbucket#393]
Is there some special magic wand that needs to be waved to get answers, or even access to discourse on clipbucket.com?

I signed up for discourse a couple of weeks ago, and have re-requested the confirmation email 3 times, with never getting any emails. I also sent an email via contact on the website, and no response. 

This zero amount of support/answers of any kind makes me question the level of support provided. My client is, potentially, interested in one of the paid options, but I wouldn't bother with this zero support.

**Comment by aliawancb** [comment]
Kindly try logging in with your discourse details, the emails are not working due to an upgrade issue with discourse platform and our tech support is working to replace the platform. All accounts are manually activated after 24-48 hours.

**Comment by mwweb** [comment]
That doesn't work. It keeps referring to the email that was sent to me to activate my account.
![clipbucket-forum](https://user-images.githubusercontent.com/19194012/30287962-ee1cd410-96db-11e7-8635-9ab523ccd6ff.png)
