### ISSUE TITLE
Dashboard hanging ClipBucket V2.8.1 STABLE and then never respond till apache restart

### ISSUE THREAD

**Issue by johnsaida3** [arslancb/clipbucket#394]
i am using ubuntu 14.04 and 15.04 both but the problem is not resolved will u plz tell me the solution find the screenshot bellow.
thanks.
url: _http://localhost/clipbucket/upload/admin_area/index.php
_
![image](https://user-images.githubusercontent.com/30964024/29244732-bcb06050-7fdd-11e7-862e-3791c9b8304f.png)

**Comment by Awais-cb** [comment]
please update clipbucket to 2.8.3 this issue is resolved in that.!
