### ISSUE TITLE
localhost signup

### ISSUE THREAD

**Issue by Syedwaheed** [arslancb/clipbucket#396]
Hi there,
i have installed the clip bucket but i have missing some pre-requisite i.e FFMPEG,MP4Box etc . After installation i have seen through my database neither admin account nor user sign up values stores in it. when i go through sign up it doesnt show any error there too. i m using "Wamp server" as localhost and my database is mysql. Any help would be appreciated. Thanks in advance.

**Comment by Awais-cb** [comment]
Hi @Syedwaheed 
if you haven't found `cb_user` table please make sure to turn off `sql_strict_mode`
to check if `sql_strict_mode` is on run this this sql command `SHOW VARIABLES LIKE 'sql_mode'`
if it shows `STRICT_TRANS_TABLES`
please run this command in sql `set global sql_mode='';` and install again 
also please check your php version Clipbucket is not supported above php version 5.6.

**Comment by Syedwaheed** [comment]
Thanks for your prompt reply @Awais-cb . I m using php version "5.6.19" and sql_strict_mode shows "NO_AUTO_VALUE_ON_ZERO" and i cant see "cb_user" table in mysql database.

**Comment by Awais-cb** [comment]
have you run this `set global sql_mode='';` command and installed again?

**Comment by Syedwaheed** [comment]
How can i get all these on my system? @Awais-cb. 
![capture](https://user-images.githubusercontent.com/14071753/29610323-4d4e6ce6-8813-11e7-831b-8cd146b74d82.JPG)

**Comment by Awais-cb** [comment]
which OS you are using? if you are using linux ubuntu 
here is the document that can help you 
https://docs.google.com/document/d/1GubKnsxXlnyGdTNbkhhflLkUkAUsFg5Lq7ahQFoF8BE/edit

**Comment by Syedwaheed** [comment]
I m using Windows 10. One more thing How to configure mail in local host so user will be authenticated once they will be sign up locally. As i have created one user but email verification is required but no mail has been received in mail.

**Comment by Syedwaheed** [comment]
Thanks for you replies. I have took activation code from my database and activate it with out mail but when i upload the video it shows video added but it wont play and on Manage videos when i play the video it shows "An error occured while uploading the video". I m uploading .mp4 and .flv extension videos. Can you help me out this @Awais-cb . Thanks once again.

**Comment by Awais-cb** [comment]
@Syedwaheed have you installed ffmpeg,MP4Box on your system if yes then please check their installation path and set them accordingly in Clipbucket.
and for activation on you local system you can activate any user from Clipbucket admin area by logging in with an admin account.

**Comment by Awais-cb** [comment]
Closing issue for now you can open it again if you face any inconvenience.
