### ISSUE TITLE
Video Uploading issue

### ISSUE THREAD

**Issue by Syedwaheed** [arslancb/clipbucket#397]
Hi there,
When i upload the video it shows 100% complete on bar, but when i see video in video menu there it show time "00:00". Video show error occurred when uploading the video. Can anyone tell me where it goes wrong?i m uploading .mp4, .flv extensions file and i m using "Wamp server localhost" and operating system "Windows".

**Comment by johnsaida3** [comment]
hi waheed 
will you plz tell me how to install clipbucket in windows. tell me step by step clearly 
thankyou.

**Comment by Syedwaheed** [comment]
install the file in your local server i.e www directory or htdocs. Create database schema only and access it through your broweser localhost i.e "localhost/clipbucket/". There will be start up screens to come up and you need to follow those screens and there you will have clipbucket installed locally.
