### ISSUE TITLE
upload date not listed in description

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#399]
this is a LONG ongoing issue, user/admin uploads video through web interface and under video manager the upload date is blank.
has to be corrected in sql itself to make it right.

**Comment by aliawancb** [comment]
verify and fix

**Comment by Awais-cb** [comment]
@dmaclip can you please attach a screenshot?

**Comment by dmaclip** [comment]
done 3 days ago using latest version from github
![capture](https://user-images.githubusercontent.com/20878066/36904042-81d0dc26-1dfd-11e8-9b51-4405cd925cfa.PNG)

**Comment by Awais-cb** [comment]
Working fine now please update this 

> admin_area/styles/cb_2014/layout/edit_video.html

 file and check if it is fixed.Closing the issue for now you can open it again if you face this issue again.

**Comment by dmaclip** [comment]
ok will test later today
