### ISSUE TITLE
signup page issue: http://localhost/cb_svn/upload/signup.php?valid=fail

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#4]
ERROR: 
http://localhost/cb_svn/upload/signup.php?valid=fail

If a user just clicks submit without adding text to the form, or does not add all required fields I get this error above, no redirect back to signup page redirect to localhost??

**Comment by fahad-cb** [comment]
Signup Captcha (DEPRECATED) 
Uninstall this plugin please !

**Comment by spirogg** [comment]
I am using plugin 2.7 captcha not deprecated. One. Still does it.

**Comment by spirogg** [comment]
Is there no plugin for captcha that  will Not create this issue ? Am I doing something wrong. ? 
Only have One plugin the 2.7 one and helper plugin for crons. That's all I have installed / activated.

**Comment by spirogg** [comment]
this happens with 2.7 plugin for captcha (( This only happens if user **Does NOT CLick** on IM NOT A ROBOT )) just fyi

**Comment by sakydev** [comment]
Plugin has been fixed. You may use from now on.
