### ISSUE TITLE
login (signup) user very slow without internet

### ISSUE THREAD

**Issue by gvasquezj** [arslancb/clipbucket#401]
I have reviewed signup.html and signup.php change
<script src = "// code.jquery.com/ui/1.10.4/jquery-ui.js"> </ script> by
<script src = "{$ baseurl} /js/jquery-ui.js"> </ script> previously downloading the file. Same for <script src = 'https: //www.google.com/recaptcha/api.js'> </ script>. (global_head.html) and all the ones I found. But I can not solve the problem.

The problem is only when there is no internet. some help?

Greetings from
Punta Arenas - Chile

**Comment by MacWarrior** [comment]
Hi, 
Maybe you should also check for custom fonts, for example : 
//fonts.googleapis.com/css?family=Cabin:regular,bold (Body.php : l8)

**Comment by gvasquezj** [comment]
thanks for the reply. I changed all the codes I found, but I did not solve the problem and does not affect watching videos. i'll leave it like that :)

regards

**Comment by MacWarrior** [comment]
Hi,
Do you reproduce this while connecting on front office or back office ?

On back office, there is a curl operation to get latests news, without timeout : 
=> function.php : function xml2array($url, $get_attributes = 1, $priority = 'tag',$is_url=true) 
=> curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0); 

This may explain slow login on BO, but not on FO...

**Comment by gvasquezj** [comment]
I'll explain more in detail

I work in a school and I have a virtual wireless network for intranet services to students including moddle, web library, etc, etc ... and clipbucket with educational videos. This network works without internet (intranet) and allows the connection of the computers and smartphone of the students. but it is very slow to log in so they can upload and comment content. They love to use clipbucket, but they complain that the login is very slow.
The simple solution is to give access to internet. but students use it badly and collapse the internet. I have changed some css and js codes that were online, but the problem continues.

I leave here three videos that explain the problem better

clipbucket with internet on local network (normal Function)
https://youtu.be/dab0XTaUimY

without internet no gateway (only IP localnetwork)
https://youtu.be/6v2SBCoYXZU

without Internet on localnetwork  (Not NAT)
https://youtu.be/yfzd3wLnEso

**Comment by MacWarrior** [comment]
Hi,

I've been trying to reproduce without success
Just in case, did you delete html pages cache ( /upload/files/temp/* ) after editing JS URLs ?

Do you get any error in chrome console ? (Or PHP ?)
To notice : api.js try to download another file (recaptcha__fr.js in my case) but even if browser can't reach it, the page load anyway

**Comment by gvasquezj** [comment]
yes, the cache has been deleted, for different tests.

The error is with api.js, but the change is still the same. Could be some problem with my network. so delete the gateway with that enough for now. I will continue testing, does anyone else have the same problem?

Thanks for the help :)
