### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ThejeswarReddy** [arslancb/clipbucket#405]
HI there, are you working on premium subscriptions and live streaming options if not, is it possible for you guys to make them happen.

**Comment by ThejeswarReddy** [comment]
Okay I see paid module plugin for subscription. Now do you have a live stream plugin too?

**Comment by aliawancb** [comment]
Yes, ClipBucket integrates with Wowza Live Streaming services and allows users to broadcast live streaming using the Mobile camera in mobile apps, Web Cam or any other streaming source. Our team will configure the live streaming server and integrate it with your ClipBucket site and mobile apps. You will have to buy the license for Wowza Live Streaming services and get a server for it. Contact me for pricing at ali.ahmed@clipbucket.com
