### ISSUE TITLE
Fatal error when uploading thumbnail on processing video

### ISSUE THREAD

**Issue by szorg** [arslancb/clipbucket#407]
When uploading a thumbnail for a video that is currently processing, I get this message:

Fatal error: Call to undefined function imagecreatetruecolor() in /var/www/html/includes/classes/image.class.php on line 33

When I go back, or reload the previous page, the thumbnail is present. 

Clipbucket 2.8.3
CentOS 6.9
apache/httpd 2.2.15-60
php 5.6.31-2

**Comment by szorg** [comment]
To note, I am not certain as yet if the issue persists once the video is finished processing - I will test once my videos are finished. My server is quite slow to convert. :)

**Comment by szorg** [comment]
The error persists even once the video is finished processing.

**Comment by MacWarrior** [comment]
Hi,

\upload\plugins\cb_server_thumb\timthumb.php : l.536
=> GD Library Error: imagecreatetruecolor does not exist - please contact your webhost and ask them to install the GD library

Never met this error before ; can you check if this library is correctly installed and enabled ?
