### ISSUE TITLE
Can't proceed on new Installation with PHP 7

### ISSUE THREAD

**Issue by draft1** [arslancb/clipbucket#408]
Error was:

> Fatal error: Uncaught Error: Call to undefined function mysql_connect()

**Comment by MacWarrior** [comment]
Hi,

PHP 7.X is not currently supported, see this issue for more informations : 
https://github.com/arslancb/clipbucket/issues/391

**Comment by Awais-cb** [comment]
Clipbucket now support PHP 7.0 closing this issue for now you can open it again if you face any issue.
