### ISSUE TITLE
How to use 'www' second domain?

### ISSUE THREAD

**Issue by deepzliu** [arslancb/clipbucket#409]
How to use 'www' second domain? 'www.domain.com' always jump to 'domain.com'.

**Comment by MacWarrior** [comment]
Hi,

If I'm right, Clipbucket can only work with one domain, all others will be redirected
You might want to change domain.com to www.domain.com : check your cb_config DB table

**Comment by deepzliu** [comment]
Thank you for your reply!

I have modify two places, and the www domain works.

1. deleted the code below in includes/common.php
` //Removing www. as it effects SEO and updating Config
$wwwcheck = preg_match('/:\/\/www\./',$baseurl,$matches);
if(count($matches)>0) {
        $baseurl = preg_replace('/:\/\/www\./','://',$baseurl);     
}  `

2. deleted the code below in includes/classes/ClipBucket.class.php
` //Get Current Page and Redirects it to without www.
//$pages->redirectOrig();`

But I don't know why ClipBucket removing 'www.'? I guess it should be have reasons.

**Comment by ThejeswarReddy** [comment]
or how about htaccess redirection?
