### ISSUE TITLE
Step 4 install

### ISSUE THREAD

**Issue by alexsandro-12** [arslancb/clipbucket#410]
Fica carregando para sempre quando clicar em próximo

**Comment by alexsandro-12** [comment]
alexs123.5gbfree.com

**Comment by MacWarrior** [comment]
Hi, 
Can you provide a screenshot with the page and the browser console errors ?

**Comment by alexsandro-12** [comment]
Já consegui arrumar

**Comment by MacWarrior** [comment]
Ok, so you can close this issue ? 👍

**Comment by alexsandro-12** [comment]
Sim , obrigado pelo suporte , uma pergunta onde consigo plugins para comprar ?

**Comment by MacWarrior** [comment]
You should check the official website : https://clipbucket.com/
