### ISSUE TITLE
Collapse Category Checkboxes does not save

### ISSUE THREAD

**Issue by adam1000018** [arslancb/clipbucket#411]
![collapse categories](https://user-images.githubusercontent.com/20660819/32908448-e4dde0fe-cb03-11e7-9d26-9e31f4caf282.jpg)

In admin panel -> Website Configuration, Collapse Category Checkboxes does not save.
After we slides to Yes and update, it slides back to No.

**Comment by MacWarrior** [comment]
Hi,

There's a missing config : show_collapsed_checkboxes
To fix it, execute this request on your DB : 
`INSERT INTO `{tbl_prefix}config`(`name`, `value`) VALUES ('show_collapsed_checkboxes', '0');`
=> Don't forget to change {tbl_prefix} with your prefix

**Comment by adam1000018** [comment]
Thank you for help. Now it saves. But there is bug with this collapsed categories. Only shows main categories. When I mark them, subcategories don't show. Maybe you have solution for that too.
One more time thank you for your time. Cheers

**Comment by MacWarrior** [comment]
Hi, 

See this commit for fix : 
https://github.com/MacWarrior/clipbucket/commit/de7d51c79255495c83300f6f4f243ca250f80487

**Comment by adam1000018** [comment]
Hi. Thank you for your help. I've tried to applly that but... I probably messed something :) I only get this visible button next to main categories, but when I try to click it nothing happens. If you tested this please let me know if this work for you. Cheers.

**Comment by MacWarrior** [comment]
Hi,

Did you correctly replace /js/functions.min.js ?
Please check your browser console, if you get some error about $.browser.msie it means you didn't update the file correctly OR you must clean your browser cache

**Comment by adam1000018** [comment]
Sorry. My bad. I did it again and everything's working fine.
Great thanks to you man. You are awsome.

**Comment by spirogg** [comment]
@MacWarrior
I see you forked this. Is all you correction on your fork. Do you feel good about anyone to use your download from fork to install CB ? Since your probably the only one who has been keeping tabs on fixing solutions other than CB team. ? Are your fork up to date with CB changes and your own fixes too included. Maybe I download from your fork and try it again.

**Comment by MacWarrior** [comment]
@Spirogg : Hi, all my work is on my fork ; feel free to use it but keep in mind that I have done many modifications (Not only fixes). 
I use it as a private streaming service so it's stable enough for me ; you may keep an eye on it if you want to use it as a public service.
I keep it up to date regulary.
If you want to test/use my fork, don't hesitate so create issues (If needed ;) ), I'll do my best to fix what needs to be

**Comment by adam1000018** [comment]
Hi. @MacWarrior
In upload area for "Upload File" and "Embed Code" it works fine, I can expand subcategories.
But for "Remote Upload" I still get only this visible "glyphicon-chevron-down" beside main categorries,  when I click it nothing happens, it don't expand subcategorries.
If you could check if it works the same on your website, or give some tips how to fix that, I would be grateful. Thank you for your time. Cheers :)

**Comment by MacWarrior** [comment]
Hi,
It seems to be working well on my repo _(Or I misunderstood something)_ : 
![capture](https://user-images.githubusercontent.com/200590/41929606-ebf07586-7978-11e8-8a5f-331e7255c26a.PNG)

**Comment by adam1000018** [comment]
Hi. @MacWarrior. Thank you for such quick response. Sorry for my english.
Is your screenshot for "Remote upload"?:
![1](https://user-images.githubusercontent.com/20660819/41934214-6672e05c-7986-11e8-9315-264dcf88551c.png)
![2](https://user-images.githubusercontent.com/20660819/41934215-6696b540-7986-11e8-92df-79c6c71c5fd9.png)

When i paste youtube url and click "grab from youtube" I can't expand categories.

For "file upload" and "embed code" everything is ok.

**Comment by MacWarrior** [comment]
Hi, 

Please check my last commit ; but I'm absolutely not sure it will be compatible with original CB code

**Comment by adam1000018** [comment]
Hi. Now it's working for remote upload too :) Great thanks for your time.
Just that glyphicon it shows in another way than before - after we expand category it should be up, but it stays down. Beside that everything works excelent.
