### ISSUE TITLE
4th subcategories in category menu on Videos Page not working

### ISSUE THREAD

**Issue by adam1000018** [arslancb/clipbucket#412]
![4th sub-cat](https://user-images.githubusercontent.com/20660819/32909996-636537f2-cb08-11e7-83f8-70d6cbd94344.jpg)

When we hit 4th subcategory on Videos Page nothing happens. There is no link inside.

**Comment by MacWarrior** [comment]
Hi, 
The url was not specified in the template ; see this commit to fix it : 
https://github.com/MacWarrior/clipbucket/commit/aed9e0258d4d86697e108a0af7c8a59d929bc6e7

PS : This part should definitely be refactored, there's a hardcoded limit to 4 sublevels categories

**Comment by adam1000018** [comment]
Working fine now. Thank you for your help.
