### ISSUE TITLE
video embedding feature stopped working

### ISSUE THREAD

**Issue by Azicoly** [arslancb/clipbucket#415]
Hello.. I was referred by my host to seek help from you guys as you people are the ones involved creation of clipbucket..
I used to embed videos from youtube on my clipbucket site before from the upload.php page ..but all of a sudden it just stopped working.. It was not even giving any error.. When i clicked the upload button it wouldn't load or give any error and will not upload even after filling all the necessary forms..
Please can you help by giving the cause of this so i can fix it.. Thanks..
Waiting for your response in anticipation

**Comment by spirogg** [comment]
did your host change php to different ( example php5.6 to php7 ? ) di you check your key from google api to make sure they didnt ban you or it didn't change ?

**Comment by Azicoly** [comment]
I have long gone fix this..thanks

**Comment by Azicoly** [comment]
Please help.
There is only one meta description and meta keywords for all pages.
I mean the keywords and description one has added at the website
configuration is what is showing for all pages.
For example if i open watch.php?v=jHrasf the meta content and keywords
should be different from another video's link.
but i noticed clipbucket is built to show thasme keyword and meta content
for all pages which is not a good seo practice.
Please where do i edit in the script to make my pages have different meta
keywords and meta content? Thanks
