### ISSUE TITLE
error 500 on admin area after install

### ISSUE THREAD

**Issue by andreicociuba** [arslancb/clipbucket#419]
I have set up an ubuntu 17.10 server with nextcloud and i figured it would be great to also install clipbucket

everything worked absolutely marvellous during installation, but after trying to log into the admin area i get a blank page and the chrome console reports error 500 returned from server.

the credentials prompt displays properly, but after entering credentials this issue occurs.

i have apache + php7 with mysql, and i spent 3 hours trying various php and apache logging options to no further resolution of the problem.

permissions on the folders is as downloaded from the github page, with the modifications specified during install on certain folders.

**Comment by MacWarrior** [comment]
Hi, 
Can you return the exact php error ?

**Comment by andreicociuba** [comment]
that is the point. i couldnt find it anywhere.

apache reports just error 500, the special logfile for my ssl connections just states that the connection is now closed. and php logs with various levels of reporting show absolutely nothing i can provde to help

any ideas where i should look?

**Comment by andreicociuba** [comment]
adding 

```
if (!isset($_SERVER["HTTP_HOST"])) {
  parse_str($argv[1], $_GET);
  parse_str($argv[1], $_POST);
}
```


to the admin_area/login.php

and calling the script from the command line with no arguments provides normal html output for authentication.

calling the script from cli with username=admin&password=admin&login=true provides no output

**Comment by andreicociuba** [comment]
adding to the script 
```

error_reporting(E_ALL);
ini_set('display_errors','On');
```
 and calling from cli with appropriate arguments gives:

```
Error: [] operator not supported for strings in /raid/htdocs/clipbucket/includes/classes/errorhandler.class.php:28
Stack trace:
#0 /raid/htdocs/clipbucket/includes/classes/errorhandler.class.php(138): errorhandler->add_error('User Doesn\xE2\x80\x99t ...')
#1 /raid/htdocs/clipbucket/includes/functions.php(927): errorhandler->e('User Doesn\xE2\x80\x99t ...', 'e', NULL)
#2 /raid/htdocs/clipbucket/includes/classes/user.class.php(266): e('User Doesn\xE2\x80\x99t ...')
#3 /raid/htdocs/clipbucket/admin_area/login.php(57): userquery->login_user('admin', 'admin')
```

**Comment by andreicociuba** [comment]
@MacWarrior  so, i understand that for some reason, it thinks the user doesnt exist?

**Comment by MacWarrior** [comment]
What's your exact version of PHP ?
Have you changed anything (Except error_reporting) from original sources ?

**Comment by MacWarrior** [comment]
@andreicociuba That's seems right, but it should display the error on the page and not get that kind of error

Anyway, your error messages seems a bit shorted; can you edit your php config : 
xdebug.var_display_max_data=-1
xdebug.var_display_max_children=-1
xdebug.var_display_max_depth=-1

**Comment by andreicociuba** [comment]
i have php 7.1 and havent changed anything not reported here

**Comment by andreicociuba** [comment]
@MacWarrior unfortunately i think i cant figure out where to put those options you mentioned.

i tried in /etc/php/7.2/modes-available/xdebug.ini where i noticed that the zend extension xdebug is loaded, but the error output is the same.

however i noticed in the user class

SELECT $fields FROM ".cb_sql_table( 'users' ); 

however, in phpmyadmin i dont have any users or cb_users table. the only tables i have containing the word user are:
  | cb_user_categories | 
  | cb_user_levels | 
  | cb_user_levels_permissions|
  | cb_user_permissions |
| cb_user_permission_types | 
 
however, now its late where i live and i think i will go and catch some zzzz. ill be back tomorrow morning in about 6 hours.

**Comment by MacWarrior** [comment]
If you don't have this table, this may be the source of the problem, but it don't explain the php error.
I'm using PHP 7.0.27 (Last Debian stable release) and it works fine, this might be a PHP 7.1+ issue

EDIT : I've seen many errors like this one reporded due to PHP 7.1
As Clipbucket is only compatible with PHP 7.0.X (and lower), I recommend you to downgrade your PHP version, there must be some other things which will not work properly under this version, I presume

**Comment by andreicociuba** [comment]
i am sorry, from https://clipbucket.com/cb-install-requirements/ i understand Version = PHP 7.x or 5.6 (with alternatives set to related version). maybe i understood this in the wrong way, unfortunately, i am not an it proffesional, i only do this as a hobby and many times i am a noob.

unfortunately i am already running other php platforms such as nextcloud succesfully integrated into my routine and habits, and my family members regularly use them too.

i don't have neither the time nor the expertise to run or maintain separate versions of php. i also dont want to deal with any potential issues from downgrading. unfortunately, my "users" dont appreciate the work that maintaining a server is for a noob like me, and i have to actually go to work to pay the extra electricity bill for a 10 year old server.

Thank you kindly for your quick responses, i am sorry for wasting our time.

**Comment by MacWarrior** [comment]
Hi, you're right, documentation should be updated (Or code)

I understand your case but I'm not an official and I just tried to figure out what the problem is on my free time ; don't take my responses too personnaly ;)

I will try to set up a 7.1.X environnement to upgrade what needs to be upgraded but I cannot guarantee when and if my modification will be fully compatible with ClipBucket master repo (Working on a fork since a long time)

**Comment by andreicociuba** [comment]
@MacWarrior i understand how collaborative projects work, i wasnt trying to be mean.

We are both doing this in our free time, my argument goes both ways. I can't spend more time and energy on this, and i understand that neither can you.

I still don't actually know if this is an issue in my own setup, or something else. i can't put the blame anywhere specifically.

this project has just gone way down my priorities list, but i will update here any findings if i get back to dealing with it

**Comment by Awais-cb** [comment]
@andreicociuba apologies for inconvenience currently Clipbucket is supported on php5.6 and 7.0.We have updated the requirements.

**Comment by MacWarrior** [comment]
Hi
@andreicociuba  : I've been testing on Ubundu 17.10.1 (x64) with PHP 7.1.15 without that kind of error
What version did you used ?

**Comment by pavan1905** [comment]
![1234](https://user-images.githubusercontent.com/22028155/51860763-819ea080-2360-11e9-8b97-c31124c9ded2.png)

anybody help with this error???

**Comment by dawsonlife** [comment]
I have the same error @pavan1905

**Comment by mesouug** [comment]
In case if someone still facing similar issue. If you have mysql >= 5.7 you need to change `sql_mode`
Like this:
```
[mysqld]
sql_mode = 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
```

Explanation: without this change during database structure provision not all tables are created. More info in google about that change.
