### ISSUE TITLE
Login button IE11 2.8.1

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#42]
This happens only on IE11. Windows 8.1
Tested also with Chrome and it's fine.

![login-ie11](https://cloud.githubusercontent.com/assets/19185161/15010471/d6505af4-11f4-11e6-8fc5-dcb0034d325c.PNG)

**Comment by pcmcis** [comment]
Hi,

On 2.8.1 RC1 the problem is fixed. Thanks!
![login-ie11f](https://cloud.githubusercontent.com/assets/19185161/15357181/f136a938-1d05-11e6-8ca4-cde110935e17.JPG)

**Comment by fahad-cb** [comment]
fixed
