### ISSUE TITLE
Mass Uploader - uploads only the first video in the list ...

### ISSUE THREAD

**Issue by mj1985** [arslancb/clipbucket#426]
... even when I select second one. When I select all with the "Select/Deselect" checkbox, the second got added, too.

Version: 4.0 latest stable
![screenshot-2018-3-12 mass uploader - clipbucket v4 0 stable](https://user-images.githubusercontent.com/5830093/37306028-b9ec1c88-2636-11e8-8879-331929774db6.png)

**Comment by AndrzejDopytalski** [comment]
Mass Uploader - nothing sends to me, only "error" is shown. No possibility to go back to the previous page, only "refresh"

**Comment by Awais-cb** [comment]
Only first video getting selected is fixed please Update

> upload/admin_area/styles/cb_2014/layout/mass_uploader.html

**Comment by AndrzejDopytalski** [comment]
I have loaded a new file and it still does not work.
