### ISSUE TITLE
SQL structure for installation isn't compatible with MySQL 5.7

### ISSUE THREAD

**Issue by aalonzi** [arslancb/clipbucket#428]
The MySQL dump structure for the initial installation is not compatible with MySQL 5.7 Strict mode. For example, for dates you cannot do:
`date_added` datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
but only:
`date_added` datetime NOT NULL

[structure.sql.txt](https://github.com/arslancb/clipbucket/files/1816410/structure.sql.txt)

**Comment by dmaclip** [comment]
mariabb strict mode also has issues fwiw.
had not bothered to see what table(s) causing issue just disabled strict mode on my end.
