### ISSUE TITLE
No video found whatever content I upload to my website

### ISSUE THREAD

**Issue by JuneZhao** [arslancb/clipbucket#429]
I installed LAMP and configure all things with this Clipbucket but it looks like data is not persistent, when I upload the video it works fine reporting 100% complete but the video doesnt appear anywhere , when i checked inside the VM I uploaded using fyp to /var/www/html/files/videos still not able to see it from web?

**Comment by dmaclip** [comment]
upload to mass upload folder then in admin panel open videos-mass uploader and click it set category/tags/etc and see if it works
just plain ftp to videos folder does not update database, trigger ffmpeg conversion,etc

**Comment by JuneZhao** [comment]
@dmaclip I did what you instructed me but it looks like it only appears under Mass Uploader tab in admin_area I still cant see it anywhere from my homage.
![image](https://user-images.githubusercontent.com/1699200/37941167-620f4ed0-319f-11e8-8b19-e53dd5601aa3.png)

**Comment by dmaclip** [comment]
click it, edit the category, tags, etc  then click mass upload videos.
it should then pass off to fmpeg to process.
you do have ffmpeg and req'd modules installed right?
basically everything needs to be processed before it show on site. just uploading crap using ftp do

**Comment by JuneZhao** [comment]
@dmaclip  I did what you have suggested but nothing works, it stay as it was. 
Below is my ffmpeg:
 ffmpeg
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
/home/junecb# whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz

![image](https://user-images.githubusercontent.com/1699200/38003388-e98c2322-3269-11e8-836d-86675ccb87d5.png)

The thing is when I click the video and edit the tag and category and click  the button Mass upload videos Now it succeed but nothing changes.
![image](https://user-images.githubusercontent.com/1699200/38003439-1e4732be-326a-11e8-8976-191c2130e571.png)

**Comment by dmaclip** [comment]
not had mush experience with ububtu but those multiple ffmpeg locations seem odd.
iirc ubuntu calls it libav
how was ffmpeg installed?
also, perhaps this is better suited for discourse forums and not github issues page
also did you edit CB setting to point to correct location?
hard to really say w./o looking atr it

**Comment by dmaclip** [comment]
also what version ubuntu? I can try building a vm to see what happens on my end

**Comment by JuneZhao** [comment]
@dmaclip  I did verify all library that it referred as from webpage, it definitely exist in my serer, it is Ubuntu 16.04, I followed some suggestion here  but still not luck to see my video
https://stackoverflow.com/questions/49441094/clipbucket-no-video-found-though-upload-succeed-and-i-have-mp4-file-under-var

**Comment by dmaclip** [comment]
use this topic now
https://discourse.clipbucket.com/t/placeholder-helping-someone-with-ununtu-install/2824
building vps now.
in discourse topic please give info on how server itself was built/setup

**Comment by JuneZhao** [comment]
@dmaclip I tried to reply you there but both Google authentication and twitter one failed, twitter one logged in but never send email to my mailbox to authenticate.

To anwer you  i installed mysql and php through apt-get intall and mysql

**Comment by JuneZhao** [comment]
@dmaclip same for ffmpeg apt-get install ffmpeg

**Comment by dmaclip** [comment]
ok got vps built and ffmpeg installed using apt-get install ffmpeg
but MY install shows different then yours
# which ffmpeg
/usr/bin/ffmpeg

this makes me wonder what is going on at your install regarding ffmpeg.
I have also installed gpac (mp4box), mplayer, imagmagick from apt-get. did you?

I am going to create the user and database needed for clipbucket today as I suspect thats where your issue lays. 
gonna take some time as I have not used pure cmd line to install sites and databases in long time. really got more experience with centos, but will do what i can.

**Comment by dmaclip** [comment]
ok got vps built and ffmpeg installed using apt-get install ffmpeg
but MY install shows different then yours

which ffmpeg
/usr/bin/ffmpeg

this makes me wonder what is going on at your install regarding ffmpeg.
I have also installed gpac (mp4box), mplayer, imagmagick from apt-get. did you?

I am going to create the user and database needed for clipbucket today as I suspect thats where your issue lays. 
gonna take some time as I have not used pure cmd line to install sites and databases in long time. really got more experience with centos, but will do what i can.

edit: I just noticed you ran whereis and not which, post the output of which ffmpeg please

**Comment by dmaclip** [comment]
and I see the topic I created to get a SUPPORT issue off from github ISSUE page was deleted.
sort of stupid as this is not a code issue but a specific user issue. 
whatever,

**Comment by dmaclip** [comment]
efore I waste a lot of hours on this I need to know, is there specific reason you used ubuntu server and not centos using centminmod or similar?

**Comment by dmaclip** [comment]
looks to me like latest revisions don't include option to turn on quik conversion (start ffmpeg as soon as vid uploaded) or use crons. files issue about crons.

**Comment by spirogg** [comment]
Did you set crons up anyway to see if that works. Even though no option ?

**Comment by dmaclip** [comment]
not yet going to try to later today

**Comment by spirogg** [comment]
@JuneZhao  read this https://github.com/arslancb/clipbucket/issues/431

**Comment by dmaclip** [comment]
while I think the cron/instant is an issue I think the particular issue of user/group permission based.
of conversion fails vid still gets handed off to database and just lists failed, that doesn't happen here.
thinking has something to do with how ubuntu 1604 handles root and sudo users.
going to install free webpanel and try from there to rule out permissions error

**Comment by JuneZhao** [comment]
@dmaclip @spirogg Thanks for your time and effort on this , to answer your question.
I utilized ubuntu is purely because of my kubernetes cluster is built on ubnutu and i want to utilize the agent to setup an video system and that is where it leads me ,

Regarding the conversion one I believe it is not relevant to the issue ,see below pic:
![image](https://user-images.githubusercontent.com/1699200/38158576-de879454-34c9-11e8-9ac3-000b21ebd8cf.png)
Previsouly there are logs when I click those number but most of them in failed state i deleted them.

Regarding ffmpeg i think we are the same directory i dont see any difference

/usr/bin/ffmpeg

**Comment by dmaclip** [comment]
gonna rebuild vps today, please post exactly how you built your server (can email me support(AT)macleodweb.net subject line ubuntu server) if you want so we can stop using issue tracking for support.
thinking more and more this is a usergroup/permissions issues, need to nail it down. once built up can test more.
just really dislike ubuntu servers LOL

**Comment by dmaclip** [comment]
not having ANY luck getting ubuntu to work.
can you try a conversion and then post the full log?
may need to delete other logs that say processing, want to see if can garner any info from log from failed one

also, is there anyway to run a centos container with ubuntu host? I am not well versed in kubernetes cluster stuff so don't know.
reason I ask is because using centmin mod (pure cmd line driven, low overhead) seems to work better

**Comment by JuneZhao** [comment]
@dmaclip  Ubuntu is the one that I want to have it work.

I tried to upload a new video again, but it never generated log 

![image](https://user-images.githubusercontent.com/1699200/38227423-af618130-3730-11e8-91ac-a6048d69cbd1.png)


![image](https://user-images.githubusercontent.com/1699200/38227443-cbe57f96-3730-11e8-8bba-5e41fac86c47.png)


It kind of back to where I was initially

**Comment by JuneZhao** [comment]
http://junecb.eastasia.cloudapp.azure.com/admin_area/phpinfo.php here is mine php info @dmaclip

**Comment by JuneZhao** [comment]
@dmaclip I found my apache2 run with user www-data, I uploaded one wmv but it didnt exist 

drwxr-xr-x 2 www-data www-data 4096 Apr  3 03:00 03

The enviable says this

# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data

It is under:
/etc/apache2/envvars

**Comment by JuneZhao** [comment]
my process list www-data    908  0.0  0.1 422372 17080 ?        S    02:07   0:00 /usr/sbin/apache2 -k start
www-data    909  0.0  0.1 424540 19700 ?        S    02:07   0:00 /usr/sbin/apache2 -k start
www-data    910  0.0  0.1 424624 21288 ?        S    02:07   0:01 /usr/sbin/apache2 -k start
www-data    912  0.0  0.1 424568 20280 ?        S    02:07   0:00 /usr/sbin/apache2 -k start
www-data   1879  0.0  0.2 808184 37224 ?        S    01:02   0:00 /usr/sbin/apache2 -k start
www-data   1881  0.0  0.1 498284 22448 ?        S    01:02   0:00 /usr/sbin/apache2 -k start
www-data   1882  0.0  0.1 424500 20176 ?        S    01:02   0:00 /usr/sbin/apache2 -k start
www-data   1883  0.0  0.2 734392 36788 ?        S    01:02   0:00 /usr/sbin/apache2 -k start
www-data   1884  0.0  0.1 424500 20224 ?        S    01:02   0:00 /usr/sbin/apache2 -k start
www-data   1896  0.0  0.0 379744  8732 ?        S    01:02   0:00 php-fpm: pool www
www-data   1897  0.0  0.0 379744  8732 ?        S    01:02   0:00 php-fpm: pool www
www-data   7347  0.0  0.3 400444 54768 ?        S    01:45   0:02 apache2 -DFOREGROUND
www-data   8845  0.0  0.1 424536 19936 ?        S    02:42   0:00 /usr/sbin/apache2 -k start
www-data  14877  0.0  0.2 320612 47420 ?        S    01:11   0:00 apache2 -DFOREGROUND
www-data  14878  0.0  0.0 315540  7632 ?        S    01:11   0:00 apache2 -DFOREGROUND
www-data  14879  0.0  0.3 395748 55280 ?        S    01:11   0:00 apache2 -DFOREGROUND
www-data  14881  0.0  0.0 315532  7632 ?        S    01:11   0:00 apache2 -DFOREGROUND
www-data  14882  0.0  0.0 315540  7632 ?        S    01:11   0:00 apache2 -DFOREGROUND
www-data  20661  0.0  0.0 315532  7632 ?        S    02:09   0:00 apache2 -DFOREGROUND

**Comment by dmaclip** [comment]
I spent days trying to get ubuntu 16.04 to work and t never did. really seeemed like a chown/chmod issue.
fired up a centos vps with centminmod and worked immediately.
you stated 

> kubernetes cluster is built on ubnutu and i want to utilize the agent 

but from my limited understanding of kubernetes centos does work with the host agent. am I wrong there? I have very little knowledge of that process.

**Comment by JuneZhao** [comment]
@dmaclip, the azure k8s cluster is built automatically so i have lots of workload there and that is why I want to utilize the agent and I wish to solve it  in current configuration

**Comment by dmaclip** [comment]
ok will rebuild ubuntu again
some questions.
did you enable root ssh and use that or create sudo user for the site?
can you post outputs of php -v and php -m please?
also th elink you provided for php info does not ork. want to make sure compiled with needed modules

so I cannot tell what php version you are using

**Comment by JuneZhao** [comment]
@dmaclip Thanks for your time and effort.
To answer your questions:
1.I didnt enaable root sshe for the server, I did create the site with root permission though.
2. Here you go:
root@k8s-agent-ECC3CC6B-0:/home/zjune# php -v
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies


root@k8s-agent-ECC3CC6B-0:/home/zjune# php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache



3. the link should work now, I started the server just now,

**Comment by MacWarrior** [comment]
@JuneZhao : Are you serious ?
`<script src="https://authedmine.com/lib/authedmine.min.js"></script>`

If you want to be helped, disable this crap...

**Comment by dmaclip** [comment]
what does which MP4Box , which mplayer , and which mediainfo show?
and along with item @macwarrior mentioned to view your php page need login rights so....not much help

**Comment by JuneZhao** [comment]
@MacWarrior @dmaclip  I have configured if you dont want that you can disable it. if you dont wish to help please close the issue and move Ubuntu from your list  to be working.

**Comment by JuneZhao** [comment]
@dmaclip here you go
zjune@k8s-agent-ECC3CC6B-0:~$ which MP4Box
/usr/local/bin/MP4Box
zjune@k8s-agent-ECC3CC6B-0:~$ which mplayer
/usr/local/bin/mplayer
zjune@k8s-agent-ECC3CC6B-0:~$ which mediainfo
/usr/bin/mediainfo

**Comment by dmaclip** [comment]
those look right, figured would check to be safe,
hope to reload ubuntu today.
just life keeps getting in the way LOL

you did disable strict mode on sql server right?
irc on ubuntu have to create /etc/mysql/conf.d/strict_mode.cnf
and add
```
[mysqld]
sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
to it

**Comment by JuneZhao** [comment]
@dmaclip I am not sure on strict mode, here is what I performed
Hi there this issue comes when you try to install clipbucket with sql strict mode on. Turn off sql_strict mode and try reinstalling clipbucket everything will be fine after that even videos will start appearing too.

Here is how you can turn off sql strict mode. go to phpmyadmin click on sql tab and run this query

set global sql_mode=""
from this link:
https://stackoverflow.com/questions/49441094/clipbucket-no-video-found-though-upload-succeed-and-i-have-mp4-file-under-var

I have added the file.

**Comment by dmaclip** [comment]
yeah I never had luck with that on ubuntu for other things (and on centos it did work placed in my.cnf (never stuck when running as query) ....go figure...) which is why I wondered if trying strict_mode.cnf and server restart would work.
sadly still have not had chance to revuild vps as I had hoped to do yesterday

**Comment by dmaclip** [comment]
rebuilt vps 3 times yesterday tried multiple things with 16.04 (including using a hosting panel) nothing worked.
15.x series worked though.
I give up on 16.04 something is not right there.

**Comment by JuneZhao** [comment]
@dmaclip  thanks for your time and effort let us close this and mark it is not working on Ubuntu 16.04 anyway

**Comment by dmaclip** [comment]
sorry I tired, cannot tell if kernel issue/template isue on openvz vps or not.
nothing seems to make any sense as to why its not working except either directory permissions or php-cli in 16.04 default php versions.
no matter what I tried was not able to get it working.
and yet been using it on centos from v5.2 onwards to latest 7.x series LOL

**Comment by MacWarrior** [comment]
Hi all, 

I don't know how you installed your Debian 16.04 but I made it works on first try.

Here are my installation scripts : 
- For [Debian 16.04](https://github.com/MacWarrior/clipbucket-5.0/blob/master/utils/install_ubuntu16.04.sh)
=> Make sure to use the correct audio codec
- For [Debian 17.10.1](https://github.com/MacWarrior/clipbucket-5.0/blob/master/utils/install_ubuntu17.10.sh)

**Comment by JuneZhao** [comment]
@dmaclip @MacWarrior  Finally I got it working following the instructions here:https://mtlynch.io/ansible-role-clipbucket/

**Comment by lucassica** [comment]
can see the videos after uploading
