### ISSUE TITLE
sound ico in player IE11 2.8.1

### ISSUE THREAD

**Issue by pcmcis** [arslancb/clipbucket#43]
The sound icon is not displayed correctly using IE11.
There is no problem with google chrome.
![sound-ico1-ie11](https://cloud.githubusercontent.com/assets/19185161/15011354/006d89f6-11fa-11e6-8615-8ece6dafac39.PNG)
![sound-ico-ie11](https://cloud.githubusercontent.com/assets/19185161/15011356/029b5df2-11fa-11e6-823e-0bd0140f5938.PNG)

**Comment by pcmcis** [comment]
Hi,
It looks ok in today's 2.8.1 RC1 release. Thanks!

![sound-ico-ie11f](https://cloud.githubusercontent.com/assets/19185161/15357082/5c8c85fa-1d05-11e6-8bb6-19fc698e0ab3.JPG)

**Comment by fahad-cb** [comment]
Fixed
