### ISSUE TITLE
recapcha not working

### ISSUE THREAD

**Issue by Blisk** [arslancb/clipbucket#432]
In latest version of clipbucket 4 recaptcha doesn't work.
I have inserted public and private keys but recaptcha doesn't show up

**Comment by MacWarrior** [comment]
Hi, if I'm right, captcha is disabled since this commit : 
https://github.com/arslancb/clipbucket/commit/ee8fe8bace31662c5777ae78ca381ee2158a3cae

**Comment by Blisk** [comment]
So how can we protect now scripts to login attack?

**Comment by spirogg** [comment]
I think CB no care about the guys whom make all the bug reports for years . They are now big shots and we are like dogs. Report report and they never reply or give us something good for script, since we are part of CB for years and waste time report bugs   then they fix and sell script to there 
This BS. We need to stop report bugs and see how they find all the bugs themselves.

**Comment by Blisk** [comment]
Anyone??

**Comment by fahad-cb** [comment]
We are looking into this, @Blisk have to wait till next release 
Thank You

**Comment by Awais-cb** [comment]
@Blisk updated Recaptcha plugin has been added to source you can update your Clipbucket and use the new one if older one isn't working.

**Comment by Blisk** [comment]
Hi
Thank you for plugin but doesn't work, no recaptcha at login page or register page

**Comment by Awais-cb** [comment]
it will work first you need to register your domain here
https://www.google.com/recaptcha/admin
and get the site key and site secret pass them into plugins configurations and it will start appearing.Please make sure to get choose the type of reCAPTCHA `reCAPTCHA V2`
you can check this link for demo
http://demo.clipbucket.com/free/signup.php

**Comment by Blisk** [comment]
yes thank you I have registered and get both keys private and public key added in file install_recaptcha
but still nothing

**Comment by Awais-cb** [comment]
you don't have to add it in any file i think you are doing it wrong let me show you a screenshot.Plugin name is is Recaptcha V2 and its installation file is `install_recaptcha_v2` and you don't have to do anything with it.
after installation of Recaptcha V2 you will see this menu 
[prntscr.com/j4sneo](https://prntscr.com/j4sneo)
and you have to add key and secret here from admin area.
if you are unable to see `Recaptcha V2` in plugin's list try updating you source code

**Comment by Blisk** [comment]
Thank you. Yes I missed that in admin page, before I added those key in file.
Now recaptcha works on register page.
How to add recaptcha to login page too, to prevent brute force attack with disctionary scripts?

**Comment by Blisk** [comment]
Still nothing new on this problem??
