### ISSUE TITLE
Uploading photos doesn't work

### ISSUE THREAD

**Issue by Blisk** [arslancb/clipbucket#434]
I have clipbucket v4 installed, now uploading videos finally works withouth problems, but still can not upload any picture at all, jpg or png nothing works.
Button save details stays greyed out.
I checked all permissions and everything and all is ok. Imagick is installed an works.
What can be wrong?
![2018-04-16 10_46_17-photo upload -videos google chrome](https://user-images.githubusercontent.com/2773050/38799016-8e3dc3d2-4163-11e8-9c2a-c0cfd6865343.png)

**Comment by Blisk** [comment]
Any help regarding uploading photos?

**Comment by winnipeg21** [comment]
having the same issue

**Comment by winnipeg21** [comment]
Fixed this issue by using the github version of ClipBucket. Still having image loading problems tho :/

**Comment by Blisk** [comment]
check permission of folders. After uploading github verison it works uploading photos

**Comment by janusz66** [comment]
Installed trough Softoculus and all work
