### ISSUE TITLE
Audio Uploading

### ISSUE THREAD

**Issue by onyedika135** [arslancb/clipbucket#435]
Please can any one who knows the Clipbucket core codes add Audio section to the project.
This project will be more balanced if it has Audio section.
Grate Job.

**Comment by Blisk** [comment]
yes that will be really good, because now I need to convert it to video format.

**Comment by onyedika135** [comment]
So when do you plan to add the feature?

**Comment by onyedika135** [comment]
So when do you plan to add the feature?
