### ISSUE TITLE
Can't log in after clean install > Downloaded source from clipbucket.com

### ISSUE THREAD

**Issue by siniztr** [arslancb/clipbucket#444]
Good day,
First off, your website needs to get fixed, I tried the discourse, never received email to confirm registration. 
Second off, your installation documentation file that comes with the package from the website is SERIOUSLY out of date. In the installation document it is pointing to files that simply don't exist, or do exist but have different names. I got through the installation through guesswork and prior knowledge of php and linux. 

Did a clean install on a Ubuntu box in VMWare Workstation. First off, when importing the SQL file (I used cb_new_install.sql) I get an error when installing, due to the first line in the file -- $Id$. Removed the first 9 lines which contained information on the dump, and proceeded with the import. I get an error (I didn't note down what went wrong though), but most, if not all, of the tables for the initial install are there. I got to the check for the prerequisite scan, the PHPShield is not working, The latest version of the PHPShield is 5.3, which of course doesn't work on PHP7.x. Continued on to the administrator account information. After installation is complete, I go to the admin section and try to log in, no such user exists. Go to the front end, same error. Using both admin/admin as prescribed in the installation documentation as well as the information that I filled in. 

Check the database, there is no cb_users table. I saw someone else on the discourse with the same issue.

**Comment by siniztr** [comment]
Something I forgot to mention:
When I try to login to the admin area, after I try logging in, I get a white screen. When I check the apache2 error.log file, I get this:

> client **ip hidden for security**:55349] script '/var/www/html/404.php' not found or unable to stat, referer: **address hidden for security**/clipbucket/admin_area/login.php

**Comment by siniztr** [comment]
Before the removal of the first 9 lines:

Static analysis:

5 errors were found during analysis.

    Unexpected character. (near "$" at position 0)
    Unexpected character. (near "$" at position 3)
    Unexpected beginning of statement. (near "$" at position 0)
    Unexpected beginning of statement. (near "Id" at position 1)
    Unexpected beginning of statement. (near "$" at position 3)

SQL query:

$Id$ -- phpMyAdmin SQL Dump -- version 3.2.0.1 -- http://www.phpmyadmin.net -- -- Host: localhost -- Generation Time: Nov 04, 2009 at 12:03 PM -- Server version: 5.1.36 -- PHP Version: 5.3.0 SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO" 

Once I remove this section from the file, I get the following error:
SQL query:

--
-- Dumping data for table `ads_data`
--

INSERT INTO `ads_data` (`ad_id`, `ad_name`, `ad_code`, `ad_placement`, `ad_category`, `ad_status`, `ad_impressions`, `date_added`) VALUES
(1, 'Ad Box of 300 x 250', '&lt;img src=&quot;http://www.lipsum.com/images/banners/black_300x250.gif&quot;&gt;', 'ad_300x250', 0, '1', 1056, '0000-00-00 00:00:00'),
(9, '336x280', '&lt;img src=&quot;http://www.lipsum.com/images/banners/black_336x280.gif&quot;&gt;', '336x280', 0, '1', 33, '0000-00-00 00:00:00'),
(2, 'Adbox 160x600', '<div style="border:2px #333333 solid; color:#53baff; font-size:20px; font-family:Geneva, Arial, Helvetica, sans-serif; font-weight:bold; width:160px; height:600px; vertical-align:middle" align="center">\r\n	Ad Box 160 x 600\r\n</div>', 'ad_160x600', 0, '1', 571, '0000-00-00 00:00:00'),
(3, 'Adbox 468x60', '&lt;div style=''border:2px #333333 solid; color:#53baff; font-size:20px; font-family:Geneva, Arial, Helvetica, sans-serif; font-weight:bold; width:468px; height:60px; [...]

MySQL said: Documentation
#1062 - Duplicate entry '1' for key 'PRIMARY'

**Comment by siniztr** [comment]
After doing the entire install again (that is how I was able to post the above listed errors) I import the database from the file, then proceed to the installation script. When I get to the database information, I fill in the same information contained in dbconnect.php and leave out the cb_ so it can use the imformation imported. Now when I log in, both in the front end as well as the admin area, after entering the login information it bounces me back to the same screen. In the apache2 error logs I still see the same
 script '/var/www/html/404.php' not found or unable to stat, error.

**Comment by MacWarrior** [comment]
Hi, 

I think you missunderstood the way installation must be done : simply upload all files and then go to yourwebsite.com/cb_install/

If your PHP/Apache2/MySQL environment is well configured, all should be done without this kind of error

Please check my [Ubuntu installation script](https://github.com/MacWarrior/clipbucket-5.0/blob/master/utils/install_ubuntu17.10.sh) if you have some configurations issues

**Comment by siniztr** [comment]
Please have a look in the docs folder > installation.html. I followed these installations. If these instructions are not accurate, I would recommend either updating or removing.

But, ok. I did do the /cb_install/ as well (without the sql import) and that puts me in the first issue I mentioned in my first message, there is no cb_users (or users) and I can't login. Also, 404.php error

**Comment by siniztr** [comment]
I did as you asked. I did a clean install (again, doing nothing but uploading the files to the server and then doing /cb_install/ and going through all of the steps. I am still not able to log in.
Both with back and front end. 

Maybe it is because I am trying to install in a subfolder (https://youtube.josephsprivate.space/clipbucket... could this be causing the script to not run correctly? Reason for this is I am currently testing a few different packages with a partner for a future project, and we want to know which to use. So I have set up youPHPtube as main script, then a netflix clone script under /netflix and clipbucket under /clipbucket. 

If it is better, I can start up another Linux vhost and do the entire installation (incl. prerequisites) and test it solo.

**Comment by siniztr** [comment]
Here is an overview of the database tables. In the screenshot I didn't get all of them, but as you can see, no cb_users so the site can't access the table. 
![clipbucket_phpmyadmin](https://user-images.githubusercontent.com/22732606/42288986-6f56ff36-7fbd-11e8-84ef-a123aba79b67.jpg)

**Comment by MacWarrior** [comment]
Hi, 

Did you get this interface while installing ?
![capture](https://user-images.githubusercontent.com/200590/42408952-3c0dfa2c-81d3-11e8-88e4-07492f6736e2.PNG)

**Comment by siniztr** [comment]
Yeah I get to that part. I get all the way to finish, but when I try to log in with the made username and password I can't log in. 
**EDIT**
I can now get past the logging in, using the version 5.1 from github, but under no circumstance can I upload videos. I followed the instructions to the t, even used your script. This is a different problem though, so should I make a new ticket?

**Comment by MacWarrior** [comment]
Hi,
I don't know why it works on my 5.1 but not on official, I don't remember having done some debug on this part

Yes, create a new ticket on my repo please, but I think this is a server configuration issue

**Comment by spirogg** [comment]
I tried installing with php 7.0.30 but will not work, so i revert to php 5.6 and everything works for install

**Comment by zaincb** [comment]
Just in your database set your sql_mode : 
`SET GLOBAL sql_mode="";`
![sql](https://user-images.githubusercontent.com/55781706/68385745-439a9c80-017c-11ea-845e-5bad61b21754.png)

OUTPUT: 
![output](https://user-images.githubusercontent.com/55781706/68385765-4eedc800-017c-11ea-86a7-bdd2ff4d67e5.png)

Then do the installation again on that database.

And if the issue remains then let me know :).

Thanks ;)
