### ISSUE TITLE
MySQL strict mode issue + Type error in error handling code

### ISSUE THREAD

**Issue by ghost** [arslancb/clipbucket#445]
After finishing the installation workflow, I tried to log into the admin panel but could not. I was getting a 500 from apache. After enabling display_errors I was able to see the following error:

`Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/html/includes/classes/errorhandler.class.php:28 Stack trace: #0 /var/www/html/includes/classes/errorhandler.class.php(138): errorhandler->add_error('User Doesn\xE2\x80\x99t ...') #1 /var/www/html/includes/functions.php(927): errorhandler->e('User Doesn\xE2\x80\x99t ...', 'e', NULL) #2 /var/www/html/includes/classes/user.class.php(266): e('User Doesn\xE2\x80\x99t ...') #3 /var/www/html/admin_area/login.php(40): userquery->login_user('admin', 'admin') #4 {main} thrown in /var/www/html/includes/classes/errorhandler.class.php on line 28`

It turns out that `includes/classes/errorhandler.class.php:66` assigns that error list to a string.

So this:

```
/**
* Function used to flush errors
*/

public function flush_error() {
	$this->error_list = '';
}
```

Should be changed to this:

```
/**
* Function used to flush errors
*/

public function flush_error() {
	$this->error_list = [];
}
```

After fixing that, I noticed I was unable to login as the admin that I created during the installation.

I checked the database and the users table was missing. I tried to execute the query to create the table as defined in structure.sql and found that the default SQL mode in MySQL 8 prevents creating "zero" dates (e.g., '0000-00-00'). This is done in both `dob` and `last_logged`. For some reason this does not bubble up to the default mysql drivers.

It might be worth adding that to the readme or as a warning on the installation page.

I assume this is related to https://github.com/arslancb/clipbucket/issues/444.

**Comment by zaincb** [comment]
Just in your database set your sql_mode : 
`SET GLOBAL sql_mode="";`
![sql](https://user-images.githubusercontent.com/55781706/68385745-439a9c80-017c-11ea-845e-5bad61b21754.png)

OUTPUT: 
![output](https://user-images.githubusercontent.com/55781706/68385765-4eedc800-017c-11ea-86a7-bdd2ff4d67e5.png)

Then do the installation again on that database.

And if the issue remains then let me know :).

Thanks ;)
