### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by xCumSlut** [arslancb/clipbucket#446]
I just installed clipbucket on my server but when i try to register a new test user it's says "Please select your category".. after that i try to do it again and select user cateory but nothing change.. same error always shown.. please help me solve this

**Comment by Awais-cb** [comment]
Which version of php you are running right now?

**Comment by xCumSlut** [comment]
7.2

**Comment by Awais-cb** [comment]
Please downgrade it to php 7.0

**Comment by xCumSlut** [comment]
ok.. i'll try

**Comment by xCumSlut** [comment]
It worked! thanks men! you're ROCK!

one more question.. can i use thumbnail from url?

**Comment by zaincb** [comment]
Hey @xCumSlut there is no option for URL .

Thanks.
