### ISSUE TITLE
what happened tpo fixing bugs on free version, we have an issue 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#449]
hi if we try to upload some videos and then we **by mistake upload a photo in the video section** the last video uploaded will show as processing and then when you try to delete it,
- it removes all videos thumbnails ??

**can you make separate field for photo uploads and remove from video the png and jpg  file types, so it will allow still photo uploads but not in video upload area**

**Comment by fahad-cb** [comment]
this issue has been fixed, what version are you using ?
