### ISSUE TITLE
submit button disabled

### ISSUE THREAD

**Issue by hassan379** [arslancb/clipbucket#450]
hello i tried everything but the submit button still disabled , the progress bar reached to 100 and then when i try to press submit button i cant because its disabled 
os : centos 7 
clipbucket 4.1 stable

**Comment by spirogg** [comment]
This means you are missing php modules.

**Comment by hassan379** [comment]
thanks i fixed the problem , i rechecked all php modules that i installed before and i discovered that some of them not installed because that the repository that i used cant find some of the packages that are necessary for php 
i reinstalled them and everything works
