### ISSUE TITLE
Max videos to convert at once not working

### ISSUE THREAD

**Issue by hassan379** [arslancb/clipbucket#452]
hello i tested today this feature on 6 videos i uploaded them at once , clipbucket convert  only the first video (if i set max videos to convert at once to 1) and after finishing the first video it converts the rest of videos together 
another thing when i upload 10 videos at once the cpu usage reach 100% even when i set max videos to convert 1 
version : 4.1 stable
os : centos 7
cpu : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 8 cores

**Comment by hassan379** [comment]
the reason of the high cpu usage , is that when someone upload 6 videos the first video will be uploaded and converted but the rest of the videos will be waitting until the first one finished 
the waiting process that clipbucket is using is infinit loop which it will take too much resources from the cpu , and the number of those infinite loops are the same as the numbers of the videos 
so when i upload 25 video at once that mean there are 25 infinite loop running and waitting for the first video which it will makes the cpu  usage 100% 
the reason of why max proccess at once only works for the first video 
the rest of videos are waitting for the first one and when the conversion unlocked fom the first one all those rest of the videos will be converted at once 
let me give example what is happening : 
consider 10 people want to enter one room but only one man allowed to enter this room , the first person entered the room and locked the door behind him and the rest are waitting in the front of the door 
and when the door open all of those people will enter to this room 
i hope to fix this issue because i tried to fix it but i couldnt done that

**Comment by hassan379** [comment]
`while(1)
                {
                        $use_crons = config('use_crons');
                        if(!$this->isLocked(PROCESSESS_AT_ONCE) || $use_crons=='yes' || !$this->set_conv_lock)`
the problem is here 
this while taking too much resources from the cpu 
when 
`!$this->isLocked(PROCESSESS_AT_ONCE) `
become true all the rest of videos will enter and started to converted at once

**Comment by MacWarrior** [comment]
Hi, 

Please check this commit : 
https://github.com/MacWarrior/clipbucket-5.0/commit/f03ddfe9c77597d65497c64cc7c8bb5444018cc2#diff-f80b3169608ce8b8d3dee7718960adc8

Just adding the sleep(5); at the end of function ClipBucket() fixes this issue ; process are now waiting but at 0% CPU most of the time

**Comment by hassan379** [comment]
it works nice one man you saved my life
