### ISSUE TITLE
Mailing list goes mad

### ISSUE THREAD

**Issue by Blisk** [arslancb/clipbucket#455]
What is wrong today with your mailing list, I get 30 emails from your mailing list and still didn't stop.
![2018-09-28 10_17_33- outlook](https://user-images.githubusercontent.com/2773050/46196695-138d9280-c308-11e8-961c-251b02ad9fdd.png)

**Comment by janusz66** [comment]
Me too. When you click on link to stop I got 404.

**Comment by aliawancb** [comment]
@Blisk @janusz66 Our team was working on changing the domain for blog and some emails were sent by mistake, the emails were stopped after a few minutes but were sent to some users from the list. I apologize for the inconvenience.
