### ISSUE TITLE
vido upload notification

### ISSUE THREAD

**Issue by janusz66** [arslancb/clipbucket#458]
User upload video, but I did not receive  notification  by e-mail. How do I fix that?. Thanks

**Comment by fahad-cb** [comment]
https://clipbucket.com/docs/knowledgebase/clipbucket-developers-documentation/#cbmail

use this method in clipbucket to send email of any kind ! 

Our team will be looking into this anyways ! 

Thank You

**Comment by janusz66** [comment]
I have very limited knowledge of the script. I noticed that I am not getting e-mail when new user register  and upload. Did I do something wrong in config?. The cbmail - user will have to fill proper form to send e-mail. Is there any way to make automated email ( registration and upload)???. Thank you. My web site http://myfunnyvideos.net

**Comment by janusz66** [comment]
Could someone tell me where to I put the cb-mail script?. In admin folder or root. Thank you

**Comment by fahad-cb** [comment]
sorry for late reply, you need to configure emails in admin section
add emails here : [http://myfunnyvideos.net/admin_area/main.php](url)
and configure here : [http://myfunnyvideos.net/admin_area/email_settings.php](url)
