### ISSUE TITLE
i have some issues with categories thumbnails

### ISSUE THREAD

**Issue by Al-Kaiser** [arslancb/clipbucket#459]
hello

i try to create new html for categories that show up category thumbnail and category description and other stuff i plan to do

but when i try to get thumbnail direct from database i got it empty and after check the category_thumb row in database it's show empty ! but still i can see the category thumbnail in manage categories admin page

please i need help < sorry for my stupid stupid english

**Comment by fahad-cb** [comment]
you can find it in images/category_thumbs/[id].jpg
