### ISSUE TITLE
Video is not working properly

### ISSUE THREAD

**Issue by keysinex** [arslancb/clipbucket#461]
I installed the script to my domain and I'm having problems with watching the videos. Please assist me to resolve the issue. 

![microsoft edge 10_25_2018 11_22_48 am](https://user-images.githubusercontent.com/43112460/47533960-454c3780-d87b-11e8-89b9-adcf8de48c99.png)
![microsoft edge 10_25_2018 11_23_39 am](https://user-images.githubusercontent.com/43112460/47533961-454c3780-d87b-11e8-8279-60643107c469.png)

**Comment by janusz66** [comment]
I have all in mp4. For some reason Clipbucket do not like any other formats. I create my own thumbnails.

**Comment by glowf1sh** [comment]
I can confirm this. I pulled the recent version of clipbucket from GIT and it is not doing a thing when it comes to convert a video. Its a disaster. I tried like 3 different versions and none of them is working 100% .. the recent version 4.1 opens the convert log but then it does not start ffmpeg even the path and binary is correct, another version does convert with the same setup but it does ONLY convert HD and SD even i have checked to generate ALL .. and the third version of clipbucket is also not transcoding.

@arslancb Could you please bring out a new version that is really working ? I spent like 2 full days and all kinds of dirty tricks to got the old 2.8.3 version to work at least but it does not generate all file sizes. And 4.1 is not doing anything. It should work on a fresh install but it does not. Tried several video files, all kinds of ffmpeg, mp4box and other binaries.. even tried static binaries. nothing helped.. 

Whats also strange is, that the alpha lab video converter test tool is always stopping after step 1 when it says "file is convertible".. step 2 just says "please wait" and nothing happens.

also the generate language pack runs exactly ONE time, then stops at 32 % and then you cannot get it to run again.. you press the generate pack button and it turns grey and nothing happens.

Sorry to say but this is all very buggy and should not be called a stable release.

KR
daniel

**Comment by janusz66** [comment]
MP4 works fine, but the others I did not tested.

**Comment by glowf1sh** [comment]
> 
> 
> MP4 works fine, but the others I did not tested.

I guess this is because you checked "leave MP4 as it is" in your settings? The MP4 will not be transcoded then, thus it will - of course - work. But clipbucket is supposed to transcode things.. otherwise it just makes no sense for me.

KR
Daniel

**Comment by janusz66** [comment]
You are right. I try without unchecking the box and did not work. I have 2 web sites myfunnyvideos.net that run Clipbucket and jestarkel.com with WordPress. WordPress plugin allow me to upload video to a post and create thumbnails. I can not find any other open source software that will work.

**Comment by glowf1sh** [comment]
I like the concept and design of clipbucket.. however they bring in more errors with each release and i dont know what their q&a is doing because they release non-working versions. And you simply cannot debug anything when you dont get a logfile with useful information in it.

**Comment by zainjamil76** [comment]
![image](https://user-images.githubusercontent.com/55781706/68390101-6467ef80-0186-11ea-8856-66133a7ec5c3.png)

Everything fine with these???

**Comment by zaincb** [comment]
Hey @keysinex As you have seleceted (stay as mp4 file) option it will upload same as it is. If you want to convert the file you need to change the configurations from admin area > uploading and conversion settings.
Regards
Thanks.
