### ISSUE TITLE
Generate language pack is not working

### ISSUE THREAD

**Issue by glowf1sh** [arslancb/clipbucket#462]
When you click on "generate pack" in a fresh install it starts to translate phrases but it stopped at 32% without any error. It just didnt do anything anymore.

When you refresh the page and try to start the generation again nothing happens. You press the "generate pack" button and it turns grey but nothing else happens. Even if you wait 1 hour.

I tried to delete all kind of cache files but i was not able to trigger the "generate pack" process again. So i had to drop the fresh installation and start all over again with a new installation and database and guess what - it exactly worked one time up to 32 % .. i gave up on generating a language pack for german.

Please fix this and tell us how to reset the process. What files need to be deleted ? What DB value do we need to delete or alter to re-trigger the "generate pack" button again ?

KR
Daniel

**Comment by zaincb** [comment]
Hey @glowfishDE your issue was looked after and it will be updated within next release.
Thank you for your feedback.

Regards 
Thank you.
