### ISSUE TITLE
/upload and /videos not found and videos dont play

### ISSUE THREAD

**Issue by Puyodead1** [arslancb/clipbucket#464]
when i click on the Videos tab or click upload photo or upload video, it goes to an error msg: 
https://puyodead1-development.me/upload/
seems to happen also with account settings
When i change the end to .php it works fine

i also cannot play videos:
https://puyodead1-development.me/watch_video.php?v=GGYHSRBWYMH1

**Comment by fahad-cb** [comment]
@Puyodead1 are you still facing issue ? it seems everything working fine !
