### ISSUE TITLE
Uploading photos doesn't work with php7.2

### ISSUE THREAD

**Issue by Blisk** [arslancb/clipbucket#465]
I just found out that uploading photos doesn't work if I use php 7.2 it works on php5.6 but not on 7.2.
Any idea why?

**Comment by Blisk** [comment]
this still doesn't work on php 7.1 too

**Comment by Blisk** [comment]
Anything new regarding this?

**Comment by zainjamil76** [comment]
> I just found out that uploading photos doesn't work if I use php 7.2 it works on php5.6 but not on 7.2.
> Any idea why?

Are you still facing this issue on 7.1 & 7.2 ? Its seems perfect on my end.

**Comment by Blisk** [comment]
Yes it is still the same it doesn't work on 7.2
But I didn't do any update after that so I don't know if they repaired that already!

**Comment by zaincb** [comment]
hey @Blisk can you tell that you server configurations are right?

**Comment by Blisk** [comment]
Centos 7.6
php 5.6 or 7.1
apache 2.4.6
mysql 5.5.64
kernel 3.10.0-1062.1.2.el7.x86_64

**Comment by zaincb** [comment]
Everything fine with your php.ini file

**Comment by Blisk** [comment]
configurations and values
POST MAX SIZE
  5000M
UPLOAD MAX FILESIZE
  5000M
MEMORY LIMIT
  5000M
MAX EXECUTION TIME
  14400


Modules and paths
FFMPEG
FFmpeg is used to covert videos from different versions to FLV , MP4 and many other formats. Learn more
Version 8.5-36
PHP CLI
PHP CLI is used to peform video conversion in a background process. Learn more
Version 7.1.3
Media Info
MediaInfo supplies technical and tag information about a video or audio file. Learn more
Version 19.09
MP4Box
MP4Box is a tool used to repair MP4 files to make them streamable Learn more
Version 0.5.1
ImageMagick
Imagick is a native php extension to create and modify images using the ImageMagick API Learn more
Version 6.7.8-9

**Comment by zaincb** [comment]
Hey @Blisk 
When you upload your picture go to photo manager and check the picture should be uploaded and if we talk about save details button( will work on PHP version 7.0 ) and we are working on that( for PHP versions 7.1, 7.2 and 7.3 ). For now ( for PHP versions 7.1, 7.2 and 7.3 ) you can just upload it and go to your photo manager and edit details from there.

Button(Save Details) will be updated as soon as possible
I hope it will help you 
Thanks.

**Comment by Blisk** [comment]
Yes save details button doesn't work. Until you solve that I will stay on php 56.

**Comment by zaincb** [comment]
you can move on to php version 7.0 everything works perfect on php7.0

**Comment by Blisk** [comment]
thank you for info I have installed php 56 and php 71 so I can choose which one I can use. So until than I will also use php 56

**Comment by zaincb** [comment]
@Blisk  please check at your end. Its working fine on my end lemme know if the error is still there

**Comment by Blisk** [comment]
did you repair clipbucket files?

**Comment by zaincb** [comment]
Hey @Blisk .
Please switch your php to 7.2 or 7.1 and before uploading the picture : 
`SET GLOBAL sql_mode="";`
in your database and then check uploading your picture and please let me know .

![sql](https://user-images.githubusercontent.com/55781706/68645389-b7042b80-0539-11ea-9fba-846ec787c442.png)

OUTPUT:

![output](https://user-images.githubusercontent.com/55781706/68645408-c7b4a180-0539-11ea-8655-2557384e20c8.png)

And then try uploading picture and saving the details.

Thanks.

**Comment by Blisk** [comment]
Hi
Sorry doesn't work. Button save is still greyed out

**Comment by zaincb** [comment]
Hey @Blisk Can u please tell which OS and browser are you using.

**Comment by Blisk** [comment]
Clipbucket is installed on centos 7.6
I use windows 10 and tried upload picture in firefox, chrome and opera.
And none of it works, button Save Details is greyed out.
As far I remember in version 4.0 was the same and someone changed some file and it works but not on version 4.1

**Comment by zaincb** [comment]
@Blisk we are sorry for this. We are updating your issue and will be updated on next release.

Thanks.

**Comment by zaincb** [comment]
Hey @Blisk your issue is resolved. And will be updated on next release.
