### ISSUE TITLE
you have category: Basic, Gurus Comedian etc listed 3 times in members info

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#468]
User activity
Title:my videos
Description:cool videos
Joined: 3 months ago
Last Login:6 minutes ago
User Status:  online
Basic info
Relationship Status: Married
Category: Gurus
Location
Country:  Canada
Category: Gurus
Education, Hobbies, etc
Education: Master’s Degree
Category: Gurus

see photo

- ![capture](https://user-images.githubusercontent.com/17736688/50714275-af344a80-103d-11e9-80cb-1847d82a56f2.PNG)

**Comment by spirogg** [comment]
@aliawancb

**Comment by fahad-cb** [comment]
@spirogg thanks for notifying the issue, it has been fixed [here](https://github.com/arslancb/clipbucket/commit/25a91ef5698e47ebebcee7c12474981dd0212a00) .
