### ISSUE TITLE
Can't create new user on clipbucket-4939

### ISSUE THREAD

**Issue by d0v1k** [arslancb/clipbucket#470]
Fresh install of clipbucket-4939 on centos 7 nginx webserver with php70
i cant seem to create new user in the admin panel User > Add Member 
When i submit nothing happen no error the user did add to the database .

**Comment by fahad-cb** [comment]
write the following query with your mysql server `SET GLOBAL sql_mode='';`
Thanks

**Comment by d0v1k** [comment]
Thanks

**Comment by d0v1k** [comment]
> write the following query with your mysql server `SET GLOBAL sql_mode='';`
> Thanks

Thank work like a charm
