### ISSUE TITLE
No audio on iPhone

### ISSUE THREAD

**Issue by 4uba** [arslancb/clipbucket#472]
Hi,

I have deployed latest version of Clupbucket 4.2.1 Stable (freeware).

Video uploaded and converted successfully. Using any player there is no audio during video on iPhone.  Android, Windows 10 - both work well.

**Comment by zaincb** [comment]
Hey @4uba 
Its working perfect on every type of Iphone on my end i will recommend you to test it again at your end

Thank you for your feedback :)
