### ISSUE TITLE
PHP.INI POST MAX SIZE / UPLOAD MAX FILESIZE Size recognition error

### ISSUE THREAD

**Issue by ghost** [arslancb/clipbucket#473]
php.ini has the settings set to 1G for both POST MAX SIZE & UPLOAD MAX FILESIZE but is detected as an error.

![clipbucket_bug](https://user-images.githubusercontent.com/37916331/56204716-32812580-609c-11e9-8702-79708cb4b2f9.png)

**Comment by zaincb** [comment]
First of all make sure that you are configuring php.ini file of your current php version. 

POST MAX SIZE = 100M
UPLOAD MAX FILESIZE = 100M
MAX EXECUTION TIME = 7500

and restart your server ..

it will work :)
Thanks
