### ISSUE TITLE
Media Info + MP4Box : Impossible to find

### ISSUE THREAD

**Issue by mrfrieza** [arslancb/clipbucket#474]
Hello,

Working on Windows, everything installed on root C:/ 

![image](https://user-images.githubusercontent.com/34782455/57197207-bd02c980-6f64-11e9-97d7-aba54ef178ed.png)

But yet, even with the right paths, I have : 

![image](https://user-images.githubusercontent.com/34782455/57197214-e02d7900-6f64-11e9-85d5-318a6e841df8.png)

The paths are correct, the files I downloaded are from : 

Mp4box : https://gpac.wp.imt.fr/mp4box/
Mediainfo : https://mediaarea.net/en/MediaInfo

Only these 2 can't be found by ClipBucket, so is there a workaround or something I could do to make this work ? 

Thanks ! I'm kinda desperate...

**Comment by zaincb** [comment]
can u please share your paths? and screenshots of where that path goes
