### ISSUE TITLE
user categories bug

### ISSUE THREAD

**Issue by adam1000018** [arslancb/clipbucket#476]
Hi I found that user categories don't work well if we have more than 9 user categories.

If we have for example user category number 12, users from that category are also displayed in categories 1 and 2.

How to fix that?

**Comment by zaincb** [comment]
> Hi I found that user categories don't work well if we have more than 9 user categories.
> 
> If we have for example user category number 12, users from that category are also displayed in categories 1 and 2.
> 
> How to fix that?

well let me know if its still doing the same thing. its  working on my end
