### ISSUE TITLE
on firefox/waterfox/palemoon cannot choose resolution in specific area

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#480]
if click video itself it opens its own window and can choose resolution ok
![clipbucket1](https://user-images.githubusercontent.com/20878066/61999802-3b1fc980-b097-11e9-9bf4-ee0b5b4216f7.png)

if click vid name then try to do same the gap between player bottom and res options causes issues.
![clipbucket2](https://user-images.githubusercontent.com/20878066/61999808-52f74d80-b097-11e9-955a-9eedd78388ae.png)

this does not seem to happen on chrome browser. did not test IE or Edge

**Comment by zaincb** [comment]
Hey @dmaclip,
Thanks for your feedback. your issue has been fixed. The new release is coming soon. It will be fixed in next release.
Regards
Thank You.
