### ISSUE TITLE
lower bar in admin area not moving when sections expanded

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#481]
lower bar in admin area not moving when sections expanded
![clipbucket3](https://user-images.githubusercontent.com/20878066/61999842-0ceeb980-b098-11e9-87b8-f99608b83253.PNG)

**Comment by zaincb** [comment]
hey @dmaclip It might be your screen resolution issue. Its working perfectly fine to me and i guess to others users too.

Thanks :)
