### ISSUE TITLE
Disable Downloads

### ISSUE THREAD

**Issue by ghost** [arslancb/clipbucket#484]
Is there a way to disable downloads?

![2019-08-27 23_21_54](https://user-images.githubusercontent.com/54602650/63809000-87be2500-c921-11e9-903d-84658252d174.png)
![2019-08-27 23_22_11-Full HD Test 1080p - ](https://user-images.githubusercontent.com/54602650/63809001-87be2500-c921-11e9-8726-753b842e40f2.png)

**Comment by pctutorials** [comment]
yes you can disable it 
go to admin area--> select users---> select registered  user (to block download access to them )
go to general permission tab and disable download from the list adding screen short if you want further help ask me i can do it :)
![fo r](https://user-images.githubusercontent.com/54707178/64012934-52415380-cb3c-11e9-8b60-5905b3f3070d.PNG)
