### ISSUE TITLE
Private Clipbucket

### ISSUE THREAD

**Issue by ghost** [arslancb/clipbucket#485]
Is there a way to only see the website after logging in?

**Comment by pctutorials** [comment]
Am not official guide am just doing this as my hobby . but when i saw your question  it was interesting, 
as this site is made as clone or replica of youtube its been like we can view videos but for commenting posting on your own you have to signup else you can raise the  ticket at https://clipbucket.com and ask the expert help for  modifying the code by hiding index page and accessing login page

**Comment by aliawancb** [comment]
Yes, there is a switch for that in admin area > website configuration
