### ISSUE TITLE
is your code dead with full of bugs, its been 6 mos no updates and plenty of bugs..?

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#486]
Guys its been long time since you make any updates or bug fixes, this CB free edition is DEAD in my eyes. its been dead for long time, I use to love back in the day but now, you create enterprise edition and that even has bugs, sorry to say i test all your demos . 

Please either just say your dead in CB Free version or make some movement to update your script and release a lot of bug fixes..
2 make some changes to your pricing structure for old customers - 49.00 79.00 99.. we dont need enterprise . just a good solid working script.!!

**A lot of users use CB for long time and now you leave the guys in DARK after you create expensive CB. (that still has bugs)** 

-  **we are users that help you create the newest CB,** 
- **we suggest new features,**
-  **we help squash bugs** 

now after you make money you say **GOODBYE to old users that help you get up on your feet...** 

- **THIS IS NOT RIGHT.. any way good luck. CB I wish you well**

Regards
Spiro

**Comment by spirogg** [comment]
![Capture](https://user-images.githubusercontent.com/17736688/65380832-bf628780-dca9-11e9-9aed-0088e7a6520d.PNG)

**Comment by aliawancb** [comment]
Dear @spirogg,

V4 was released in 2018, V 4.3 was released in January 2019 and a new release is coming this week. There is a lot of debugging going around.
