### ISSUE TITLE
Regenerating video previews does not work

### ISSUE THREAD

**Issue by aliggie** [arslancb/clipbucket#490]
The regeneration of video previews does not work: when you click on the Regenerate button, the previews are not replaced with new ones, they remain the same

**Comment by zainjamil76** [comment]
> The regeneration of video previews does not work: when you click on the Regenerate button, the previews are not replaced with new ones, they remain the same

**Comment by zainjamil76** [comment]
> The regeneration of video previews does not work: when you click on the Regenerate button, the previews are not replaced with new ones, they remain the same

It might be your FFmpeg configuration issues. Its totally working proper boss!...

**Comment by zaincb** [comment]
> The regeneration of video previews does not work: when you click on the Regenerate button, the previews are not replaced with new ones, they remain the same

It might be your FFmpeg configuration issue. Its working properly on my end .

**Comment by aliggie** [comment]
It depends on the purpose of the button: If it is correct that at the click, the previews (present or not) are replaced with the same previews generated, then there is no problem. If instead at the click (present or not), the previews should change, then there is a problem.

I hope I was clear

**Comment by zaincb** [comment]
Hey @aliggie, 
Previews remain the same if the configurations are same as at the time of previous revision.
