### ISSUE TITLE
Repeated and non-unique description tag for each page

### ISSUE THREAD

**Issue by aliggie** [arslancb/clipbucket#491]
Hi,
the description tag of each page should be different. To date, every page (Homepage, Any video page, Videos, Photos, Channels, Collections) is indexed by google (and not well considered) with the same description. In the same way as it is possible to choose the title and description of the homepage in the administration panel, the same thing should be possible for the remaining pages that cannot be managed automatically (Videos, Photos, Channels, Collections), ie managing the description and title from the administration panel, while for the description of each video the automatic description can be taken from the description box present in each video.
Thanks

**Comment by zaincb** [comment]
Hey,
We have already this in our paid subscriptions 
https://clipbucket.com/pricing/

we have a proper plugin for this and if u want to get access you can visit our paid subscriptions plan :)

Thanks For Feedback.
