### ISSUE TITLE
Unable to access the admin panel after installation [CB v 4.2 RC1]

### ISSUE THREAD

**Issue by aliggie** [arslancb/clipbucket#493]
Hi, as reported here: https://forums.clipbucket.com/t/unable-to-access-the-admin-panel-after-installation-cb-v-4-2-rc1/3256

I made a new ClipBucket installation in locally using the 4.2 RC1 version package, at the end of the installation, it is not possible to access the administration panel.

- The menu item “Admin area” is not present
- If I try to access via url, ClipBucket returns that the administrator has no permissions

I can’t try version 4.2 RC1, because at the end of local installation, it is not possible to access the administration panel.

- “Admin area” entry not present in the in the drop-down menu at the top right.
- It is not possible to access via url, CB returns that I do not have permission to log in with the Admin user

I used the virgin package of version 4.2 RC1 available on github (I tried using the “upload” folder the “clipbucket-master.zip” package, then the Source Code [zip] package, they should be the same, but when in doubt I did a double test), at the end of the installation it is not possible to access the administration panel. The “Admin area” entry is not visible in the drop-down menu of the administrator user.

Forcing access from url by adding “/admin_area/” clipbucket returns that I do not have permission to access the administration

Try to reinstall CB using the CB v 4.2 RC1 package, then log in to the administration.

You should have more confidence in your users, you should have more confidence in my words and try to make a new installation locally. The current public package CB 4.2 RC1 is unusable, because the administration panel is inaccessible

**The same happens in the clipbucket demo**
I can’t access the demo admin panel

*** From this page:
http://demo.clipbucket.com/free/upload/admin_area/
or
http://demo.clipbucket.com/free/admin_area/login.php

user: admin
password: admin

Result: White page

*** From this page:
https://demo.clipbucket.com/free/signup?mode=login

user: admin
password: admin

Result: User Doesn’t Exist

Same problem I reported.
Solve the problem in the demo and in the official repository, please. Anyone cannot test the CB 4.2 RC1 version

Thanks

**Comment by zaincb** [comment]
Hey @aliggie we are working on your issue and will resolve it as soon as possible :)

**Comment by zaincb** [comment]
Just in your database set your sql_mode : 
`SET GLOBAL sql_mode="";`
![sql](https://user-images.githubusercontent.com/55781706/68385745-439a9c80-017c-11ea-845e-5bad61b21754.png)

OUTPUT: 
![output](https://user-images.githubusercontent.com/55781706/68385765-4eedc800-017c-11ea-86a7-bdd2ff4d67e5.png)

Then do the installation again on that database.

And if the issue remains then let me know :).

Thanks ;)

**Comment by aliggie** [comment]
I followed your advice and now it works ... With the command `SET GLOBAL sql_mode ="";` you set the variable sql_mode to the default values, but considering I haven't changed anything, I don't understand what the problem is. Perhaps due to the change of version of MariaDB, so it is necessary to adapt the installation instructions of ClipBucket ....
