### ISSUE TITLE
typo in function get_conversion_queue

### ISSUE THREAD

**Issue by oldskule** [arslancb/clipbucket#497]
V4.2 RC1, my_queries.class.php Line #1137
Contains "oder" instead of "order"

`$result = $db->select(tbl("conversion_queue"),"*",$cond,$limit,$oder);`

**Comment by zaincb** [comment]
Hey @oldskule 
Thanks for your feedback and letting us know. New release is coming soon and this will be updated in next coming release.

Regards 
Zain jamil.
