### ISSUE TITLE
in user profile. date does not work. using svn from today 

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#5]
Hi a few things to look into. Remove the need to add a website (url) in order for settings to be saved. This user might not@have website to add and keeps saying url not valid. 

Birthday. I tried to add my birth date 12-14-1970 does not save shows highlighted prior to saving. And gives me 03-01-0001 

In admin settings I edited date format from
Y-m-d to m-d-Y and it saved correctly, but doesn't seem to work in above user account settings (birthdate)

Is that the correct format to use for month date year dislay ? 
Or still a big.

**Comment by sakydev** [comment]
Issue has been resolved
