### ISSUE TITLE
Upload photo is still exist  in drop down menu but the photo section is disabled.

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#50]
Upload photo is still exist  in drop down menu but the photo section is disabled.

i have disabled the photo section and it exist every where like, channels page, view channel page, etc

![untitled-4](https://cloud.githubusercontent.com/assets/4317570/15090303/6d155436-143d-11e6-8a58-dda57a770735.png)

**Comment by sakydev** [comment]
Killed.
