### ISSUE TITLE
Missing directory in the 2.8.1 download

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#51]
during install you get this error images/backgrounds please chmod to 777, but there is no such directory.

**Comment by HAlexTM** [comment]
Just ignore it, works the same, I think that they missed it during the update :)

**Comment by spirogg** [comment]
I created the directory, before I finish setup and chmod to 777 then proceeded to finish install ??

**Comment by sakydev** [comment]
Just fixed. https://github.com/arslancb/clipbucket/commit/224fbd4988e53045d453d6e8239590e4ab5a3b8c
