### ISSUE TITLE
When I click the "OK, I agree, now let me continue" button, there is no response

### ISSUE THREAD

**Issue by hu279318344** [arslancb/clipbucket#511]
When I click the "OK, I agree, now let me continue" button, there is no response. I would like to inquire about any questions. Thank you. The platform environment is Linux（Centos 7） + nginx（1.18） + PHP（7.3） + MariaDB（10.3）

**Comment by aleytus** [comment]
[clipbucket.conf.txt](https://github.com/arslancb/clipbucket/files/5897348/clipbucket.conf.txt)
[nginx.conf.txt](https://github.com/arslancb/clipbucket/files/5897349/nginx.conf.txt)
MariaDB No Support (Only MySQL) ;-;

**Comment by aleytus** [comment]
[clipbucket.conf.txt](https://github.com/arslancb/clipbucket/files/5897354/clipbucket.conf.txt)
[nginx.conf.txt](https://github.com/arslancb/clipbucket/files/5897355/nginx.conf.txt)
MariaDB No Support (Only MySQL) ;-;

**Comment by aleytus** [comment]
https://github.com/aleytus/nginx-clipbucket
MariaDB No Support, only MySQL.
They could and add PDO ;-;

**Comment by MacWarrior** [comment]
Hello

@aleytus : You're wrong and mysql no longer exists on Debian per example as it was fully replaced by MariaDB since years
MariaDB is 99.99999999% (Ok, this number is probably wrong, but not far from truth) compatible with all apps using MySQL, and you absolutely don't need to switch to PDO to use MariaDB (And this is absolutely true :wink:)

@hu279318344 : You are probably facing some PHP 7.X issues ; current repo isn't PHP 7.X compatible and you might want to check my repo : https://github.com/MacWarrior/clipbucket-v5
In can also be linked with your nginx vhost configuration (As @aleytus may have tried to say) and you'll also find support for nginx on my repo

Best regards,
MacWarrior.

**Comment by aleytus** [comment]
@MacWarrior :thinking: I did not know!
Thanks for the config (001-clipbucket). I used your work.
Unfortunately it doesn't work on mingw without correct nginx.conf

I tried installing postgresql myself until I realized it was not supported :laughing:
Эх PDO бы завезли :cry:

**Comment by MacWarrior** [comment]
@aleytus I simply hate postgresql ; the simple fact that NULL != NULL drives me crazy !
Current CB use mysql functions and because switching to PDO would have requiered a huge refactor, I "only" updated to mysqli on my repo

Speaking of SQL, everybody should disable strict mode : I've made a lot of fixes about it, but there must be some more to do

**Comment by hu279318344** [comment]
> 
> 
> Hello
> 
> @aleytus : You're wrong and mysql no longer exists on Debian per example as it was fully replaced by MariaDB since years
> MariaDB is 99.99999999% (Ok, this number is probably wrong, but not far from truth) compatible with all apps using MySQL, and you absolutely don't need to switch to PDO to use MariaDB (And this is absolutely true 😉)
> 
> @hu279318344 : You are probably facing some PHP 7.X issues ; current repo isn't PHP 7.X compatible and you might want to check my repo : https://github.com/MacWarrior/clipbucket-v5
> In can also be linked with your nginx vhost configuration (As @aleytus may have tried to say) and you'll also find support for nginx on my repo
> 
> Best regards,
> MacWarrior.

thanks

**Comment by hu279318344** [comment]
> 
> 
> @aleytus I simply hate postgresql ; the simple fact that NULL != NULL drives me crazy !
> Current CB use mysql functions and because switching to PDO would have requiered a huge refactor, I "only" updated to mysqli on my repo
> 
> Speaking of SQL, everybody should disable strict mode : I've made a lot of fixes about it, but there must be some more to do

thanks

**Comment by hu279318344** [comment]
> 
> 
> @MacWarrior 🤔 I did not know!
> Thanks for the config (001-clipbucket). I used your work.
> Unfortunately it doesn't work on mingw without correct nginx.conf
> 
> I tried installing postgresql myself until I realized it was not supported 😆
> Эх PDO бы завезли 😢

thanks

**Comment by hu279318344** [comment]
> 
> 
> Hello
> 
> @aleytus : You're wrong and mysql no longer exists on Debian per example as it was fully replaced by MariaDB since years
> MariaDB is 99.99999999% (Ok, this number is probably wrong, but not far from truth) compatible with all apps using MySQL, and you absolutely don't need to switch to PDO to use MariaDB (And this is absolutely true 😉)
> 
> @hu279318344 : You are probably facing some PHP 7.X issues ; current repo isn't PHP 7.X compatible and you might want to check my repo : https://github.com/MacWarrior/clipbucket-v5
> In can also be linked with your nginx vhost configuration (As @aleytus may have tried to say) and you'll also find support for nginx on my repo
> 
> Best regards,
> MacWarrior.

thanks

**Comment by hu279318344** [comment]
> 
> 
> Hello
> 
> @aleytus : You're wrong and mysql no longer exists on Debian per example as it was fully replaced by MariaDB since years
> MariaDB is 99.99999999% (Ok, this number is probably wrong, but not far from truth) compatible with all apps using MySQL, and you absolutely don't need to switch to PDO to use MariaDB (And this is absolutely true 😉)
> 
> @hu279318344 : You are probably facing some PHP 7.X issues ; current repo isn't PHP 7.X compatible and you might want to check my repo : https://github.com/MacWarrior/clipbucket-v5
> In can also be linked with your nginx vhost configuration (As @aleytus may have tried to say) and you'll also find support for nginx on my repo
> 
> Best regards,
> MacWarrior.

thanks
