### ISSUE TITLE
CB 2.8.1 is Playing Highest Resolution by Default

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#53]
HI
       in the new player by default the highest resolution video playing. the default selected resolution should be 360p or 480p. i think its better for slow connections.

![untitled-2](https://cloud.githubusercontent.com/assets/4317570/15141002/6bf33d1c-16b7-11e6-949e-2437735741c1.png)

**Comment by fahad-cb** [comment]
This issue has been fixed , now player will set the appropriate resolution by default as 360
