### ISSUE TITLE
issue in Mp4 File Name 14629423861d125.mp4-1080.mp4 cb 2.8.1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#55]
The MP4 file Name have a small issue 14629423861d125**.mp4**-1080.mp4

![untitled-1](https://cloud.githubusercontent.com/assets/4317570/15171916/a164fb66-176b-11e6-997d-1f2bb2a04f0d.png)

**Comment by sakydev** [comment]
@fahad-cb You got another one to make you like "No wayyyyyyyyyyy" :imp:

**Comment by fahad-cb** [comment]
fixed
