### ISSUE TITLE
Player Resolution issue on Moblie cb 2.8.1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#56]
the new player have a small issue on mobile devices, i check it with android chrome browser. the lowest and highest resolution bot are selected check in bellow snapshot.

![screenshot_2016-05-11-11-31-13](https://cloud.githubusercontent.com/assets/4317570/15172051/a6744368-176c-11e6-803f-3454053aed4c.png)

**Comment by sakydev** [comment]
Fixed by @fahad-cb
