### ISSUE TITLE
Comments not working getting Fatal error cb 2.8.1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#58]
video & photo comments not working getting the following error 

i am using php 5.4.45

Fatal error: Can't use function return value in write context in /var/www/vhosts/pashto.xyz/httpdocs/cache/a867cb9e16123e16f86f448cdeb759963919310b.file.comment.html.php on line 87

**Comment by spirogg** [comment]
did you try to chmod ajax.php to 777 if that helps? or try 5.5 or 5.6 php.

**Comment by sakydev** [comment]
Fixed!
