### ISSUE TITLE
cannot try to upload a video as Anonymous User

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#68]
cannot try to upload a video as Anonymous User
http://discourse.clipbucket.com/t/clipbucket-2-8-1-beta-1-i-cannot-try-to-upload-a-video-as-anonymous-user/1765****

**Comment by fahad-cb** [comment]
Right now, if you set a user level to anonymous user of anyone , and it will work according to relative user level permissions

**Comment by sakydev** [comment]
Fixed!
