### ISSUE TITLE
Send message on user channel

### ISSUE THREAD

**Issue by husk04** [arslancb/clipbucket#7]
The send message icon at the right hand side of the banner on any user channel/profile does not work.
Whenever you click it the response is user does not exist.
I think that form of message sending is more efficient than the other method (send message) because not everybody will be able to remember the Username of the recipient. 
Please look into it.

**Comment by sakydev** [comment]
Issue has been resolved previously and fix is available in this ClipBucket repository if you do a checkout. Thank you for reporting anyway :+1:
