### ISSUE TITLE
missing semicolon in upgrade_2.8.1.sql for index_recent & index_featured

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#75]
i try to upgrade one of my 2.8 site to 2.8.1 after upgrade the home page was blank then i check the upgrade_2.8.1.sql to compare with **cb_config** table i found that the following setting is not insert in to config table due to missing the **semicolon** at the end of statement .

INSERT INTO `{tbl_prefix}config`(`name`, `value`) VALUES ('index_recent','6')
INSERT INTO `{tbl_prefix}config`(`name`, `value`) VALUES ('index_featured','2')

![untitled-8](https://cloud.githubusercontent.com/assets/4317570/15203549/651134c8-181e-11e6-8ceb-38914559af6c.png)

**Comment by sakydev** [comment]
It shouldn't have any effect on functionality, still, it will be fixed
