### ISSUE TITLE
Issue in Playlist when you upgrade it from 2.6 to 2.8.1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#76]
HI,
            today i checked one of my site that i was upgraded from 2.6 to 2.7 => 2.8 and today 2.8.1 the playlist was not shown on home page. then i found the playlist was not upgraded since 2.6..

try to upgrade from 2.6 and the latest one.. you will see the playlist table missing few fields.. i have manually added these field and the playlist start working..

**Comment by sakydev** [comment]
Issue is valid. Will be fixed.
