### ISSUE TITLE
 404 error when you select user in "My ACCOUNT"

### ISSUE THREAD

**Issue by husk04** [arslancb/clipbucket#9]
WHEN YOU CLICK "MY ACCOUNT" it shows you all recent videos with the uploader's name. But when you click the uploader's name which should take you to the user's channel or profile it returns a 404 ERROR.
Please look into this

i am taking time to point out all these glitches for your team.

**Comment by spirogg** [comment]
I also get this 404 error latest cb install from your site 
https://MYWEBSITE.com/view_user.php?uid=18 
or 
https://MYWEBSITE.com/view_user.php?uid=12
etc.. etc.. 

Spiro

**Comment by sakydev** [comment]
Thank you @husk04  for reporting this. I'm working on it.

**Comment by sakydev** [comment]
Issue has been fixed.
