### ISSUE TITLE
Coversion Lock Issue cb 2.8.1 rc1?

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#92]
i have upload some videos to my site after 1 video conversion when i check the Conversion Que manager **Delete Conversion Lock** button appear and videos stuck in processing mode..

![untitled-2](https://cloud.githubusercontent.com/assets/4317570/15350081/ac8f1262-1cf0-11e6-9b6b-7101238f56fb.png)

**Comment by sakydev** [comment]
Fixed
