### ISSUE TITLE
SEO Urls if off and i can't update video details.

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#94]
i want to video category but when i hit update button getting this msg "Title exceeds max length of 70 characters" but the SEO urls is turned off i am not using seo url.. 

please fix the issue.

![untitled-5](https://cloud.githubusercontent.com/assets/4317570/15353348/0790282a-1d02-11e6-9da5-923d0fcf07bb.png)

**Comment by sakydev** [comment]
Killed!
